(function () {
  'use strict';
  var list=document.querySelector('[data-call-list]'),search=document.querySelector('[data-call-search]'),feedback=document.querySelector('[data-call-feedback]'),picker=document.querySelector('[data-call-pick-contacts]');
  var friends=[],phoneContacts=[],people=[];
  function esc(v){return String(v||'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function normalizePhone(value){var p=String(value||'').replace(/[^\d+]/g,'');if(p.indexOf('+964')===0)p='0'+p.slice(4);if(p.indexOf('00964')===0)p='0'+p.slice(5);return p;}
  function safeTel(value){var p=normalizePhone(value);return /^0\d{9,10}$/.test(p)?p:'';}
  function avatar(p){var name=p.fullName||p.name||p.username||'؟',image=p.avatarUrl||(p.linkedUser&&p.linkedUser.avatarUrl)||'';return '<span class="avatar calls-avatar">'+(image?'<img src="'+esc(/^https?:\/\//i.test(image)?image:SocialAPI.baseUrl+image)+'" alt="">':esc(name.slice(0,1)))+(p.kind==='friend'?'<i class="presence '+(p.online?'online':'')+'"></i>':'')+'</span>';}
  function friendCard(p){var id=encodeURIComponent(p.id);return '<article class="call-contact">'+avatar(p)+'<a class="call-contact-copy" href="messages.html?user='+id+'"><strong>'+esc(p.fullName||p.name||'مستخدم')+'</strong><small>@'+esc(p.username||'غير متاح')+' · '+(p.online?'متصل الآن':'صديق على شنو منو')+'</small></a><div class="call-contact-actions"><a class="call-action chat" href="messages.html?user='+id+'">💬<span>رسالة</span></a><a class="call-action audio" href="messages.html?user='+id+'&call=audio">☎<span>صوت</span></a><a class="call-action video" href="messages.html?user='+id+'&call=video">▣<span>فيديو</span></a></div></article>';}
  function phoneCard(p){var phone=safeTel(p.phone),linked=p.linkedUser||null,isFriend=linked&&friends.some(function(f){return String(f.id)===String(linked.id);});var actions='<a class="call-action audio" href="tel:'+encodeURIComponent(phone)+'">📞<span>هاتف</span></a>';if(linked&&isFriend){var id=encodeURIComponent(linked.id);actions='<a class="call-action chat" href="messages.html?user='+id+'">💬<span>رسالة</span></a><a class="call-action audio" href="messages.html?user='+id+'&call=audio">☎<span>شنو منو</span></a><a class="call-action" href="tel:'+encodeURIComponent(phone)+'">📞<span>هاتف</span></a>';}else if(linked){actions='<a class="call-action chat" href="profile.html?id='+encodeURIComponent(linked.id)+'">👤<span>الملف</span></a>'+actions;}else{actions+='<a class="call-action chat" href="invite-friends.html">＋<span>دعوة</span></a>';}
    return '<article class="call-contact">'+avatar(p)+'<div class="call-contact-copy"><strong>'+esc(p.name||'جهة اتصال')+'</strong><small>'+esc(phone)+(linked?' · على شنو منو':' · غير مسجل')+'</small></div><div class="call-contact-actions">'+actions+'</div></article>';}
  function render(items){if(!items.length){list.innerHTML='<div class="social-empty"><span class="social-empty-icon">☎</span><strong>لا توجد جهات اتصال</strong><p>أضف أصدقاء أو اختر جهات من الهاتف.</p></div>';return;}list.innerHTML=items.map(function(p){return p.kind==='phone'?phoneCard(p):friendCard(p);}).join('');}
  function rebuild(){var seen={};people=[];friends.forEach(function(p){p.kind='friend';var key='u:'+p.id;if(!seen[key]){seen[key]=1;people.push(p);}});phoneContacts.forEach(function(p){var phone=safeTel(p.phone),key='p:'+phone;if(phone&&!seen[key]){seen[key]=1;p.kind='phone';people.push(p);}});render(people);}
  function loadStored(){try{var value=JSON.parse(localStorage.getItem('shnoPhoneContacts')||'[]');phoneContacts=Array.isArray(value)?value:[];}catch(_){phoneContacts=[];}}
  function saveStored(){try{localStorage.setItem('shnoPhoneContacts',JSON.stringify(phoneContacts.slice(0,200)));}catch(_){}}
  async function lookup(contact){var phone=safeTel(contact.phone);if(!phone)return contact;try{var d=await SocialAPI.request('/api/users/lookup-phone?phone='+encodeURIComponent(phone));if(d.user)contact.linkedUser=d.user;}catch(_){}return contact;}
  async function addContacts(selected){var incoming=[];(selected||[]).forEach(function(c){var numbers=c.tel||c.phoneNumbers||[];if(!Array.isArray(numbers))numbers=[numbers];numbers.forEach(function(value){var phone=safeTel(value&&value.value?value.value:value);if(phone)incoming.push({name:(c.name&&c.name[0])||c.displayName||c.name||'جهة اتصال',phone:phone,kind:'phone'});});});for(var i=0;i<incoming.length;i++)await lookup(incoming[i]);var map={};phoneContacts.concat(incoming).forEach(function(c){var key=safeTel(c.phone);if(key)map[key]=c;});phoneContacts=Object.keys(map).map(function(k){return map[k];});saveStored();rebuild();}
  async function pick(){if(picker)picker.disabled=true;try{if(navigator.contacts&&navigator.contacts.select){var selected=await navigator.contacts.select(['name','tel'],{multiple:true});await addContacts(selected);return;}if(window.ShnoManoContacts&&typeof window.ShnoManoContacts.pick==='function'){window.ShnoManoContacts.pick();return;}feedback.textContent='اختيار جهات الهاتف غير مدعوم في هذا المتصفح حالياً.';feedback.className='form-message is-error';}catch(e){if(e&&e.name!=='AbortError'){feedback.textContent='تعذر قراءة جهات الاتصال المختارة.';feedback.className='form-message is-error';}}finally{if(picker)picker.disabled=false;}}
  window.addEventListener('shnomano:contacts',function(e){addContacts(e.detail||[]);});
  async function load(){loadStored();try{var data=await SocialAPI.request('/api/friends');friends=(data.friends||data.users||data.data||[]).map(function(x){return x.user||x;});}catch(e){feedback.textContent=e.message;feedback.className='form-message is-error';friends=[];}for(var i=0;i<phoneContacts.length;i++){if(!phoneContacts[i].linkedUser)await lookup(phoneContacts[i]);}saveStored();rebuild();}
  var timer;search.addEventListener('input',function(){clearTimeout(timer);timer=setTimeout(function(){var q=search.value.trim().toLocaleLowerCase('ar');render(!q?people:people.filter(function(p){return String((p.fullName||p.name||'')+' '+(p.username||'')+' '+(p.phone||'')).toLocaleLowerCase('ar').includes(q);}));},120);});
  if(picker)picker.addEventListener('click',pick);
  load();
}());