(function(){
'use strict';
if(window.ShnoCommunicationDock)return;
var API=location.protocol==='file:'?'https://shino-mino-tak-tak.duckdns.org':location.origin;
var token=localStorage.getItem('token')||sessionStorage.getItem('token')||'';if(!token)return;
var rail=document.createElement('div');rail.className='shno-comm-rail';rail.hidden=true;document.body.appendChild(rail);
var launcher=document.createElement('button');launcher.className='shno-comm-launcher';launcher.type='button';launcher.textContent='☎ الاتصال والأصدقاء';document.body.appendChild(launcher);
var friends=[],socket=null,activeCall=null,ringTimer=null;
function esc(v){return String(v||'').replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c];});}
function qescape(v){return String(v||'').replace(/["\\]/g,'\\$&');}
function request(path,opt){opt=Object.assign({},opt||{});opt.headers=Object.assign({Accept:'application/json',Authorization:'Bearer '+token},opt.headers||{});return fetch(API+path,opt).then(async function(r){var d=await r.json().catch(function(){return{}});if(!r.ok)throw new Error(d.message||'تعذر الاتصال');return d;});}
function avatar(u,cls){var n=u.fullName||u.displayName||u.name||u.username||'؟',src=u.avatarUrl||(u.profile&&u.profile.avatarUrl)||'';return '<span class="'+(cls||'shno-comm-avatar')+'">'+(src?'<img src="'+esc(/^https?:/.test(src)?src:API+src)+'" alt="">':esc(n.slice(0,1)))+'</span>';}
function reveal(){rail.hidden=false;}function removeCard(card){card&&card.remove();if(!rail.children.length)rail.hidden=true;}
function contactCard(){var old=rail.querySelector('[data-comm-contacts]');if(old){old.scrollIntoView({behavior:'smooth',inline:'nearest'});return old;}var c=document.createElement('section');c.className='shno-comm-card is-contacts';c.dataset.commContacts='1';c.innerHTML='<header class="shno-comm-head"><strong>☎ الاتصال والأصدقاء</strong><button type="button" data-close>×</button></header><input class="shno-comm-search" type="search" placeholder="ابحث عن صديق"><div class="shno-comm-list"><div class="shno-comm-empty">جارٍ تحميل الأصدقاء…</div></div>';rail.prepend(c);reveal();c.querySelector('[data-close]').onclick=function(){removeCard(c)};var input=c.querySelector('input');input.oninput=function(){renderFriends(c,input.value)};loadFriends().then(function(){renderFriends(c,'')});return c;}
async function loadFriends(){try{var d=await request('/api/friends');friends=(d.friends||d.users||d.data||[]).map(function(x){return x.user||x;});}catch(_){friends=[];}return friends;}
function renderFriends(c,q){q=String(q||'').trim().toLowerCase();var items=friends.filter(function(u){return !q||String((u.fullName||u.displayName||'')+' '+(u.username||'')).toLowerCase().includes(q)});c.querySelector('.shno-comm-list').innerHTML=items.length?items.map(function(u){var id=esc(u.id||u._id),name=esc(u.fullName||u.displayName||u.username||'مستخدم');return '<div class="shno-comm-person" data-user="'+id+'">'+avatar(u)+'<span class="shno-comm-copy"><strong>'+name+'</strong><small>'+(u.online?'متصل الآن':'صديق على شنو منو')+'</small></span><span class="shno-comm-actions"><button type="button" data-chat title="مراسلة">💬</button><button type="button" data-call="audio" title="صوت">☎</button><button type="button" data-call="video" title="فيديو">📹</button></span></div>'}).join(''):'<div class="shno-comm-empty">لا توجد نتائج.</div>';}
function findUser(id){return friends.find(function(u){return String(u.id||u._id)===String(id)})||{id:id,fullName:'مستخدم شنو منو'};}
async function openChat(userId){var existing=rail.querySelector('[data-chat-user="'+qescape(String(userId))+'"]');if(existing){existing.scrollIntoView({behavior:'smooth',inline:'nearest'});return existing;}var u=findUser(userId),c=document.createElement('section');c.className='shno-comm-card';c.dataset.chatUser=String(userId);c.innerHTML='<header class="shno-comm-head">'+avatar(u)+'<strong>'+esc(u.fullName||u.displayName||u.username||'محادثة')+'</strong><button type="button" data-call="audio">☎</button><button type="button" data-call="video">📹</button><button type="button" data-close>×</button></header><div class="shno-chat-body"><div class="shno-comm-empty">جارٍ فتح المحادثة…</div></div><form class="shno-chat-compose"><textarea maxlength="5000" placeholder="اكتب رسالة…"></textarea><button>إرسال</button></form>';rail.appendChild(c);reveal();c.querySelector('[data-close]').onclick=function(){removeCard(c)};c.querySelectorAll('[data-call]').forEach(function(b){b.onclick=function(){startCall(userId,b.dataset.call)}});var conv;try{var d=await request('/api/conversations/'+encodeURIComponent(userId),{method:'POST'});conv=d.conversation;var m=await request('/api/conversations/'+encodeURIComponent(conv.id)+'/messages');renderChat(c,m.messages||[]);if(socket)socket.emit('private:join',String(conv.id));c.dataset.conversation=String(conv.id);}catch(e){c.querySelector('.shno-chat-body').innerHTML='<div class="shno-comm-empty">'+esc(e.message)+'</div>';}c.querySelector('form').onsubmit=async function(e){e.preventDefault();var t=c.querySelector('textarea'),text=t.value.trim();if(!text||!c.dataset.conversation)return;t.value='';try{await request('/api/conversations/'+encodeURIComponent(c.dataset.conversation)+'/messages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'text',text:text})});}catch(err){t.value=text;}};return c;}
function renderChat(c,items){var body=c.querySelector('.shno-chat-body');body.innerHTML=items.length?items.map(function(m){return '<div class="shno-chat-msg '+(m.mine?'mine':'')+'">'+esc(m.deletedForEveryone?'تم حذف هذه الرسالة':m.text||'وسائط')+'<time>'+(m.createdAt?new Date(m.createdAt).toLocaleTimeString('ar-IQ',{hour:'2-digit',minute:'2-digit'}):'')+'</time></div>'}).join(''):'<div class="shno-comm-empty">لا توجد رسائل بعد.</div>';body.scrollTop=body.scrollHeight;}
function callCard(payload,incoming){var old=rail.querySelector('[data-call-card]');if(old)old.remove();var u=findUser(payload.from||payload.userId),name=payload.callerName||u.fullName||u.displayName||'مستخدم شنو منو',c=document.createElement('section');c.className='shno-comm-card shno-call-card';c.dataset.callCard='1';c.innerHTML='<header class="shno-comm-head"><strong>'+(payload.type==='video'?'📹 مكالمة فيديو':'☎ مكالمة صوتية')+'</strong><button type="button" data-close>×</button></header><div class="shno-call-main"><div>'+avatar(Object.assign({},u,{fullName:name}),'shno-call-avatar')+'<h3>'+esc(name)+'</h3><div class="shno-call-status">'+(incoming?'مكالمة واردة':'جارٍ الاتصال…')+'</div><div class="shno-call-buttons">'+(incoming?'<button class="shno-call-accept" data-accept>✓</button>':'')+'<button class="shno-call-reject" data-reject>✕</button></div></div></div>';rail.appendChild(c);reveal();c.querySelector('[data-close]').onclick=function(){rejectCall('closed')};c.querySelector('[data-reject]').onclick=function(){rejectCall('rejected')};if(incoming)c.querySelector('[data-accept]').onclick=function(){acceptCall()};return c;}
function tone(start){if(!start){if(ringTimer){clearInterval(ringTimer);ringTimer=null}return}function beep(){try{var C=window.AudioContext||window.webkitAudioContext,ctx=new C(),o=ctx.createOscillator(),g=ctx.createGain();o.connect(g);g.connect(ctx.destination);o.frequency.value=620;g.gain.value=.06;o.start();setTimeout(function(){o.stop();ctx.close()},550)}catch(_){}}beep();ringTimer=setInterval(beep,1800);}
async function startCall(userId,type){if(!socket){contactCard();return;}try{var d=await request('/api/conversations/'+encodeURIComponent(userId),{method:'POST'});activeCall={callId:(window.crypto&&crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random()),userId:String(userId),conversationId:String(d.conversation.id),type:type==='video'?'video':'audio',incoming:false};callCard({userId:userId,type:activeCall.type},false);socket.emit('call:invite',activeCall,function(r){var s=rail.querySelector('.shno-call-status');if(r&&r.ok){if(s)s.textContent='يرن…';tone(true)}else{if(s)s.textContent=(r&&r.message)||'تعذر الاتصال';setTimeout(function(){finishCall()},2500)}});}catch(e){alert(e.message)}}
function receiveCall(p){if(!p||!p.callId)return;if(activeCall&&activeCall.callId!==String(p.callId)){socket.emit('call:reject',{callId:p.callId,userId:p.from,conversationId:p.conversationId,type:p.type,reason:'busy'});return;}activeCall={callId:String(p.callId),userId:String(p.from),conversationId:String(p.conversationId),type:p.type==='video'?'video':'audio',incoming:true};callCard(p,true);tone(true);try{if('Notification'in window&&Notification.permission==='granted')new Notification('مكالمة واردة من '+(p.callerName||'شنو منو'),{body:p.type==='video'?'مكالمة فيديو':'مكالمة صوتية'})}catch(_){}}
function payload(extra){return Object.assign({callId:activeCall.callId,userId:activeCall.userId,conversationId:activeCall.conversationId,type:activeCall.type},extra||{})}
function acceptCall(){if(!activeCall)return;tone(false);socket.emit('call:accept',payload(),function(r){var s=rail.querySelector('.shno-call-status');if(r&&r.ok){if(s)s.textContent='تم القبول — جارٍ إنشاء الاتصال';}else finishCall()});}
function rejectCall(reason){if(activeCall&&socket)socket.emit('call:reject',payload({reason:reason||'rejected'}));finishCall()}
function finishCall(){tone(false);activeCall=null;removeCard(rail.querySelector('[data-call-card]'));}
function bindSocket(s){if(!s||s.__shnoCommBound)return;s.__shnoCommBound=true;socket=s;s.on('call:invite',receiveCall);s.on('call:reject',finishCall);s.on('call:end',finishCall);s.on('call:accept',function(){tone(false);var st=rail.querySelector('.shno-call-status');if(st)st.textContent='تم قبول المكالمة';});s.on('private:message',function(p){var cards=rail.querySelectorAll('[data-chat-user]');for(var i=0;i<cards.length;i++){var c=cards[i];if(String(c.dataset.conversation)!==String(p.conversationId))continue;var body=c.querySelector('.shno-chat-body'),m=p.message||p;body.insertAdjacentHTML('beforeend','<div class="shno-chat-msg">'+esc(m.text||'وسائط')+'</div>');body.scrollTop=body.scrollHeight;break;}})}
function ensureSocket(){if(window.ShnoPresenceSocket){bindSocket(window.ShnoPresenceSocket);return}if(window.io){bindSocket(window.io(API,{auth:{token:token},transports:['websocket','polling'],reconnection:true}));return}setTimeout(ensureSocket,350)}
rail.addEventListener('click',function(e){var row=e.target.closest('[data-user]');if(!row)return;var id=row.dataset.user;if(e.target.closest('[data-call]'))startCall(id,e.target.closest('[data-call]').dataset.call);else openChat(id)});launcher.onclick=contactCard;
function interceptLegacyNavigation(e){var a=e.target.closest&&e.target.closest('a[href]');if(!a)return;var raw=a.getAttribute('href')||'';if(!/(?:^|\/)messages\.html(?:[?#]|$)|(?:^|\/)calls\.html(?:[?#]|$)/i.test(raw))return;try{var u=new URL(a.href,location.href),path=u.pathname.split('/').pop(),user=u.searchParams.get('user');if(path==='messages.html'&&user){e.preventDefault();e.stopPropagation();var mode=u.searchParams.get('call')||u.searchParams.get('prepare');if(mode==='audio'||mode==='video')startCall(user,mode);else openChat(user);return;}e.preventDefault();e.stopPropagation();contactCard();}catch(_){}}
document.addEventListener('click',interceptLegacyNavigation,true);
ensureSocket();window.ShnoCommunicationDock={open:contactCard,chat:openChat,call:startCall};
}());