(function(){
'use strict';
if(window.ShnoCommunicationDock)return;
var API=location.protocol==='file:'?'https://shino-mino-tak-tak.duckdns.org':location.origin;
var token=localStorage.getItem('token')||sessionStorage.getItem('token')||'';if(!token)return;
var rail=document.createElement('div');rail.className='shno-comm-rail';rail.hidden=true;document.body.appendChild(rail);
var launcher=document.createElement('button');launcher.className='shno-comm-launcher';launcher.type='button';launcher.textContent='☎ الاتصال والأصدقاء';launcher.setAttribute('aria-expanded','false');document.body.appendChild(launcher);
var friends=[],socket=null,activeCall=null,ringTimer=null,localStream=null,peer=null,pendingIce=[],connectionTimer=null;
function esc(v){return String(v||'').replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function qescape(v){return String(v||'').replace(/["\\]/g,'\\$&');}
function request(path,opt){opt=Object.assign({},opt||{});opt.headers=Object.assign({Accept:'application/json',Authorization:'Bearer '+token},opt.headers||{});return fetch(API+path,opt).then(async function(r){var d=await r.json().catch(function(){return{}});if(!r.ok)throw new Error(d.message||'تعذر الاتصال');return d;});}
function avatar(u,cls){var n=u.fullName||u.displayName||u.name||u.username||'؟',src=u.avatarUrl||(u.profile&&u.profile.avatarUrl)||'';return '<span class="'+(cls||'shno-comm-avatar')+'">'+(src?'<img src="'+esc(/^https?:/.test(src)?src:API+src)+'" alt="">':esc(n.slice(0,1)))+'</span>';}
function reveal(){rail.hidden=false;launcher.setAttribute('aria-expanded','true');}function conceal(){rail.hidden=true;launcher.setAttribute('aria-expanded','false');}function removeCard(card){card&&card.remove();if(!rail.children.length)conceal();}
function contactCard(){var old=rail.querySelector('[data-comm-contacts]');if(old){reveal();old.scrollIntoView({behavior:'smooth',inline:'nearest'});return old;}var c=document.createElement('section');c.className='shno-comm-card is-contacts';c.dataset.commContacts='1';c.innerHTML='<header class="shno-comm-head"><strong>☎ الاتصال والأصدقاء</strong><a class="shno-comm-page-link" href="calls.html" data-comm-page>شنو منو اتصال ↗</a><button type="button" data-close>×</button></header><input class="shno-comm-search" type="search" placeholder="ابحث عن صديق"><div class="shno-comm-list"><div class="shno-comm-empty">جارٍ تحميل الأصدقاء…</div></div>';rail.prepend(c);reveal();c.querySelector('[data-close]').onclick=function(){removeCard(c)};var input=c.querySelector('input');input.oninput=function(){renderFriends(c,input.value)};loadFriends().then(function(){renderFriends(c,'')});return c;}
async function loadFriends(){try{var d=await request('/api/friends');friends=(d.friends||d.users||d.data||[]).map(function(x){return x.user||x;});}catch(_){friends=[];}return friends;}
function renderFriends(c,q){q=String(q||'').trim().toLowerCase();var items=friends.filter(function(u){return !q||String((u.fullName||u.displayName||'')+' '+(u.username||'')).toLowerCase().includes(q)});c.querySelector('.shno-comm-list').innerHTML=items.length?items.map(function(u){var id=esc(u.id||u._id),name=esc(u.fullName||u.displayName||u.username||'مستخدم');return '<div class="shno-comm-person" data-user="'+id+'">'+avatar(u)+'<span class="shno-comm-copy"><strong>'+name+'</strong><small>'+(u.online?'متصل الآن':'صديق على شنو منو')+'</small></span><span class="shno-comm-actions"><button type="button" data-chat title="مراسلة">💬</button><button type="button" data-call="audio" title="صوت">☎</button><button type="button" data-call="video" title="فيديو">📹</button></span></div>'}).join(''):'<div class="shno-comm-empty">لا توجد نتائج.</div>';}
function findUser(id){return friends.find(function(u){return String(u.id||u._id)===String(id)})||{id:id,fullName:'مستخدم شنو منو'};}
async function openChat(userId){var existing=rail.querySelector('[data-chat-user="'+qescape(String(userId))+'"]');if(existing){existing.scrollIntoView({behavior:'smooth',inline:'nearest'});return existing;}var u=findUser(userId),c=document.createElement('section');c.className='shno-comm-card';c.dataset.chatUser=String(userId);c.innerHTML='<header class="shno-comm-head">'+avatar(u)+'<strong>'+esc(u.fullName||u.displayName||u.username||'محادثة')+'</strong><button type="button" data-call="audio">☎</button><button type="button" data-call="video">📹</button><button type="button" data-close>×</button></header><div class="shno-chat-body"><div class="shno-comm-empty">جارٍ فتح المحادثة…</div></div><form class="shno-chat-compose"><textarea maxlength="5000" placeholder="اكتب رسالة…"></textarea><button>إرسال</button></form>';rail.appendChild(c);reveal();c.querySelector('[data-close]').onclick=function(){removeCard(c)};c.querySelectorAll('[data-call]').forEach(function(b){b.onclick=function(){startCall(userId,b.dataset.call)}});var conv;try{var d=await request('/api/conversations/'+encodeURIComponent(userId),{method:'POST'});conv=d.conversation;var m=await request('/api/conversations/'+encodeURIComponent(conv.id)+'/messages');renderChat(c,m.messages||[]);if(socket)socket.emit('private:join',String(conv.id));c.dataset.conversation=String(conv.id);}catch(e){c.querySelector('.shno-chat-body').innerHTML='<div class="shno-comm-empty">'+esc(e.message)+'</div>';}c.querySelector('form').onsubmit=async function(e){e.preventDefault();var t=c.querySelector('textarea'),text=t.value.trim();if(!text||!c.dataset.conversation)return;t.value='';try{await request('/api/conversations/'+encodeURIComponent(c.dataset.conversation)+'/messages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'text',text:text})});}catch(err){t.value=text;}};return c;}
function renderChat(c,items){var body=c.querySelector('.shno-chat-body');body.innerHTML=items.length?items.map(function(m){return '<div class="shno-chat-msg '+(m.mine?'mine':'')+'">'+esc(m.deletedForEveryone?'تم حذف هذه الرسالة':m.text||'وسائط')+'<time>'+(m.createdAt?new Date(m.createdAt).toLocaleTimeString('ar-IQ',{hour:'2-digit',minute:'2-digit'}):'')+'</time></div>'}).join(''):'<div class="shno-comm-empty">لا توجد رسائل بعد.</div>';body.scrollTop=body.scrollHeight;}
function callCard(payload,incoming){var old=rail.querySelector('[data-call-card]');if(old)old.remove();var u=findUser(payload.from||payload.userId),name=payload.callerName||u.fullName||u.displayName||'مستخدم شنو منو',c=document.createElement('section');c.className='shno-comm-card shno-call-card';c.dataset.callCard='1';c.innerHTML='<header class="shno-comm-head"><strong>'+(payload.type==='video'?'📹 مكالمة فيديو':'☎ مكالمة صوتية')+'</strong><button type="button" data-close>×</button></header><div class="shno-call-media"><video autoplay playsinline data-comm-remote-video></video><video autoplay playsinline muted data-comm-local-video></video><audio autoplay data-comm-remote-audio></audio></div><div class="shno-call-main"><div>'+avatar(Object.assign({},u,{fullName:name}),'shno-call-avatar')+'<h3>'+esc(name)+'</h3><div class="shno-call-status">'+(incoming?'مكالمة واردة':'جارٍ الاتصال…')+'</div><div class="shno-call-buttons">'+(incoming?'<button class="shno-call-accept" data-accept title="قبول">✓</button>':'')+'<button class="shno-call-reject" data-reject title="رفض/إنهاء">✕</button></div><div class="shno-call-live-controls" hidden><button type="button" data-mute>🎙️ كتم</button><button type="button" data-camera>📹 كاميرا</button><button type="button" data-end>إنهاء</button></div></div></div>';rail.appendChild(c);reveal();c.querySelector('[data-close]').onclick=function(){endCall(true,'closed')};c.querySelector('[data-reject]').onclick=function(){if(activeCall&&activeCall.incoming&&activeCall.state!=='accepted')rejectCall('rejected');else endCall(true,'ended')};if(incoming)c.querySelector('[data-accept]').onclick=function(){acceptCall()};c.querySelector('[data-end]').onclick=function(){endCall(true,'ended')};c.querySelector('[data-mute]').onclick=function(){toggleMute(c)};c.querySelector('[data-camera]').onclick=function(){toggleCamera(c)};return c;}
function setCallStatus(text){var s=rail.querySelector('.shno-call-status');if(s)s.textContent=text;}
function setLiveControls(show){var x=rail.querySelector('.shno-call-live-controls');if(x)x.hidden=!show;var b=rail.querySelector('.shno-call-buttons');if(b)b.hidden=!!show;}
function tone(start){if(!start){if(ringTimer){clearInterval(ringTimer);ringTimer=null}return}if(ringTimer)return;function beep(){try{var C=window.AudioContext||window.webkitAudioContext,ctx=new C(),o=ctx.createOscillator(),g=ctx.createGain();o.connect(g);g.connect(ctx.destination);o.frequency.value=620;g.gain.value=.06;o.start();setTimeout(function(){try{o.stop();ctx.close()}catch(_){}},550)}catch(_){}}beep();ringTimer=setInterval(beep,1800);}
function payload(extra){if(!activeCall)return extra||{};return Object.assign({callId:activeCall.callId,userId:activeCall.userId,conversationId:activeCall.conversationId,type:activeCall.type},extra||{})}
async function getMedia(){if(localStream)return localStream;if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia)throw new Error('الميكروفون أو الكاميرا غير مدعومين في هذا الجهاز');localStream=await navigator.mediaDevices.getUserMedia({audio:true,video:activeCall&&activeCall.type==='video'});var lv=rail.querySelector('[data-comm-local-video]');if(lv&&activeCall.type==='video'){lv.srcObject=localStream;lv.hidden=false;lv.play().catch(function(){})}return localStream;}
function ensurePeer(){if(peer)return peer;peer=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'}]});if(localStream)localStream.getTracks().forEach(function(t){peer.addTrack(t,localStream)});peer.ontrack=function(e){var stream=e.streams&&e.streams[0];if(!stream)return;var card=rail.querySelector('[data-call-card]');if(!card)return;if(activeCall&&activeCall.type==='video'){var rv=card.querySelector('[data-comm-remote-video]');rv.srcObject=stream;rv.hidden=false;rv.play().catch(function(){})}else{var ra=card.querySelector('[data-comm-remote-audio]');ra.srcObject=stream;ra.play().catch(function(){})}};peer.onicecandidate=function(e){if(e.candidate&&socket&&activeCall)socket.emit('webrtc:ice',payload({data:e.candidate}))};peer.onconnectionstatechange=function(){if(!peer)return;var st=peer.connectionState;if(st==='connected'){clearTimeout(connectionTimer);setCallStatus('متصل الآن');setLiveControls(true)}else if(st==='failed'||st==='closed'){endCall(true,'connection-failed')}else if(st==='disconnected'){clearTimeout(connectionTimer);connectionTimer=setTimeout(function(){if(peer&&peer.connectionState==='disconnected')endCall(true,'disconnected')},8000)}};return peer;}
async function flushIce(){if(!peer||!peer.remoteDescription)return;while(pendingIce.length){try{await peer.addIceCandidate(pendingIce.shift())}catch(_){}}}
async function createAndSendOffer(){try{await getMedia();var p=ensurePeer(),offer=await p.createOffer();await p.setLocalDescription(offer);socket.emit('webrtc:offer',payload({data:p.localDescription}),function(r){if(!r||!r.ok)setCallStatus('تعذر بدء الصوت/الفيديو')})}catch(e){setCallStatus(e.message||'تعذر الوصول للمايك/الكاميرا');setTimeout(function(){endCall(true,'media-error')},2000)}}
async function handleOffer(p){if(!activeCall||String(p.callId)!==String(activeCall.callId))return;try{await getMedia();var pc=ensurePeer();await pc.setRemoteDescription(new RTCSessionDescription(p.data));await flushIce();var answer=await pc.createAnswer();await pc.setLocalDescription(answer);socket.emit('webrtc:answer',payload({data:pc.localDescription}));activeCall.state='accepted';setCallStatus('جارٍ توصيل المكالمة…');setLiveControls(true)}catch(e){setCallStatus('تعذر إنشاء الاتصال');endCall(true,'offer-error')}}
async function handleAnswer(p){if(!activeCall||String(p.callId)!==String(activeCall.callId)||!peer)return;try{await peer.setRemoteDescription(new RTCSessionDescription(p.data));await flushIce();setCallStatus('جارٍ توصيل المكالمة…')}catch(_){endCall(true,'answer-error')}}
async function handleIce(p){if(!activeCall||String(p.callId)!==String(activeCall.callId)||!p.data)return;try{var candidate=new RTCIceCandidate(p.data);if(peer&&peer.remoteDescription)await peer.addIceCandidate(candidate);else pendingIce.push(candidate)}catch(_){}}
function cleanupMedia(){tone(false);clearTimeout(connectionTimer);connectionTimer=null;if(peer){try{peer.ontrack=peer.onicecandidate=peer.onconnectionstatechange=null;peer.close()}catch(_){}peer=null}if(localStream){localStream.getTracks().forEach(function(t){try{t.stop()}catch(_){}});localStream=null}pendingIce=[];}
function finishCall(){cleanupMedia();activeCall=null;removeCard(rail.querySelector('[data-call-card]'));}
function endCall(notify,reason){if(notify&&activeCall&&socket)socket.emit('call:end',payload({reason:reason||'ended'}));finishCall();}
function rejectCall(reason){if(activeCall&&socket)socket.emit('call:reject',payload({reason:reason||'rejected'}));finishCall();}
function toggleMute(c){if(!localStream)return;var tracks=localStream.getAudioTracks();if(!tracks.length)return;tracks.forEach(function(t){t.enabled=!t.enabled});var muted=!tracks[0].enabled,b=c.querySelector('[data-mute]');if(b)b.textContent=muted?'🔇 تشغيل الصوت':'🎙️ كتم';}
function toggleCamera(c){if(!localStream)return;var tracks=localStream.getVideoTracks();if(!tracks.length)return;tracks.forEach(function(t){t.enabled=!t.enabled});var off=!tracks[0].enabled,b=c.querySelector('[data-camera]');if(b)b.textContent=off?'📷 تشغيل الكاميرا':'📹 إيقاف الكاميرا';}
async function startCall(userId,type){if(!socket||!socket.connected){contactCard();return;}if(activeCall){setCallStatus('هناك مكالمة جارية');return;}try{var d=await request('/api/conversations/'+encodeURIComponent(userId),{method:'POST'});activeCall={callId:(window.crypto&&crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random()),userId:String(userId),conversationId:String(d.conversation.id),type:type==='video'?'video':'audio',incoming:false,state:'inviting'};callCard({userId:userId,type:activeCall.type},false);socket.emit('call:invite',activeCall,function(r){if(r&&r.ok){activeCall.state='ringing';setCallStatus('يرن عند الطرف الآخر…');}else{setCallStatus=(typeof setCallStatus==='function'?setCallStatus:function(){});setCallStatus((r&&r.message)||'تعذر الاتصال');setTimeout(finishCall,2200)}});}catch(e){alert(e.message)}}
function receiveCall(p){if(!p||!p.callId)return;if(activeCall&&activeCall.callId!==String(p.callId)){socket.emit('call:reject',{callId:p.callId,userId:p.from,conversationId:p.conversationId,type:p.type,reason:'busy'});return;}activeCall={callId:String(p.callId),userId:String(p.from),conversationId:String(p.conversationId),type:p.type==='video'?'video':'audio',incoming:true,state:'ringing'};callCard(p,true);tone(true);try{if('Notification'in window&&Notification.permission==='granted')new Notification('مكالمة واردة من '+(p.callerName||'شنو منو'),{body:p.type==='video'?'مكالمة فيديو':'مكالمة صوتية'})}catch(_){}}
async function acceptCall(){if(!activeCall||!activeCall.incoming)return;tone(false);var btn=rail.querySelector('[data-accept]');if(btn)btn.disabled=true;setCallStatus('جارٍ فتح الميكروفون…');try{await getMedia();ensurePeer();socket.emit('call:accept',payload(),function(r){if(r&&r.ok){activeCall.state='accepted';setCallStatus('تم القبول — بانتظار الاتصال…');setLiveControls(true)}else{setCallStatus((r&&r.message)||'تعذر قبول المكالمة');setTimeout(finishCall,1800)}})}catch(e){setCallStatus(e.message||'تعذر الوصول للمايك/الكاميرا');socket.emit('call:reject',payload({reason:'media-denied'}));setTimeout(finishCall,1800)}}
function handleAccepted(p){if(!activeCall||String(p.callId)!==String(activeCall.callId)||activeCall.incoming)return;tone(false);activeCall.state='accepted';setCallStatus('تم القبول — جارٍ إنشاء الاتصال…');setLiveControls(true);createAndSendOffer();}
function bindSocket(s){if(!s||s.__shnoCommBound)return;s.__shnoCommBound=true;socket=s;s.on('call:invite',receiveCall);s.on('call:reject',function(p){if(!activeCall||!p||String(p.callId)===String(activeCall.callId))finishCall()});s.on('call:end',function(p){if(!activeCall||!p||String(p.callId)===String(activeCall.callId))finishCall()});s.on('call:accept',handleAccepted);s.on('webrtc:offer',handleOffer);s.on('webrtc:answer',handleAnswer);s.on('webrtc:ice',handleIce);s.on('private:message',function(p){var cards=rail.querySelectorAll('[data-chat-user]');for(var i=0;i<cards.length;i++){var c=cards[i];if(String(c.dataset.conversation)!==String(p.conversationId))continue;var body=c.querySelector('.shno-chat-body'),m=p.message||p;body.insertAdjacentHTML('beforeend','<div class="shno-chat-msg">'+esc(m.text||'وسائط')+'</div>');body.scrollTop=body.scrollHeight;break;}})}
function ensureSocket(){if(window.ShnoPresenceSocket){bindSocket(window.ShnoPresenceSocket);return}if(window.io){bindSocket(window.io(API,{auth:{token:token},transports:['websocket','polling'],reconnection:true}));return}setTimeout(ensureSocket,350)}
rail.addEventListener('click',function(e){var row=e.target.closest('[data-user]');if(!row)return;var id=row.dataset.user;if(e.target.closest('[data-call]'))startCall(id,e.target.closest('[data-call]').dataset.call);else openChat(id)});launcher.onclick=function(){if(!rail.hidden){conceal();return;}contactCard();};
function interceptLegacyNavigation(e){var a=e.target.closest&&e.target.closest('a[href]');if(!a||a.hasAttribute('data-comm-page'))return;var raw=a.getAttribute('href')||'';if(!/(?:^|\/)messages\.html(?:[?#]|$)/i.test(raw))return;try{var u=new URL(a.href,location.href),path=u.pathname.split('/').pop(),user=u.searchParams.get('user');if(path==='messages.html'&&user){e.preventDefault();e.stopPropagation();var mode=u.searchParams.get('call')||u.searchParams.get('prepare');if(mode==='audio'||mode==='video')startCall(user,mode);else openChat(user);}}catch(_){}}
document.addEventListener('click',interceptLegacyNavigation,true);
window.addEventListener('beforeunload',function(){if(activeCall&&socket)socket.emit('call:end',payload({reason:'page-leave'}));cleanupMedia()});
ensureSocket();window.ShnoCommunicationDock={open:contactCard,chat:openChat,call:startCall};
}());
