(function(){'use strict';
const $=s=>document.querySelector(s),params=new URLSearchParams(location.search),roomId=params.get('room');let room=null,me='',filter='',peopleMode='friends',selectedTile='';
const req=(p,o)=>SocialAPI.request(p,o),id=x=>String(x?.id||x?._id||x||''),name=x=>x?.name||x?.fullName||x?.displayName||x?.username||'لاعب',esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function msg(s,e=false){const x=$('[data-feedback]')||$('[data-lobby-feedback]');if(x){x.textContent=s;x.className='form-message '+(e?'is-error':'is-success');x.classList.remove('feedback-pop');void x.offsetWidth;x.classList.add('feedback-pop')}showToast(s,e)}
function showToast(s,e=false){let t=$('.game-toast');if(!t){t=document.createElement('div');t.className='game-toast';document.body.appendChild(t)}t.textContent=s;t.className='game-toast show '+(e?'error':'success');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),2300)}
function apiBody(method,body){return{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body||{})}}
async function action(btn,loading,fn,success){if(!btn||btn.dataset.busy==='1')return;const old=btn.innerHTML;btn.dataset.busy='1';btn.disabled=true;btn.classList.add('is-loading');btn.innerHTML='<span class="btn-spinner"></span>'+loading;try{const out=await fn();btn.classList.remove('is-loading');btn.classList.add('is-success');btn.innerHTML='✓ '+(success||'تم');setTimeout(()=>{btn.innerHTML=old;btn.classList.remove('is-success');btn.disabled=false;btn.dataset.busy='0'},950);return out}catch(e){btn.classList.remove('is-loading');btn.classList.add('is-error');btn.innerHTML='⚠ تعذر';msg(e.message||'تعذر تنفيذ الطلب',true);setTimeout(()=>{btn.innerHTML=old;btn.classList.remove('is-error');btn.disabled=false;btn.dataset.busy='0'},1300);throw e}}
async function loadMe(){const d=await req('/api/users/me');me=id(d.user)}
async function loadLobby(){try{let p='/api/game-rooms/';if(filter)p+='?gameType='+encodeURIComponent(filter);const d=await req(p),g=$('#roomsGrid');g.innerHTML=d.rooms.length?d.rooms.map(r=>`<article class="room-card"><div class="room-top"><span class="game-symbol">${esc(r.gameIcon)}</span><b>#${esc(r.roomCode)}</b></div><h3>${esc(r.name)}</h3><div class="room-meta"><span>${esc(r.gameName)}</span><span>${r.players.length}/${r.maxPlayers} لاعبين</span><span>${r.visibility==='public'?'عامة':r.visibility==='friends'?'أصدقاء':'خاصة'}</span></div><div class="room-actions"><a class="icon-button primary" href="game-room.html?room=${encodeURIComponent(r.id)}">دخول الطاولة</a></div></article>`).join(''):'<div class="room-empty">لا توجد غرف بهذه اللعبة. افتح أول طاولة.</div>'}catch(e){msg(e.message,true)}}
function render(r){room=r;const own=id(r.owner)===me,playing=r.players.some(p=>id(p)===me);$('[data-room-name]').textContent=r.name;$('[data-room-code]').textContent=r.roomCode;document.querySelectorAll('[data-game-name]').forEach(x=>x.textContent=r.gameName);$('[data-game-icon]').textContent=r.gameIcon;$('[data-visibility]').textContent=r.visibility==='public'?'عامة':r.visibility==='friends'?'للأصدقاء':'خاصة';$('[data-player-count]').textContent=r.players.length;$('[data-player-max]').textContent=r.maxPlayers;$('[data-game-status]').textContent=r.gameState?.status||'waiting';$('[data-turn]').textContent=r.gameState?.turn?name(r.gameState.turn):'—';const ts=r.gameState?.teamScores||{};$('[data-score-a]').textContent=ts.A||0;$('[data-score-b]').textContent=ts.B||0;$('[data-board-title]').textContent=r.gameName+(r.teamMode==='2v2'?' · 2 ضد 2':'');const reservations=r.reservations||[],box=$('[data-players]');box.innerHTML='';for(let i=0;i<r.maxPlayers;i++){const p=r.players[i],rv=reservations.find(q=>Number(q.seatIndex)===i),el=document.createElement('div');el.className='player '+(!p?'is-empty ':'')+(p&&id(p)===me?'is-me ':'')+(p&&r.gameState?.turn&&id(p)===id(r.gameState.turn)?'is-turn ':'')+(rv?'is-reserved':'');el.innerHTML=`<span class="seat-number">${i+1}</span><strong>${p?esc(name(p)):rv?'محجوز · '+esc(name(rv.user)):'مقعد متاح'}</strong><small>${p?(r.teamMode==='2v2'?(i%2?'الفريق B':'الفريق A'):'جاهز'):'اضغط للانضمام'}</small>`;if(!p)el.onclick=()=>join(el);box.appendChild(el)}$('[data-join-room]').hidden=playing||r.players.length>=r.maxPlayers;$('[data-leave-room]').hidden=!playing||own;$('[data-start-room]').hidden=!own;$('[data-close-room]').hidden=!own;$('[data-owner-settings]').hidden=!own;document.querySelectorAll('[data-score-team]').forEach(x=>x.hidden=!own||r.gameType==='domino');$('[data-spectator-count]').textContent=(r.spectators||[]).length;if(r.gameType==='domino'&&playing)loadDomino();else clearDomino()}
async function loadRoom(){try{const d=await req('/api/game-rooms/'+encodeURIComponent(roomId));render(d.room)}catch(e){msg(e.message,true)}}
async function join(btn){try{const b=btn?.tagName==='BUTTON'?btn:$('[data-join-room]');const d=await action(b,'جارٍ الانضمام…',()=>req('/api/game-rooms/'+roomId+'/join',apiBody('POST',{})),'تم الانضمام');render(d.room);msg('أنت الآن داخل الطاولة')}catch(e){}}
function clearDomino(){document.querySelector('.domino-live')?.remove();}
function tileHtml(t,selected=false){return `<button class="domino-tile ${selected?'selected':''}" data-domino-tile="${esc(t.id)}" type="button"><span>${t.a}</span><i></i><span>${t.b}</span></button>`}
function playerLabel(pid){const p=room?.players?.find(x=>id(x)===String(pid));return p?name(p):'لاعب'}
function ensureDomino(){let d=document.querySelector('.domino-live');if(!d){d=document.createElement('section');d.className='domino-live';$('[data-game-table]').appendChild(d)}return d}
function renderDomino(s){const d=ensureDomino(),mineTurn=String(s.turn||'')===me,chain=s.chain||[],hand=s.myHand||[];if(selectedTile&&!hand.some(t=>t.id===selectedTile))selectedTile='';const counts=Object.entries(s.handCounts||{}).map(([pid,n])=>`<span>${esc(playerLabel(pid))}: <b>${n}</b></span>`).join('');d.innerHTML=`<div class="domino-status"><div><strong>🁫 الدومنة الحقيقية</strong><small>${s.status==='finished'?(s.winner===me?'🏆 فزت بالمباراة':'انتهت المباراة · الفائز '+esc(playerLabel(s.winner))):(mineTurn?'🟢 دورك الآن':'بانتظار '+esc(playerLabel(s.turn)))}</small></div><div class="domino-counts">${counts}<span>المخزن: <b>${s.boneyardCount||0}</b></span></div></div><div class="domino-chain">${chain.length?chain.map(t=>tileHtml(t)).join(''):'<div class="domino-empty-board">ابدأ بوضع أول حجر</div>'}</div><div class="domino-hand-title"><b>أحجارك (${hand.length})</b><small>${selectedTile?'اختر يمين أو يسار':'اضغط على الحجر لاختياره'}</small></div><div class="domino-hand">${hand.map(t=>tileHtml(t,t.id===selectedTile)).join('')}</div><div class="domino-controls"><button type="button" data-domino-left ${!mineTurn||!selectedTile||s.status==='finished'?'disabled':''}>⬅ ضع يسار</button><button type="button" data-domino-right ${!mineTurn||!selectedTile||s.status==='finished'?'disabled':''}>ضع يمين ➡</button><button type="button" data-domino-pass ${!mineTurn||s.status==='finished'?'disabled':''}>⏭ سحب / تمرير</button></div>`;const center=$('.table-center');if(center)center.classList.add('domino-center-hidden')}
async function loadDomino(){try{const d=await req('/api/game-actions/'+roomId+'/domino/state');renderDomino(d.domino)}catch(e){if(/لم تبدأ/.test(e.message||'')){clearDomino();return;}msg(e.message,true)}}
async function dominoPlay(side,btn){if(!selectedTile)return msg('اختر حجراً أولاً',true);try{const d=await action(btn,'جارٍ اللعب…',()=>req('/api/game-actions/'+roomId+'/domino/play',apiBody('POST',{tileId:selectedTile,side})),'تمت الحركة');selectedTile='';renderDomino(d.domino)}catch(e){}}
async function dominoPass(btn){try{const d=await action(btn,'جارٍ الفحص…',()=>req('/api/game-actions/'+roomId+'/domino/pass',apiBody('POST',{})), 'تم');renderDomino(d.domino);if(d.message)msg(d.message)}catch(e){}}
async function openPeople(mode){peopleMode=mode;$('#peopleModal').hidden=false;$('[data-people-title]').textContent=mode==='friends'?'دعوة صديق للعب':'طلب لعب من شخص';$('#peopleSearch').value='';await loadPeople('')}
async function loadPeople(q){try{let users;if(peopleMode==='friends'){const d=await req('/api/friends');users=d.friends||d.users||[]}else{const d=await req('/api/game-actions/'+roomId+'/players?q='+encodeURIComponent(q));users=d.users||[]}$('#peopleList').innerHTML=users.length?users.map(u=>`<div class="person-row" data-person="${id(u)}"><span class="person-avatar"></span><div class="person-info"><b>${esc(name(u))}</b><small>@${esc(u.username||'')}</small></div><button class="icon-button primary" data-pick-player="${id(u)}">${peopleMode==='friends'?'دعوة':'طلب لعب'}</button></div>`).join(''):'<p class="room-empty">لا يوجد أشخاص مطابقون</p>'}catch(e){msg(e.message,true)}}
async function requestPlayer(uid,btn){try{const d=await action(btn,'جارٍ الإرسال…',()=>req('/api/game-actions/'+roomId+'/request-player',apiBody('POST',{userId:uid})),'تم الإرسال');btn.disabled=true;btn.dataset.busy='1';btn.innerHTML='✓ بانتظار الرد';btn.closest('.person-row')?.classList.add('invite-sent');msg(d.message||'تم إرسال طلب اللعب')}catch(e){}}
$('#openCreate')?.addEventListener('click',()=>{$('#createModal').hidden=false;showToast('اختر اللعبة ونوع الطاولة')});$('#closeCreate')?.addEventListener('click',()=>$('#createModal').hidden=true);$('#createGame')?.addEventListener('change',function(){const m=$('#maxPlayers');m.innerHTML=this.value==='cards'?'<option>2</option><option>3</option><option selected>4</option><option>5</option><option>6</option>':this.value==='domino'?'<option>2</option><option>4</option>':'<option>2</option>';$('#teamMode').disabled=!['domino','cards'].includes(this.value)});
$('#createRoomForm')?.addEventListener('submit',async e=>{e.preventDefault();const btn=e.submitter;try{const b=Object.fromEntries(new FormData(e.target));const d=await action(btn,'جارٍ فتح الطاولة…',()=>req('/api/game-rooms',apiBody('POST',b)),'تم الإنشاء');if(b.teamMode==='2v2')await req('/api/game-actions/'+d.room.id+'/match-settings',apiBody('PATCH',{teamMode:'2v2'}));location.href='game-room.html?room='+d.room.id}catch(x){$('#createFeedback').textContent=x.message}});
$('#gamePicker')?.addEventListener('click',e=>{const b=e.target.closest('[data-game]');if(!b)return;filter=b.dataset.game;document.querySelectorAll('.game-chip').forEach(x=>x.classList.toggle('active',x===b));loadLobby()});$('#refreshRooms')?.addEventListener('click',e=>action(e.currentTarget,'تحديث…',loadLobby,'تم التحديث').catch(()=>{}));
$('[data-join-room]')?.addEventListener('click',e=>join(e.currentTarget));$('[data-leave-room]')?.addEventListener('click',e=>action(e.currentTarget,'جارٍ المغادرة…',()=>req('/api/game-rooms/'+roomId+'/join',{method:'DELETE'}),'تمت المغادرة').then(()=>location.href='game-room.html').catch(()=>{}));
$('[data-start-room]')?.addEventListener('click',async e=>{try{let d;if(room?.gameType==='domino'){d=await action(e.currentTarget,'توزيع الأحجار…',()=>req('/api/game-actions/'+roomId+'/domino/start',apiBody('POST',{})),'بدأت الدومنة');renderDomino(d.domino);msg('تم توزيع الأحجار. اللعب بدأ الآن.')}else{d=await action(e.currentTarget,'جارٍ البدء…',()=>req('/api/game-rooms/'+roomId+'/start',apiBody('POST',{})),'بدأت اللعبة');render(d.room)}}catch(e){}});
$('[data-close-room]')?.addEventListener('click',async e=>{if(confirm('إغلاق الغرفة؟'))action(e.currentTarget,'جارٍ الإغلاق…',()=>req('/api/game-rooms/'+roomId,{method:'DELETE'}),'أغلقت').then(()=>location.href='game-room.html').catch(()=>{})});$('[data-invite-friend]')?.addEventListener('click',()=>openPeople('friends'));$('[data-find-player]')?.addEventListener('click',()=>openPeople('all'));$('[data-people-close]')?.addEventListener('click',()=>$('#peopleModal').hidden=true);$('#peopleSearch')?.addEventListener('input',e=>loadPeople(e.target.value));$('#peopleList')?.addEventListener('click',e=>{const b=e.target.closest('[data-pick-player]');if(b)requestPlayer(b.dataset.pickPlayer,b)});
document.querySelector('[data-game-table]')?.addEventListener('click',e=>{const t=e.target.closest('[data-domino-tile]');if(t&&t.closest('.domino-hand')){selectedTile=t.dataset.dominoTile;loadDomino();return;}const l=e.target.closest('[data-domino-left]');if(l)return dominoPlay('left',l);const r=e.target.closest('[data-domino-right]');if(r)return dominoPlay('right',r);const p=e.target.closest('[data-domino-pass]');if(p)return dominoPass(p)});
document.querySelectorAll('[data-score-team]').forEach(b=>b.addEventListener('click',e=>action(e.currentTarget,'حساب…',()=>req('/api/game-actions/'+roomId+'/score',apiBody('POST',{team:b.dataset.scoreTeam,delta:1})),'أضيفت').then(d=>{if(d){$('[data-score-a]').textContent=d.teamScores.A||0;$('[data-score-b]').textContent=d.teamScores.B||0}}).catch(()=>{})));$('[data-save-game]')?.addEventListener('click',e=>action(e.currentTarget,'جارٍ الحفظ…',()=>req('/api/game-actions/'+roomId+'/save',apiBody('POST',{})),'تم الحفظ').then(d=>msg(d.message)).catch(()=>{}));$('[data-fit-table]')?.addEventListener('click',()=>{const t=$('[data-game-table]');if(!document.fullscreenElement)t.requestFullscreen?.();else document.exitFullscreen?.()});$('[data-spectators-toggle]')?.addEventListener('click',()=>{const p=$('[data-spectator-panel]');p.hidden=!p.hidden});
(async()=>{await loadMe();if(roomId){$('#lobbyView').hidden=true;$('#roomView').hidden=false;await loadRoom();const socket=window.io&&SocialAPI.token()?window.io(SocialAPI.baseUrl,{auth:{token:SocialAPI.token()}}):null;if(socket){socket.on('game:room-updated',d=>{if(d.roomId===roomId||d.roomCode===roomId)loadRoom()});socket.on('game:domino-updated',d=>{if(d.roomId===roomId||d.roomCode===roomId){loadRoom();loadDomino();showToast('🁫 حركة جديدة على الطاولة')}});socket.on('game:player-request',d=>{showToast('🎮 وصلك طلب لعب من '+d.from.name);if(confirm(`${d.from.name} يدعوك للعب ${d.gameType}. دخول الغرفة؟`))location.href='game-room.html?room='+d.roomId})}}else loadLobby()})().catch(e=>msg(e.message,true));
})();