(function(){'use strict';
if(!/\/(?:taktak\.html)?$/i.test(location.pathname))return;
function esc(v){return String(v||'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[s]));}
function playlists(){try{return JSON.parse(localStorage.getItem('taktak_tv_playlists')||'{}')}catch(_){return {}}}
function channels(){const out=[];for(const [playlist,groups] of Object.entries(playlists()))for(const [group,rows] of Object.entries(groups||{}))for(const [name,url] of Object.entries(rows||{}))out.push({playlist,group,name,url});return out;}
function current(){try{return JSON.parse(localStorage.getItem('taktak_tv_current_channel')||'null')}catch(_){return null}}
function save(c){localStorage.setItem('taktak_tv_current_channel',JSON.stringify({...c,updatedAt:Date.now()}));}
function place(sec){const quick=document.querySelector('.home-quick-panel');if(quick){quick.insertAdjacentElement('afterend',sec);return true;}const people=document.querySelector('.people-strip');if(people){people.insertAdjacentElement('afterend',sec);return true;}const feed=document.querySelector('.feed');if(feed){feed.insertAdjacentElement('beforebegin',sec);return true;}document.body.appendChild(sec);return true;}
function inject(){if(document.querySelector('section[data-home-mini-tv-card]'))return;const sec=document.createElement('section');sec.className='home-mini-tv compact-panel';sec.dataset.homeMiniTvCard='1';sec.innerHTML='<div class="home-mini-tv-head"><div><strong>📺 شنو منو TV</strong><small data-mini-tv-name>لم يتم اختيار قناة</small></div><a href="tv.html">فتح TV</a></div><div class="home-mini-tv-screen"><video playsinline webkit-playsinline preload="metadata" data-mini-tv-video></video><div class="home-mini-tv-empty" data-mini-tv-empty><b>📺</b><span>اختر قناة لبدء المشاهدة</span></div><div class="home-mini-tv-error" data-mini-tv-error hidden></div></div><div class="home-mini-tv-controls"><div class="tv-control-main"><button type="button" data-mini-tv-prev title="القناة السابقة">⏮</button><button type="button" class="tv-play" data-mini-tv-play aria-label="تشغيل أو إيقاف">▶</button><button type="button" data-mini-tv-next title="القناة التالية">⏭</button><button type="button" data-mini-tv-mute aria-label="كتم الصوت">🔊</button><input type="range" min="0" max="100" value="70" data-mini-tv-volume aria-label="مستوى الصوت"></div><div class="tv-control-channel"><span class="tv-select-wrap"><select data-mini-tv-channel aria-label="اختيار القناة"><option value="">اختر قناة</option></select><i aria-hidden="true">▼</i></span><button type="button" data-mini-tv-refresh title="تحديث القنوات">↻</button></div></div><div class="home-mini-tv-status" data-mini-tv-status>اختر قناة ثم اضغط تشغيل.</div>';place(sec);wire(sec);}
function loadHls(done){if(window.Hls)return done(true);let old=document.querySelector('script[data-home-hls]');if(old){old.addEventListener('load',()=>done(!!window.Hls),{once:true});old.addEventListener('error',()=>done(false),{once:true});return;}const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/hls.js@1/dist/hls.min.js';s.async=true;s.dataset.homeHls='1';s.onload=()=>done(!!window.Hls);s.onerror=()=>done(false);document.head.appendChild(s);}
function wire(root){const video=root.querySelector('[data-mini-tv-video]'),nameBox=root.querySelector('[data-mini-tv-name]'),empty=root.querySelector('[data-mini-tv-empty]'),errorBox=root.querySelector('[data-mini-tv-error]'),select=root.querySelector('[data-mini-tv-channel]'),play=root.querySelector('[data-mini-tv-play]'),prev=root.querySelector('[data-mini-tv-prev]'),next=root.querySelector('[data-mini-tv-next]'),mute=root.querySelector('[data-mini-tv-mute]'),volume=root.querySelector('[data-mini-tv-volume]'),refresh=root.querySelector('[data-mini-tv-refresh]'),status=root.querySelector('[data-mini-tv-status]');let hls=null,list=[],selected=null,loading=false;
function setStatus(t){status.textContent=t||''}
function fail(t){errorBox.textContent=t;errorBox.hidden=false;setStatus(t);play.textContent='▶'}
function clearError(){errorBox.hidden=true;errorBox.textContent=''}
function fill(){list=channels();const cur=current();select.innerHTML='<option value="">اختر قناة</option>'+list.map((c,i)=>'<option value="'+i+'">'+esc(c.name)+' — '+esc(c.group)+'</option>').join('');if(cur){const idx=list.findIndex(c=>c.url===cur.url&&c.name===cur.name);if(idx>=0){select.value=String(idx);selected=list[idx];}else selected=cur;}if(!list.length)setStatus('لا توجد قنوات محفوظة على هذا الجهاز. افتح TV وأضف أو استورد القنوات.');}
function teardown(){if(hls){hls.destroy();hls=null;}video.pause();video.removeAttribute('src');video.load();}
function attach(c,autoplay){if(!c||!c.url)return;selected=c;save(c);nameBox.textContent=c.name||'قناة';empty.hidden=true;clearError();teardown();loading=true;setStatus('جارٍ تجهيز القناة…');const idx=list.findIndex(x=>x.url===c.url&&x.name===c.name);if(idx>=0)select.value=String(idx);const startPlay=()=>{loading=false;setStatus('القناة جاهزة');if(autoplay)video.play().catch(()=>{setStatus('اضغط ▶ لبدء المشاهدة.');});};if(video.canPlayType('application/vnd.apple.mpegurl')){video.src=c.url;video.addEventListener('loadedmetadata',startPlay,{once:true});video.load();return;}if(/\.m3u8(?:\?|$)/i.test(c.url)){loadHls(ok=>{if(!ok||!window.Hls||!Hls.isSupported()){fail('تعذر تشغيل HLS في هذا المتصفح. افتح القناة من صفحة TV.');loading=false;return;}hls=new Hls({enableWorker:true,lowLatencyMode:true});hls.on(Hls.Events.MEDIA_ATTACHED,()=>hls.loadSource(c.url));hls.on(Hls.Events.MANIFEST_PARSED,startPlay);hls.on(Hls.Events.ERROR,(_,data)=>{if(data&&data.fatal){loading=false;fail('تعذر تحميل القناة. جرّب تحديث القناة أو افتح TV.');}});hls.attachMedia(video);});return;}video.src=c.url;video.addEventListener('loadedmetadata',startPlay,{once:true});video.addEventListener('error',()=>{loading=false;fail('تعذر تشغيل رابط هذه القناة.')},{once:true});video.load();}
function move(step){if(!list.length){setStatus('لا توجد قنوات محفوظة.');return;}let idx=selected?list.findIndex(c=>c.url===selected.url&&c.name===selected.name):-1;if(idx<0)idx=0;idx=(idx+step+list.length)%list.length;select.value=String(idx);attach(list[idx],true);}
fill();const cur=current();if(cur)attach(cur,false);
select.addEventListener('change',()=>{const c=list[Number(select.value)];if(c)attach(c,true)});
prev.addEventListener('click',()=>move(-1));next.addEventListener('click',()=>move(1));
play.addEventListener('click',()=>{if(!selected){const c=list[Number(select.value)];if(c){attach(c,true);return;}setStatus('اختر قناة أولاً.');return;}if(loading){setStatus('انتظر لحظة، جارٍ تجهيز القناة…');return;}if(!video.src&&!hls){attach(selected,true);return;}if(video.paused){video.play().catch(()=>attach(selected,true));}else video.pause();});
video.addEventListener('play',()=>{play.textContent='⏸';setStatus('يتم التشغيل الآن')});video.addEventListener('pause',()=>{play.textContent='▶'});video.addEventListener('waiting',()=>setStatus('جارٍ التحميل…'));video.addEventListener('playing',()=>setStatus('يتم التشغيل الآن'));
mute.addEventListener('click',()=>{video.muted=!video.muted;mute.textContent=video.muted?'🔇':'🔊'});
volume.addEventListener('input',()=>{video.volume=Number(volume.value)/100;if(video.volume>0)video.muted=false;mute.textContent=video.muted?'🔇':'🔊'});video.volume=.7;
refresh.addEventListener('click',()=>{fill();const cur=current();if(cur){selected=cur;attach(cur,false);}setStatus(list.length?'تم تحديث القنوات.':'لا توجد قنوات محفوظة على هذا الجهاز.');});
window.addEventListener('storage',e=>{if(e.key==='taktak_tv_current_channel'||e.key==='taktak_tv_playlists'){fill();const c=current();if(c)attach(c,false);}});window.addEventListener('taktak-tv-channel-change',e=>{const c=e.detail;if(c){fill();attach(c,false);}});video.removeAttribute('controls');}
function boot(){inject();setTimeout(inject,700);setTimeout(inject,1800)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();