(function(){'use strict';
var confirmBox=document.querySelector('[data-confirm]'),start=document.querySelector('[data-start]'),status=document.querySelector('[data-status]'),preview=document.querySelector('[data-preview]'),video=document.querySelector('[data-video]'),selected=document.querySelector('[data-selected-people]'),switchCamera=document.querySelector('[data-switch-camera]'),stream=null,facingMode='user';
function visibility(){var x=document.querySelector('input[name="visibility"]:checked');return x?x.value:'public'}
function update(){start.disabled=!confirmBox.checked;selected.hidden=visibility()!=='selected'}
function constraints(){return {video:{facingMode:{ideal:facingMode}},audio:true}}
async function openCamera(){return navigator.mediaDevices.getUserMedia(constraints())}
async function replaceCamera(){if(!stream)return;var oldVideo=stream.getVideoTracks()[0],audioTracks=stream.getAudioTracks();try{if(oldVideo)oldVideo.stop();var cameraOnly=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:facingMode}},audio:false});var newVideo=cameraOnly.getVideoTracks()[0];stream=new MediaStream([newVideo].concat(audioTracks));video.srcObject=stream;switchCamera.textContent=facingMode==='user'?'🔄 الكاميرا الخلفية':'🔄 الكاميرا الأمامية';status.textContent=facingMode==='user'?'تم تشغيل الكاميرا الأمامية.':'تم تشغيل الكاميرا الخلفية.';window.dispatchEvent(new CustomEvent('shno-live-camera-changed',{detail:{track:newVideo,stream:stream,facingMode:facingMode}}))}catch(e){facingMode=facingMode==='user'?'environment':'user';status.textContent='تعذر التبديل إلى الكاميرا المطلوبة.'}}
document.querySelectorAll('input[name="visibility"]').forEach(function(x){x.addEventListener('change',update)});confirmBox.addEventListener('change',update);update();
start.addEventListener('click',async function(){if(!confirmBox.checked)return;start.disabled=true;status.textContent='جارٍ طلب صلاحية الكاميرا والمايك…';try{stream=await openCamera();video.srcObject=stream;preview.style.display='block';switchCamera.textContent='🔄 الكاميرا الخلفية';var setup={title:(document.getElementById('liveTitle').value||'').trim(),visibility:visibility(),startedAt:new Date().toISOString(),facingMode:facingMode};sessionStorage.setItem('shno_live_setup',JSON.stringify(setup));status.textContent=visibility()==='public'?'الكاميرا والمايك يعملان. البث العام جاهز للربط بالخادم.':'الكاميرا والمايك يعملان. إعداد الخصوصية محفوظ وجاهز للربط بالخادم.';start.hidden=true}catch(e){status.textContent='تعذر فتح الكاميرا أو المايك. تحقق من الصلاحيات وحاول مرة أخرى.';start.disabled=false;}});
switchCamera.addEventListener('click',async function(){if(!stream)return;facingMode=facingMode==='user'?'environment':'user';this.disabled=true;await replaceCamera();this.disabled=false});
document.querySelector('[data-toggle-mic]').addEventListener('click',function(){if(!stream)return;var t=stream.getAudioTracks()[0];if(!t)return;t.enabled=!t.enabled;this.textContent=t.enabled?'🎙 كتم المايك':'🎙 تشغيل المايك'});
document.querySelector('[data-toggle-camera]').addEventListener('click',function(){if(!stream)return;var t=stream.getVideoTracks()[0];if(!t)return;t.enabled=!t.enabled;this.textContent=t.enabled?'📷 إيقاف الكاميرا':'📷 تشغيل الكاميرا'});
document.querySelector('[data-end]').addEventListener('click',function(){if(stream)stream.getTracks().forEach(function(t){t.stop()});stream=null;video.srcObject=null;preview.style.display='none';start.hidden=false;confirmBox.checked=false;facingMode='user';update();status.textContent='تم إيقاف الكاميرا والمايك.'});
window.addEventListener('pagehide',function(){if(stream)stream.getTracks().forEach(function(t){t.stop()})});
})();