(function(){'use strict';
var confirmBox=document.querySelector('[data-confirm]'),start=document.querySelector('[data-start]'),status=document.querySelector('[data-status]'),preview=document.querySelector('[data-preview]'),video=document.querySelector('[data-video]'),selected=document.querySelector('[data-selected-people]'),stream=null;
function visibility(){var x=document.querySelector('input[name="visibility"]:checked');return x?x.value:'public'}
function update(){start.disabled=!confirmBox.checked;selected.hidden=visibility()!=='selected'}
document.querySelectorAll('input[name="visibility"]').forEach(function(x){x.addEventListener('change',update)});confirmBox.addEventListener('change',update);update();
start.addEventListener('click',async function(){if(!confirmBox.checked)return;start.disabled=true;status.textContent='جارٍ طلب صلاحية الكاميرا والمايك…';try{stream=await navigator.mediaDevices.getUserMedia({video:true,audio:true});video.srcObject=stream;preview.style.display='block';var setup={title:(document.getElementById('liveTitle').value||'').trim(),visibility:visibility(),startedAt:new Date().toISOString()};sessionStorage.setItem('shno_live_setup',JSON.stringify(setup));status.textContent=visibility()==='public'?'الكاميرا والمايك يعملان. البث العام جاهز للربط بالخادم.':'الكاميرا والمايك يعملان. إعداد الخصوصية محفوظ وجاهز للربط بالخادم.';start.hidden=true}catch(e){status.textContent='تعذر فتح الكاميرا أو المايك. تحقق من الصلاحيات وحاول مرة أخرى.';start.disabled=false;}});
document.querySelector('[data-toggle-mic]').addEventListener('click',function(){if(!stream)return;var t=stream.getAudioTracks()[0];if(!t)return;t.enabled=!t.enabled;this.textContent=t.enabled?'🎙 كتم المايك':'🎙 تشغيل المايك'});
document.querySelector('[data-toggle-camera]').addEventListener('click',function(){if(!stream)return;var t=stream.getVideoTracks()[0];if(!t)return;t.enabled=!t.enabled;this.textContent=t.enabled?'📷 إيقاف الكاميرا':'📷 تشغيل الكاميرا'});
document.querySelector('[data-end]').addEventListener('click',function(){if(stream)stream.getTracks().forEach(function(t){t.stop()});stream=null;video.srcObject=null;preview.style.display='none';start.hidden=false;confirmBox.checked=false;update();status.textContent='تم إيقاف الكاميرا والمايك.'});
window.addEventListener('pagehide',function(){if(stream)stream.getTracks().forEach(function(t){t.stop()})});
})();