(()=>{'use strict';
if(window.__shnoMediaCacheLoaded)return;window.__shnoMediaCacheLoaded=true;
const DB='shno_mano_offline_media',STORE='media',VERSION=1,CACHE='shno-mano-media-v1',inflight=new Set();
function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORE)){const s=db.createObjectStore(STORE,{keyPath:'url'});s.createIndex('lastAccessed','lastAccessed');s.createIndex('type','type')}};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function putMeta(url,response){try{const db=await openDb(),type=(response.headers.get('content-type')||'').split(';')[0],size=Number(response.headers.get('content-length')||0),now=Date.now();await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put({url,type,size,cachedAt:now,lastAccessed:now,status:'cached'});tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close()}catch(_){}}
async function touch(url){try{const db=await openDb();await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite'),s=tx.objectStore(STORE),r=s.get(url);r.onsuccess=()=>{const v=r.result;if(v){v.lastAccessed=Date.now();s.put(v)}};tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close()}catch(_){}}
async function cacheMedia(src){if(!src)return;let u;try{u=new URL(src,location.href)}catch(_){return}if(!/^https?:$/.test(u.protocol)||u.pathname.includes('/api/')||u.pathname.includes('/messages/'))return;const url=u.href;if(inflight.has(url))return;inflight.add(url);try{const cache=await caches.open(CACHE);if(await cache.match(url)){touch(url);return}const same=u.origin===location.origin,r=await fetch(url,same?{credentials:'same-origin'}:{mode:'cors',credentials:'omit'});if(!r.ok)return;const ct=(r.headers.get('content-type')||'').toLowerCase();if(!/^(video|audio|image)\//.test(ct))return;await cache.put(url,r.clone());await putMeta(url,r)}catch(_){}finally{inflight.delete(url)}}
function watch(){document.addEventListener('play',e=>{const el=e.target;if(el&&/^(VIDEO|AUDIO)$/.test(el.tagName))cacheMedia(el.currentSrc||el.src)},true);document.addEventListener('load',e=>{const el=e.target;if(el&&el.tagName==='IMG')cacheMedia(el.currentSrc||el.src)},true)}
async function init(){if(!('indexedDB'in window)||!('caches'in window))return;openDb().then(db=>db.close()).catch(()=>{});navigator.storage?.persist?.().catch(()=>{});if('serviceWorker'in navigator){try{await navigator.serviceWorker.register('/media-sw.js',{scope:'/'});}catch(_){}}watch()}
window.ShnoMediaCache={cacheMedia,openDb};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();