(function(){
"use strict";
var css=document.createElement("link");css.rel="stylesheet";css.href="profile-media-editor.css?v=20260911-1";document.head.appendChild(css);
var id=new URLSearchParams(location.search).get("id")||"me",message=document.querySelector("[data-profile-message]"),currentUser=null,followState=null,previewUrls=[];
function setMessage(t,type){if(message){message.textContent=t;message.className="form-message"+(type?" is-"+type:"");}}
function text(s,v){var e=document.querySelector(s);if(e&&v!==undefined)e.textContent=v;}
function action(label,name,type){var b=document.createElement("button");b.className="icon-button "+(type||"");b.type="button";b.textContent=label;b.dataset.profileAction=name;return b;}
function abs(u){return !u?"":/^https?:/i.test(u)?u:"https://shino-mino-tak-tak.duckdns.org"+u;}
function position(u){return{x:Number.isFinite(Number(u&&u.coverPositionX))?Number(u.coverPositionX):50,y:Number.isFinite(Number(u&&u.coverPositionY))?Number(u.coverPositionY):50};}
async function loadFollow(){if(id==="me")return null;try{return await SocialAPI.request("/api/social/follow-state/"+encodeURIComponent(id));}catch(_){return null;}}
function render(data){
 var u=data.user||data.profile||data.data||{};currentUser=u;
 text("[data-full-name]",u.fullName||u.name||"مستخدم");text("[data-username]",u.username?"@"+u.username:"@غير متاح");text("[data-bio]",u.bio||"لا توجد نبذة منشورة.");text("[data-location]",u.locationVisible===false?"الموقع مخفي حسب إعدادات الخصوصية.":[u.governorate,u.city].filter(Boolean).join(" · ")||"المحافظة والمدينة غير معلنة.");text("[data-friends-count]",u.friendsCount===undefined?"—":u.friendsCount);text("[data-posts-count]",u.postsCount===undefined?"—":u.postsCount);text("[data-joined]",u.createdAt?new Date(u.createdAt).getFullYear():"—");text("[data-presence]",u.online?"متصل الآن":"غير متصل");text("[data-last-seen]",u.lastSeenVisible===false?"آخر ظهور مخفي":u.lastSeen?"آخر ظهور "+new Date(u.lastSeen).toLocaleString("ar-IQ"):"آخر ظهور غير متاح");
 var avatar=document.querySelector("[data-avatar]");if(avatar)avatar.innerHTML=u.avatarUrl?'<img src="'+abs(u.avatarUrl)+'" alt="الصورة الشخصية">':(u.fullName||"؟").slice(0,1);
 var cover=document.querySelector(".profile-cover"),p=position(u);if(cover)cover.innerHTML=u.coverUrl?'<img src="'+abs(u.coverUrl)+'" alt="صورة الغلاف" style="object-position:'+p.x+'% '+p.y+'%">':"";
 var actions=document.querySelector("[data-profile-actions]");if(!actions)return;actions.innerHTML="";
 if(u.isSelf||id==="me"){actions.append(action("تعديل الملف والصور","edit","primary"));actions.append(action("الخصوصية","privacy"));var ps=document.querySelector("[data-privacy-section]");if(ps)ps.hidden=false;return;}
 if(followState){actions.append(action(followState.following?"✓ متابَع · إلغاء المتابعة":"＋ متابعة",followState.following?"unfollow":"follow",followState.following?"":"primary"));var stat=document.createElement("span");stat.className="meta-chip";stat.textContent="المتابعون: "+Number(followState.followersCount||0)+" · يتابع: "+Number(followState.followingCount||0);actions.append(stat);}
 actions.append(action(u.friendStatus==="pending"?"إلغاء الطلب":"إضافة صديق",u.friendStatus==="pending"?"cancel-friend":"add-friend","primary"));actions.append(action("مراسلة","message"));actions.append(action("صوت","audio"));actions.append(action("فيديو","video"));actions.append(action("حظر","block","danger"));actions.append(action("إبلاغ","report"));
}
async function load(){try{var pair=await Promise.all([SocialAPI.request("/api/users/"+encodeURIComponent(id)+"/profile"),loadFollow()]);followState=pair[1];render(pair[0]);}catch(e){setMessage(e.message,"error");text("[data-full-name]","تعذر تحميل الملف");}}
function releaseUrls(){previewUrls.forEach(function(u){URL.revokeObjectURL(u);});previewUrls=[];}
function setPickerImage(kind,url){var img=document.querySelector('[data-media-preview="'+kind+'"] img');if(!img)return;if(url)img.src=abs(url);else img.removeAttribute("src");if(kind==="cover"){var form=document.querySelector("[data-edit-form]"),p=position(currentUser);form.elements.coverPositionX.value=p.x;form.elements.coverPositionY.value=p.y;img.style.objectPosition=p.x+"% "+p.y+"%";}}
function makePicker(input,kind){
 if(!input||input.dataset.enhanced)return;input.dataset.enhanced="true";input.accept="image/jpeg,image/png,image/webp,image/gif";
 var picker=document.createElement("div");picker.className="profile-media-picker";var preview=document.createElement("div");preview.className="profile-media-preview is-"+kind;preview.dataset.mediaPreview=kind;var img=document.createElement("img");img.alt=kind==="cover"?"معاينة الغلاف":"معاينة الصورة الشخصية";preview.append(img);
 if(kind==="cover"){var hint=document.createElement("span");hint.className="profile-cover-position-hint";hint.textContent="حرّك الصورة بإصبعك أو الماوس لتحديد موضعها";preview.append(hint);}
 var controls=document.createElement("div");controls.className="profile-media-controls";var choose=document.createElement("button");choose.type="button";choose.className="profile-media-choose";choose.textContent=kind==="cover"?"اختيار صورة الغلاف":"اختيار صورة شخصية";var reset=document.createElement("button");reset.type="button";reset.className="profile-media-reset";reset.textContent="إلغاء الاختيار";var name=document.createElement("span");name.className="profile-media-name";name.textContent="لم يتم اختيار صورة جديدة";controls.append(choose,reset,name);var note=document.createElement("small");note.className="profile-media-note";note.textContent="JPG أو PNG أو WEBP أو GIF — الحد الأقصى 10 MB";
 input.parentNode.insertBefore(picker,input);picker.append(preview,controls,note,input);choose.addEventListener("click",function(){input.click();});reset.addEventListener("click",function(){input.value="";name.textContent="تم إلغاء الصورة الجديدة";setPickerImage(kind,kind==="cover"?currentUser&&currentUser.coverUrl:currentUser&&currentUser.avatarUrl);});
 input.addEventListener("change",function(){var file=input.files&&input.files[0];if(!file)return;if(!/^image\/(jpeg|png|webp|gif)$/.test(file.type)||file.size>10*1024*1024){input.value="";name.textContent="الصورة غير صالحة";setMessage("اختر صورة JPG أو PNG أو WEBP أو GIF بحجم لا يتجاوز 10 MB.","error");return;}var url=URL.createObjectURL(file);previewUrls.push(url);img.src=url;name.textContent=file.name;setMessage("تم اختيار الصورة. اضغط حفظ التعديلات لرفعها.","");});
}
function enhanceEditor(){
 var form=document.querySelector("[data-edit-form]");if(!form||form.dataset.enhanced)return;form.dataset.enhanced="true";
 ["coverPositionX","coverPositionY"].forEach(function(name){var hidden=document.createElement("input");hidden.type="hidden";hidden.name=name;hidden.value="50";form.append(hidden);});makePicker(form.elements.avatar,"avatar");makePicker(form.elements.cover,"cover");
 var preview=form.querySelector('[data-media-preview="cover"]'),drag=null;
 preview.addEventListener("pointerdown",function(e){if(!preview.querySelector("img").getAttribute("src"))return;drag={x:e.clientX,y:e.clientY,px:Number(form.elements.coverPositionX.value),py:Number(form.elements.coverPositionY.value)};preview.setPointerCapture(e.pointerId);preview.classList.add("is-dragging");});
 preview.addEventListener("pointermove",function(e){if(!drag)return;var x=Math.max(0,Math.min(100,drag.px-(e.clientX-drag.x)/preview.clientWidth*100)),y=Math.max(0,Math.min(100,drag.py-(e.clientY-drag.y)/preview.clientHeight*100));form.elements.coverPositionX.value=x.toFixed(1);form.elements.coverPositionY.value=y.toFixed(1);preview.querySelector("img").style.objectPosition=x+"% "+y+"%";});
 function stop(){drag=null;preview.classList.remove("is-dragging");}preview.addEventListener("pointerup",stop);preview.addEventListener("pointercancel",stop);
}
function openEdit(){enhanceEditor();var modal=document.querySelector("[data-edit-modal]"),form=document.querySelector("[data-edit-form]");if(!modal||!form)return;releaseUrls();form.reset();modal.hidden=false;form.elements.fullName.value=currentUser&&currentUser.fullName||"";form.elements.bio.value=currentUser&&currentUser.bio||"";setPickerImage("avatar",currentUser&&currentUser.avatarUrl);setPickerImage("cover",currentUser&&currentUser.coverUrl);form.querySelectorAll(".profile-media-name").forEach(function(e){e.textContent="لم يتم اختيار صورة جديدة";});}
document.addEventListener("click",async function(e){var b=e.target.closest("[data-profile-action]");if(!b)return;var a=b.dataset.profileAction;if(a==="privacy"){document.querySelector("[data-privacy-section]")?.scrollIntoView({behavior:"smooth"});return;}if(a==="message"){location.href="messages.html?user="+encodeURIComponent(id);return;}if(a==="audio"||a==="video"){location.href="messages.html?call="+a+"&user="+encodeURIComponent(id);return;}if(a==="edit"){openEdit();return;}try{if(a==="follow"||a==="unfollow"){await SocialAPI.request("/api/social/follow/"+encodeURIComponent(id),{method:a==="unfollow"?"DELETE":"POST"});setMessage(a==="follow"?"تمت المتابعة.":"تم إلغاء المتابعة.","success");await load();return;}var path=a==="add-friend"?"/api/friends/request/"+id:a==="cancel-friend"?"/api/friends/"+id:a==="block"?"/api/users/"+id+"/block":"";if(!path){setMessage("الإبلاغ غير متاح حالياً.","");return;}await SocialAPI.request(path,{method:a==="cancel-friend"?"DELETE":"POST"});setMessage("تم تنفيذ الطلب.","success");await load();}catch(err){setMessage(err.message,"error");}});
var savePrivacy=document.querySelector("[data-save-privacy]");if(savePrivacy)savePrivacy.addEventListener("click",async function(){var s={};document.querySelectorAll("[data-privacy]").forEach(function(f){s[f.dataset.privacy]=f.value;});try{await SocialAPI.request("/api/users/me/privacy",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(s)});setMessage("تم حفظ إعدادات الخصوصية.","success");}catch(e){setMessage(e.message,"error");}});
document.querySelector("[data-close-edit]")?.addEventListener("click",function(){document.querySelector("[data-edit-modal]").hidden=true;releaseUrls();});
document.querySelector("[data-edit-form]")?.addEventListener("submit",async function(e){e.preventDefault();var form=e.target,msg=form.querySelector("[data-edit-message]"),btn=form.querySelector('[type="submit"]'),label=btn&&btn.textContent;if(btn){btn.disabled=true;btn.textContent="جارٍ رفع الصور والحفظ…";}try{var data=await SocialAPI.request("/api/users/me/profile",{method:"PATCH",body:new FormData(form)});msg.textContent=data.message||"تم حفظ الملف الشخصي.";msg.className="form-message is-success";await load();setTimeout(function(){document.querySelector("[data-edit-modal]").hidden=true;releaseUrls();},650);}catch(err){msg.textContent=err.message;msg.className="form-message is-error";}finally{if(btn){btn.disabled=false;btn.textContent=label;}}});
enhanceEditor();load();
}());
