(function(){
'use strict';
var id=new URLSearchParams(location.search).get('id')||'me',message=document.querySelector('[data-profile-message]'),currentUser=null,followState=null,editingSocialIndex=-1;
function text(s,v){var e=document.querySelector(s);if(e&&v!==undefined)e.textContent=v;}
function setMessage(t,type){if(message){message.textContent=t;message.className='form-message'+(type?' is-'+type:'');}}
function abs(u){return !u?'':/^https?:/i.test(u)?u:'https://shino-mino-tak-tak.duckdns.org'+u;}
function safeUrl(v){try{var u=new URL(String(v||''));return /^(https?:)$/.test(u.protocol)?u.href:'';}catch(_){return'';}}
function action(label,name,type){var b=document.createElement('button');b.className='icon-button '+(type||'');b.type='button';b.textContent=label;b.dataset.profileAction=name;return b;}
function addInfo(label,value){if(value===undefined||value===null||value==='')return;var root=document.querySelector('[data-profile-details]'),row=document.createElement('div');row.className='profile-info-item';row.innerHTML='<b></b><span></span>';row.querySelector('b').textContent=label;row.querySelector('span').textContent=value;root.appendChild(row);}
function genderLabel(v){return v==='male'?'ذكر':v==='female'?'أنثى':v==='other'?'غير محدد':v||'';}
function dateLabel(v){if(!v)return'';try{return new Date(v).toLocaleDateString('ar-IQ',{year:'numeric',month:'long',day:'numeric'});}catch(_){return'';}}
var socialMeta={facebook:['Facebook','f'],instagram:['Instagram','◎'],youtube:['YouTube','▶'],tiktok:['TikTok','♪'],whatsapp:['WhatsApp','☎'],telegram:['Telegram','✈'],website:['موقع شخصي','⌂'],other:['رابط آخر','↗']};
function decodeSocial(v){v=String(v||'');var p=v.indexOf('|');if(p>0){var n=v.slice(0,p),u=v.slice(p+1);if(socialMeta[n]&&safeUrl(u))return{network:n,url:safeUrl(u)};}if(safeUrl(v))return{network:'other',url:safeUrl(v)};return null;}
function encodeSocial(n,u){return n+'|'+u;}
function renderSocial(u){var root=document.querySelector('[data-social-links]');if(!root)return;root.innerHTML='';var list=Array.isArray(u.socialLinks)?u.socialLinks.slice():[];if(u.website&&!list.some(function(v){var x=decodeSocial(v);return x&&x.network==='website';}))list.push(encodeSocial('website',u.website));var items=list.map(decodeSocial).filter(Boolean);if(!items.length){root.innerHTML='<div class="empty-social">لم تتم إضافة روابط بعد.</div>';return;}items.forEach(function(x,i){var meta=socialMeta[x.network]||socialMeta.other,wrap=document.createElement('div');wrap.className='social-link-item';wrap.dataset.network=x.network;wrap.innerHTML='<span class="social-link-icon"></span><a class="social-link-main" target="_blank" rel="noopener noreferrer"><strong></strong><small></small></a>'+(u.isSelf||id==='me'?'<span class="social-link-actions"><button class="edit-link" type="button">تعديل</button><button class="delete-link" type="button">حذف</button></span>':'');wrap.querySelector('.social-link-icon').textContent=meta[1];var a=wrap.querySelector('a');a.href=x.url;a.querySelector('strong').textContent=meta[0];a.querySelector('small').textContent=x.url;var eb=wrap.querySelector('.edit-link'),db=wrap.querySelector('.delete-link');if(eb){eb.dataset.socialEdit=i;db.dataset.socialDelete=i;}root.appendChild(wrap);});}
async function saveProfileFields(fields){var fd=new FormData();Object.keys(fields).forEach(function(k){var v=fields[k];if(Array.isArray(v))v=v.join(',');fd.append(k,v==null?'':v);});return SocialAPI.request('/api/users/me/profile',{method:'PATCH',body:fd});}
async function loadFollow(){if(id==='me')return null;try{return await SocialAPI.request('/api/social/follow-state/'+encodeURIComponent(id));}catch(_){return null;}}
function render(data){var u=data.user||data.profile||data.data||{};currentUser=u;text('[data-full-name]',u.fullName||u.name||'مستخدم');text('[data-username]',u.username?'@'+u.username:'@غير متاح');text('[data-bio]',u.bio||'لا توجد نبذة منشورة.');text('[data-presence]',u.online?'متصل الآن':'غير متصل');text('[data-last-seen]',u.lastSeenVisible===false?'آخر ظهور مخفي':u.lastSeen?'آخر ظهور '+new Date(u.lastSeen).toLocaleString('ar-IQ'):'آخر ظهور غير متاح');text('[data-friends-count]',u.friendsCount===undefined?'—':u.friendsCount);text('[data-posts-count]',u.postsCount===undefined?'—':u.postsCount);text('[data-joined]',u.createdAt?new Date(u.createdAt).getFullYear():'—');
 var details=document.querySelector('[data-profile-details]');if(details)details.innerHTML='';addInfo('المحافظة',u.governorate);addInfo('المدينة',u.city);addInfo('محل الولادة',u.birthPlace);addInfo('العنوان',u.address);addInfo('تاريخ الميلاد',dateLabel(u.birthDate));addInfo('الجنس',genderLabel(u.gender));addInfo('التحصيل العلمي',u.education);addInfo('التخصص العلمي',u.academicSpecialization);addInfo('المهنة',u.profession);addInfo('مكان العمل',u.workplace);addInfo('رقم الهاتف',u.phone);addInfo('البريد الإلكتروني',u.email);if(u.website)addInfo('الموقع الإلكتروني',u.website);if(details&&!details.children.length)addInfo('المعلومات','لم يضف المستخدم معلومات شخصية بعد.');renderSocial(u);
 var avatar=document.querySelector('[data-avatar]');if(avatar)avatar.innerHTML=u.avatarUrl?'<img src="'+abs(u.avatarUrl)+'" alt="الصورة الشخصية">':(u.fullName||'؟').slice(0,1);var cover=document.querySelector('.profile-cover');if(cover)cover.innerHTML=u.coverUrl?'<img src="'+abs(u.coverUrl)+'" alt="صورة الغلاف" style="object-position:'+(u.coverPositionX||50)+'% '+(u.coverPositionY||50)+'%">':'';
 var self=u.isSelf||id==='me';document.querySelector('[data-edit-bio]')?.toggleAttribute('hidden',!self);document.querySelector('[data-add-social]')?.toggleAttribute('hidden',!self);var actions=document.querySelector('[data-profile-actions]');if(!actions)return;actions.innerHTML='';if(self){actions.append(action('تعديل الملف والصور','edit','primary'));actions.append(action('الخصوصية','privacy'));var ps=document.querySelector('[data-privacy-section]');if(ps)ps.hidden=false;document.querySelectorAll('[data-privacy]').forEach(function(f){if(u.privacy&&u.privacy[f.dataset.privacy])f.value=u.privacy[f.dataset.privacy];});return;}if(followState){actions.append(action(followState.following?'✓ متابَع · إلغاء المتابعة':'＋ متابعة',followState.following?'unfollow':'follow',followState.following?'':'primary'));}if(u.isFriend){var fb=action('✓ صديق','friend');fb.disabled=true;actions.append(fb);}else actions.append(action(u.friendStatus==='pending'?'إلغاء الطلب':'إضافة صديق',u.friendStatus==='pending'?'cancel-friend':'add-friend','primary'));actions.append(action('مراسلة','message'));actions.append(action('صوت','audio'));actions.append(action('فيديو','video'));}
async function load(){try{var pair=await Promise.all([SocialAPI.request('/api/users/'+encodeURIComponent(id)+'/profile'),loadFollow()]);followState=pair[1];render(pair[0]);}catch(e){setMessage(e.message,'error');text('[data-full-name]','تعذر تحميل الملف');}}
function openEdit(){var modal=document.querySelector('[data-edit-modal]'),form=document.querySelector('[data-edit-form]');if(!modal||!form)return;form.reset();modal.hidden=false;var fields=['fullName','governorate','city','birthPlace','address','education','academicSpecialization','profession','workplace','website'];fields.forEach(function(n){if(form.elements[n])form.elements[n].value=currentUser&&currentUser[n]||'';});if(form.elements.birthDate&&currentUser&&currentUser.birthDate)form.elements.birthDate.value=String(currentUser.birthDate).slice(0,10);if(form.elements.gender)form.elements.gender.value=currentUser&&currentUser.gender||'other';}
function openSocial(index){var editor=document.querySelector('[data-social-editor]'),network=document.querySelector('[data-social-network]'),url=document.querySelector('[data-social-url]');if(!editor)return;editingSocialIndex=typeof index==='number'?index:-1;var list=(currentUser&&Array.isArray(currentUser.socialLinks)?currentUser.socialLinks:[]).map(decodeSocial).filter(Boolean);if(editingSocialIndex>=0&&list[editingSocialIndex]){network.value=list[editingSocialIndex].network;url.value=list[editingSocialIndex].url;}else{network.value='facebook';url.value='';}editor.classList.add('is-open');url.focus();}
function closeSocial(){editingSocialIndex=-1;document.querySelector('[data-social-editor]')?.classList.remove('is-open');}
document.addEventListener('click',async function(e){var bioBtn=e.target.closest('[data-edit-bio]');if(bioBtn){var ed=document.querySelector('[data-bio-editor]'),inp=document.querySelector('[data-bio-input]');inp.value=currentUser&&currentUser.bio||'';ed.classList.add('is-open');inp.focus();return;}if(e.target.closest('[data-cancel-bio]')){document.querySelector('[data-bio-editor]')?.classList.remove('is-open');return;}if(e.target.closest('[data-save-bio]')){try{var bio=document.querySelector('[data-bio-input]').value.trim();await saveProfileFields({bio:bio});document.querySelector('[data-bio-editor]').classList.remove('is-open');await load();}catch(err){setMessage(err.message,'error');}return;}if(e.target.closest('[data-add-social]')){openSocial(-1);return;}if(e.target.closest('[data-cancel-social]')){closeSocial();return;}var edit=e.target.closest('[data-social-edit]');if(edit){openSocial(Number(edit.dataset.socialEdit));return;}var del=e.target.closest('[data-social-delete]');if(del){try{var list=(currentUser&&Array.isArray(currentUser.socialLinks)?currentUser.socialLinks:[]).slice();list.splice(Number(del.dataset.socialDelete),1);await saveProfileFields({socialLinks:list});await load();}catch(err){setMessage(err.message,'error');}return;}if(e.target.closest('[data-save-social]')){var n=document.querySelector('[data-social-network]').value,u=safeUrl(document.querySelector('[data-social-url]').value.trim());if(!u){setMessage('أدخل رابطاً صحيحاً يبدأ بـ http أو https.','error');return;}try{var links=(currentUser&&Array.isArray(currentUser.socialLinks)?currentUser.socialLinks:[]).slice();var val=encodeSocial(n,u);if(editingSocialIndex>=0&&editingSocialIndex<links.length)links[editingSocialIndex]=val;else links.push(val);links=links.slice(0,8);await saveProfileFields({socialLinks:links});closeSocial();await load();}catch(err){setMessage(err.message,'error');}return;}var b=e.target.closest('[data-profile-action]');if(!b)return;var a=b.dataset.profileAction;if(a==='privacy'){document.querySelector('[data-privacy-section]')?.scrollIntoView({behavior:'smooth'});return;}if(a==='edit'){openEdit();return;}if(a==='message'){location.href='messages.html?user='+encodeURIComponent(id);return;}if(a==='audio'||a==='video'){location.href='messages.html?call='+a+'&user='+encodeURIComponent(id);return;}try{if(a==='follow'||a==='unfollow'){await SocialAPI.request('/api/social/follow/'+encodeURIComponent(id),{method:a==='unfollow'?'DELETE':'POST'});await load();return;}var path=a==='add-friend'?'/api/friends/request/'+id:a==='cancel-friend'?'/api/friends/'+id:'';if(path){await SocialAPI.request(path,{method:a==='cancel-friend'?'DELETE':'POST'});await load();}}catch(err){setMessage(err.message,'error');}});
document.querySelector('[data-save-privacy]')?.addEventListener('click',async function(){var s={};document.querySelectorAll('[data-privacy]').forEach(function(f){s[f.dataset.privacy]=f.value;});try{await SocialAPI.request('/api/users/me/privacy',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(s)});setMessage('تم حفظ إعدادات الخصوصية.','success');}catch(e){setMessage(e.message,'error');}});
document.querySelector('[data-close-edit]')?.addEventListener('click',function(){document.querySelector('[data-edit-modal]').hidden=true;});
document.querySelector('[data-edit-form]')?.addEventListener('submit',async function(e){e.preventDefault();var form=e.target,msg=form.querySelector('[data-edit-message]'),btn=form.querySelector('[type="submit"]'),label=btn.textContent;btn.disabled=true;btn.textContent='جارٍ الحفظ…';try{var fd=new FormData(form);var account={birthDate:fd.get('birthDate')||'',gender:fd.get('gender')||'other'};fd.delete('birthDate');fd.delete('gender');await SocialAPI.request('/api/users/me',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(account)});var data=await SocialAPI.request('/api/users/me/profile',{method:'PATCH',body:fd});msg.textContent=data.message||'تم حفظ الملف الشخصي.';msg.className='form-message is-success';await load();setTimeout(function(){document.querySelector('[data-edit-modal]').hidden=true;},500);}catch(err){msg.textContent=err.message;msg.className='form-message is-error';}finally{btn.disabled=false;btn.textContent=label;}});
load();
}());
