(()=>{'use strict';
const API='https://shino-mino-tak-tak.duckdns.org',token=localStorage.getItem('token')||sessionStorage.getItem('token')||'',feed=document.getElementById('feed'),form=document.getElementById('upload'),clip=document.getElementById('clip'),preview=document.getElementById('preview'),note=document.getElementById('note'),sheet=document.getElementById('commentsSheet'),commentsList=document.getElementById('commentsList'),commentForm=document.getElementById('commentForm');let commentReel='';
const esc=v=>String(v||'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s])),abs=u=>!u?'':/^https?:/i.test(u)?u:API+u;
async function api(p,o={}){o.headers=Object.assign({Authorization:'Bearer '+token,Accept:'application/json'},o.headers||{});const r=await fetch(API+p,o),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||'تعذر تنفيذ الطلب');return d}
document.getElementById('create').onclick=()=>form.classList.toggle('open');clip.onchange=()=>{const f=clip.files[0];if(!f){preview.hidden=true;return}preview.src=URL.createObjectURL(f);preview.hidden=false;preview.onerror=()=>{note.textContent='ستتم معاينة هذه الصيغة بعد تحويلها عند النشر.'}};
function reelMedia(m){const src=esc(abs(m.url)),audio=m.type==='audio'||String(m.mimeType||'').startsWith('audio/');return audio?'<div class="audio-reel"><div class="audio-art">🎵</div><strong>ريلز صوتي</strong><audio controls preload="metadata" src="'+src+'"></audio><a href="'+src+'" download>⬇ تحميل الصوت</a></div>':'<video controls playsinline preload="metadata" src="'+src+'"><a href="'+src+'" download>تحميل الفيديو</a></video>'}
function card(r){const u=r.author||{},m=r.media&&r.media[0];if(!m)return'';return '<article class="reel-card" data-id="'+esc(r.id)+'">'+reelMedia(m)+'<div class="reel-meta"><div class="owner"><span class="avatar">'+esc((u.fullName||'?').slice(0,1))+'</span><strong>'+esc(u.fullName||u.username||'مستخدم')+'</strong></div><div>'+esc(r.text||'')+'</div></div><div class="actions"><button class="action like '+(r.liked?'active':'')+'" type="button">'+(r.liked?'♥':'♡')+'<small>'+Number(r.likes||0)+'</small></button><button class="action comment" type="button">💬<small>'+Number(r.commentsCount||0)+'</small></button><button class="action share" type="button">↗<small>مشاركة</small></button><button class="action save '+(r.saved?'active':'')+'" type="button">🔖<small>'+(r.saved?'محفوظ':'حفظ')+'</small></button></div></article>'}
async function load(){try{const d=await api('/api/reels'),a=d.reels||[];feed.innerHTML=a.length?a.map(card).join(''):'<div class="empty">لا توجد ريلز بعد. كن أول من ينشر مقطعاً.</div>';const vs=[...feed.querySelectorAll('video')];vs.forEach(v=>v.addEventListener('play',()=>vs.forEach(x=>{if(x!==v)x.pause()})))}catch(e){feed.innerHTML='<div class="empty bad">'+esc(e.message)+'</div>'}}
form.onsubmit=async e=>{e.preventDefault();if(!clip.files[0])return;const b=new FormData();b.append('media',clip.files[0]);b.append('text',document.getElementById('caption').value.trim());b.append('visibility',document.getElementById('reelVisibility').value);const btn=form.querySelector('[type=submit]');btn.disabled=true;note.className='note muted';note.textContent='جارٍ رفع الملف وتحويله إلى صيغة تشغيل موحدة...';try{await api('/api/reels',{method:'POST',body:b});note.className='note ok';note.textContent='تم نشر الريل.';form.reset();preview.hidden=true;await load()}catch(err){note.className='note bad';note.textContent=err.message}finally{btn.disabled=false}};
async function openComments(id){commentReel=id;sheet.hidden=false;commentsList.innerHTML='<p class="muted">جارٍ التحميل...</p>';try{const d=await api('/api/reels/'+id+'/comments');commentsList.innerHTML=d.comments.length?d.comments.map(c=>'<article class="reel-comment"><strong>'+esc(c.author?.fullName||c.author?.username||'مستخدم')+'</strong><p>'+esc(c.text)+'</p></article>').join(''):'<p class="muted">لا توجد تعليقات بعد.</p>'}catch(e){commentsList.innerHTML='<p class="bad">'+esc(e.message)+'</p>'}}
feed.onclick=async e=>{const c=e.target.closest('.reel-card');if(!c)return;const like=e.target.closest('.like'),save=e.target.closest('.save');try{if(like){const d=await api('/api/reels/'+c.dataset.id+'/like',{method:'POST'});like.classList.toggle('active',d.liked);like.firstChild.nodeValue=d.liked?'♥':'♡';like.querySelector('small').textContent=d.likesCount;return}if(save){const d=await api('/api/reels/'+c.dataset.id+'/save',{method:'POST'});save.classList.toggle('active',d.saved);save.querySelector('small').textContent=d.saved?'محفوظ':'حفظ';return}if(e.target.closest('.comment')){await openComments(c.dataset.id);return}if(e.target.closest('.share')){const url=location.origin+location.pathname+'#'+c.dataset.id;if(navigator.share)await navigator.share({title:'ريلز تك تك',url});else{await navigator.clipboard.writeText(url);alert('تم نسخ رابط الريل')}}}catch(err){alert(err.message)}};
document.querySelectorAll('[data-close-comments]').forEach(b=>b.onclick=()=>sheet.hidden=true);commentForm.onsubmit=async e=>{e.preventDefault();const input=document.getElementById('commentText'),value=input.value.trim();if(!value)return;try{const d=await api('/api/reels/'+commentReel+'/comments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:value})});input.value='';await openComments(commentReel);const card=feed.querySelector('[data-id="'+CSS.escape(commentReel)+'"] .comment small');if(card)card.textContent=d.commentsCount}catch(err){alert(err.message)}};
load();
})();
