(function(){'use strict';const root=document.querySelector('[data-rooms]'),status=document.querySelector('[data-status]'),form=document.querySelector('[data-create-form]');let rooms=[],filter='all';const esc=v=>String(v||'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s]));const labels={text:'💬 كتابية',voice:'🎙 صوتية',challenge:'🏆 تحديات'};
function approvalLabel(r){return r.privacy==='private'||r.joinApproval==='owner_approval'?'✅ الانضمام بموافقة المالك':'⚡ انضمام مباشر';}
function joinLabel(r){return r.privacy==='private'||r.joinApproval==='owner_approval'?'طلب انضمام':'انضم الآن';}
function draw(){const items=filter==='all'?rooms:rooms.filter(r=>r.roomType===filter);root.innerHTML=items.length?items.map(r=>'<article class="room-card '+(r.isOfficial?'official':'')+'"><div class="room-head"><span class="room-badge">'+esc(labels[r.roomType]||labels.text)+'</span>'+(r.isLive?'<span class="room-badge live">● مباشرة</span>':'')+'</div><h2>'+esc(r.name)+(r.isOfficial?' ✓':'')+'</h2><p>'+esc(r.description||'مجموعة شنو منو')+'</p><div class="room-meta"><span>'+(r.privacy==='private'?'🔒 خاصة':'🌐 عامة')+'</span><span>'+approvalLabel(r)+'</span><span>👥 '+Number(r.memberCount||0)+'</span>'+(r.isAdmin?'<span>🛡 أنت المسؤول</span>':'')+'</div><div class="room-actions">'+(r.joined?'<a class="room-button primary" href="group-room.html?id='+esc(r.id)+'">دخول المجموعة</a>'+(r.isAdmin?'':'<button class="room-button" data-leave="'+esc(r.id)+'">مغادرة</button>'):r.pending?'<button class="room-button" disabled>طلبك قيد المراجعة</button><button class="room-button" data-cancel="'+esc(r.id)+'">إلغاء الطلب</button>':'<button class="room-button primary" data-join="'+esc(r.id)+'">'+joinLabel(r)+'</button>')+'</div></article>').join(''):'<div class="room-card empty">لا توجد مجموعات في هذا القسم.</div>';}
async function load(){try{const d=await SocialAPI.request('/api/groups');rooms=d.groups||[];draw()}catch(e){status.textContent=e.message}}
const privacy=form.querySelector('[data-privacy]'),approval=form.querySelector('[data-join-approval]'),help=form.querySelector('[data-join-help]');function syncApproval(){if(privacy.value==='private'){approval.value='owner_approval';approval.disabled=true;help.textContent='المجموعة الخاصة تتطلب موافقة صاحب المجموعة دائماً.';}else{approval.disabled=false;help.textContent=approval.value==='owner_approval'?'كل طلب انضمام يصل إلى صاحب المجموعة للموافقة أو الرفض.':'يمكن لأي مستخدم الانضمام مباشرة.';}}privacy.onchange=syncApproval;approval.onchange=syncApproval;syncApproval();
document.querySelector('[data-create-toggle]').onclick=()=>form.hidden=false;document.querySelector('[data-create-cancel]').onclick=()=>form.hidden=true;
form.onsubmit=async e=>{e.preventDefault();approval.disabled=false;const body=Object.fromEntries(new FormData(form));syncApproval();try{const d=await SocialAPI.request('/api/groups',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});location.href='group-room.html?id='+encodeURIComponent(d.group.id)}catch(x){status.textContent=x.message}};
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));filter=b.dataset.filter;draw()});
root.onclick=async e=>{const join=e.target.closest('[data-join]'),cancel=e.target.closest('[data-cancel]'),leave=e.target.closest('[data-leave]');const b=join||cancel||leave;if(!b)return;b.disabled=true;try{const groupId=b.dataset.join||b.dataset.cancel||b.dataset.leave;const method=join?'POST':'DELETE';const d=await SocialAPI.request('/api/groups/'+groupId+'/join',{method});status.textContent=d.message||'تم تنفيذ العملية';await load()}catch(x){status.textContent=x.message;b.disabled=false}};load()}());
