(()=>{'use strict';
const token=()=>localStorage.getItem('token')||sessionStorage.getItem('token')||'';
const msg=document.querySelector('#schoolMessage');
let students=[],activeSession=null,sessionStartedAt=null,teacherHistory=[];
function show(text,bad=false){msg.hidden=false;msg.textContent=text;msg.className='message '+(bad?'bad':'ok');clearTimeout(show.t);show.t=setTimeout(()=>msg.hidden=true,4500)}
async function api(path,options={}){const headers={...(options.headers||{}),Authorization:`Bearer ${token()}`};if(options.body&&!(options.body instanceof FormData)){headers['Content-Type']='application/json';options.body=JSON.stringify(options.body)}const r=await fetch(path,{...options,headers});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.message||'تعذر تنفيذ الطلب');return data}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function studentOptions(){const html='<option value="">اختر الطالب</option>'+students.map(s=>`<option value="${s._id}">${esc(s.name)} — ${esc(s.stage)} ${esc(s.grade)}</option>`).join('');['scheduleStudent','studyStudent','reportStudent'].forEach(id=>document.getElementById(id).innerHTML=id==='reportStudent'?html.replace('اختر الطالب','اختر الطالب لعرض التقرير'):html);document.querySelector('#startStudy').disabled=!students.length||Boolean(activeSession)}
function renderStudents(){const box=document.querySelector('#students');box.innerHTML=students.length?students.map(s=>`<article class="student"><div><b>${esc(s.name)}</b><small>${esc(s.stage)} · ${esc(s.grade)}</small></div><div class="student-stats"><span>الحصص ${s.progress?.sessions||0}</span><span>المعدل ${Math.round(s.progress?.average||0)}%</span></div><button type="button" data-report="${s._id}">التقرير</button></article>`).join(''):'<p>لم يضف ولي الأمر طالبًا بعد.</p>';box.querySelectorAll('[data-report]').forEach(b=>b.onclick=()=>{document.querySelector('#reportStudent').value=b.dataset.report;loadReport(b.dataset.report)})}
async function loadStudents(){const d=await api('/api/school/students');students=d.students||[];renderStudents();studentOptions()}
async function loadSchedules(){const d=await api('/api/school/schedules');const box=document.querySelector('#schedules'),arr=d.schedules||[];box.innerHTML=arr.length?arr.map(x=>`<div class="schedule"><b>${esc(x.subject)}</b><span>${esc(x.student?.name||'طالب')}</span><time>${new Date(x.scheduledAt).toLocaleString('ar-IQ')}</time><em>${esc(x.status)}</em></div>`).join(''):'<p>لا توجد مواعيد بعد.</p>'}
async function loadReport(id){if(!id){document.querySelector('#report').innerHTML='';return}try{const d=await api(`/api/school/students/${id}/report`),s=d.student,r=d.report||{};document.querySelector('#report').innerHTML=`<div class="report-card"><h4>${esc(s.name)}</h4><div class="report-grid"><span>المعدل <b>${r.average||0}%</b></span><span>الحصص <b>${r.sessions||0}</b></span><span>الصف <b>${esc(s.stage)} ${esc(s.grade)}</b></span></div><h5>آخر ملاحظات المعلم</h5>${(r.latestNotes||[]).length?(r.latestNotes||[]).map(n=>`<p>• ${esc(n.text)}${n.subject?` — ${esc(n.subject)}`:''}</p>`).join(''):'<p>لا توجد ملاحظات بعد.</p>'}<h5>آخر الحصص</h5>${(d.sessions||[]).slice(0,10).map(x=>`<div class="session-row"><span>${esc(x.subject||'دراسة')} ${x.lesson?'— '+esc(x.lesson):''}</span><span>${x.maxScore?`${x.score}/${x.maxScore}`:'بدون درجة'}</span></div>`).join('')||'<p>لا توجد حصص مكتملة بعد.</p>'}<h5>آخر تفاعل مع المعلم</h5>${(d.learning||[]).slice(0,5).map(x=>`<div class="learning-row"><b>${esc(x.question)}</b><span>${esc(x.answer||'')}</span></div>`).join('')||'<p>لا يوجد حوار محفوظ بعد.</p>'}</div>`}catch(e){show(e.message,true)}}
function enterStudy(session){activeSession=session;sessionStartedAt=new Date(session.startedAt||Date.now()).getTime();const studentId=session.student?._id||session.student;document.querySelector('#studyStudent').value=studentId||'';document.querySelector('#studySubject').value=session.subject||'';document.querySelector('#studyLesson').value=session.lesson||'';document.querySelector('#studyMode').value=session.mode||'individual';document.body.classList.add('study-locked');document.querySelector('#studyState').innerHTML=`🔒 <b>وقت الدراسة مفعل</b> — ${esc(session.subject||'دراسة')}${session.lesson?' / '+esc(session.lesson):''}`;document.querySelector('#teacherBox').hidden=false;document.querySelector('#finishBox').hidden=false;document.querySelector('#startStudy').textContent='الحصة جارية';document.querySelector('#startStudy').disabled=true;document.querySelector('#teacherContext').textContent=`${session.subject||''}${session.lesson?' · '+session.lesson:''}`}
async function restoreActive(){const d=await api('/api/school/sessions/active');if(d.session)enterStudy(d.session)}
async function loadAI(){try{const d=await api('/api/school/ai/status');const el=document.querySelector('#aiStatus');el.textContent=d.configured?`المعلم متصل · ${d.provider}`:'المعلم غير مربوط';el.classList.toggle('offline',!d.configured)}catch(_){document.querySelector('#aiStatus').textContent='تعذر فحص المعلم'}}
function addBubble(role,text,sources=[]){const chat=document.querySelector('#teacherChat'),div=document.createElement('div');div.className='teacher-msg '+role;const src=sources.length?`<div class="sources">المصدر: ${sources.map(s=>`${esc(s.title)}${s.page?' — ص '+esc(s.page):''}`).join(' · ')}</div>`:'';div.innerHTML=`<div>${esc(text).replace(/\n/g,'<br>')}</div>${src}`;chat.appendChild(div);chat.scrollTop=chat.scrollHeight}
document.querySelector('#studentForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api('/api/school/students',{method:'POST',body:{name:f.get('name').trim(),stage:f.get('stage'),grade:f.get('grade').trim(),subjects:String(f.get('subjects')||'').split(/[,،]/).map(x=>x.trim()).filter(Boolean)}});e.currentTarget.reset();await loadStudents();show('تمت إضافة الطالب وربطه بولي الأمر')}catch(err){show(err.message,true)}};
document.querySelector('#scheduleForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api('/api/school/schedules',{method:'POST',body:{studentId:f.get('studentId'),subject:f.get('subject').trim(),scheduledAt:f.get('scheduledAt'),durationMinutes:Number(f.get('durationMinutes')||45),reminderMinutes:Number(f.get('reminderMinutes')||15)}});e.currentTarget.reset();e.currentTarget.durationMinutes.value=45;e.currentTarget.reminderMinutes.value=15;await loadSchedules();show('تم حفظ موعد الدراسة')}catch(err){show(err.message,true)}};
async function startStudy(){if(activeSession)return;const studentId=document.querySelector('#studyStudent').value,subject=document.querySelector('#studySubject').value.trim(),lesson=document.querySelector('#studyLesson').value.trim(),mode=document.querySelector('#studyMode').value;if(!studentId||!subject)return show('اختر الطالب واكتب المادة أولًا',true);try{const d=await api('/api/school/sessions/start',{method:'POST',body:{studentId,subject,lesson,mode}});teacherHistory=[];document.querySelector('#teacherChat').innerHTML='<div class="teacher-welcome">بدأت الحصة. اسأل المعلم عن الدرس.</div>';enterStudy(d.session);show('بدأت الحصة التعليمية')}catch(err){show(err.message,true)}}
document.querySelector('#startStudy').onclick=startStudy;
document.querySelector('#teacherForm').onsubmit=async e=>{e.preventDefault();if(!activeSession)return show('ابدأ الحصة أولًا',true);const input=document.querySelector('#teacherQuestion'),question=input.value.trim();if(!question)return;addBubble('user',question);input.value='';const send=document.querySelector('#teacherSend');send.disabled=true;send.textContent='يفكر...';try{const studentId=activeSession.student?._id||activeSession.student;const d=await api('/api/school/teacher/ask',{method:'POST',body:{studentId,sessionId:activeSession._id,subject:activeSession.subject,lesson:activeSession.lesson,question,history:teacherHistory}});addBubble('assistant',d.answer,d.sources||[]);teacherHistory.push({role:'user',content:question},{role:'assistant',content:d.answer});teacherHistory=teacherHistory.slice(-8);const r=document.querySelector('#responses');r.value=Number(r.value||0)+1}catch(err){addBubble('assistant','تعذر الحصول على رد: '+err.message);show(err.message,true)}finally{send.disabled=false;send.textContent='إرسال'}};
document.querySelector('#clearTeacher').onclick=()=>{teacherHistory=[];document.querySelector('#teacherChat').innerHTML='<div class="teacher-welcome">تم مسح الحوار الظاهر فقط. السجل التعليمي المحفوظ لا يُحذف.</div>'};
document.querySelector('#finishStudy').onclick=async()=>{if(!activeSession)return;const activeMinutes=Math.max(1,Math.round((Date.now()-sessionStartedAt)/60000));try{const d=await api(`/api/school/sessions/${activeSession._id}/complete`,{method:'POST',body:{score:Number(document.querySelector('#finishScore').value||0),maxScore:Number(document.querySelector('#finishMax').value||10),teacherNote:document.querySelector('#teacherNote').value.trim(),responses:Number(document.querySelector('#responses').value||0),unanswered:Number(document.querySelector('#unanswered').value||0),activeMinutes}});document.body.classList.remove('study-locked');document.querySelector('#studyState').textContent='لا توجد حصة جارية.';document.querySelector('#teacherBox').hidden=true;document.querySelector('#finishBox').hidden=true;document.querySelector('#startStudy').textContent='ابدأ وقت الدراسة';activeSession=null;sessionStartedAt=null;teacherHistory=[];await loadStudents();studentOptions();show(`اكتملت الحصة${d.parentSummary?.score?' — الدرجة '+d.parentSummary.score:''}`)}catch(err){show(err.message,true)}};
document.querySelector('#reportStudent').onchange=e=>loadReport(e.target.value);
window.addEventListener('beforeunload',e=>{if(activeSession){e.preventDefault();e.returnValue=''}});
(async()=>{try{await Promise.all([loadStudents(),loadSchedules(),loadAI()]);await restoreActive()}catch(e){show(e.message,true)}})();
})();