(()=>{'use strict';
const token=()=>localStorage.getItem('token')||sessionStorage.getItem('token')||'';
const msg=document.querySelector('#schoolMessage');
let students=[],activeSession=null,sessionStartedAt=null;
function show(text,bad=false){msg.hidden=false;msg.textContent=text;msg.className='message '+(bad?'bad':'ok');clearTimeout(show.t);show.t=setTimeout(()=>msg.hidden=true,4500)}
async function api(path,options={}){const headers={...(options.headers||{}),Authorization:`Bearer ${token()}`};if(options.body&&!(options.body instanceof FormData)){headers['Content-Type']='application/json';options.body=JSON.stringify(options.body)}const r=await fetch(path,{...options,headers});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.message||'تعذر تنفيذ الطلب');return data}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function studentOptions(){const html='<option value="">اختر الطالب</option>'+students.map(s=>`<option value="${s._id}">${esc(s.name)} — ${esc(s.stage)} ${esc(s.grade)}</option>`).join('');['scheduleStudent','studyStudent','reportStudent'].forEach(id=>document.getElementById(id).innerHTML= id==='reportStudent'?html.replace('اختر الطالب','اختر الطالب لعرض التقرير'):html);document.querySelector('#startStudy').disabled=!students.length}
function renderStudents(){const box=document.querySelector('#students');box.innerHTML=students.length?students.map(s=>`<article class="student"><div><b>${esc(s.name)}</b><small>${esc(s.stage)} · ${esc(s.grade)}</small></div><div class="student-stats"><span>الحصص ${s.progress?.sessions||0}</span><span>المعدل ${Math.round(s.progress?.average||0)}%</span></div><button type="button" data-report="${s._id}">التقرير</button></article>`).join(''):'<p>لم يضف ولي الأمر طالبًا بعد.</p>';box.querySelectorAll('[data-report]').forEach(b=>b.onclick=()=>{document.querySelector('#reportStudent').value=b.dataset.report;loadReport(b.dataset.report)})}
async function loadStudents(){const d=await api('/api/school/students');students=d.students||[];renderStudents();studentOptions()}
async function loadSchedules(){const d=await api('/api/school/schedules');const box=document.querySelector('#schedules');const arr=d.schedules||[];box.innerHTML=arr.length?arr.map(x=>`<div class="schedule"><b>${esc(x.subject)}</b><span>${esc(x.student?.name||'طالب')}</span><time>${new Date(x.scheduledAt).toLocaleString('ar-IQ')}</time><em>${esc(x.status)}</em></div>`).join(''):'<p>لا توجد مواعيد بعد.</p>'}
async function loadReport(id){if(!id){document.querySelector('#report').innerHTML='';return}try{const d=await api(`/api/school/students/${id}/report`),s=d.student,r=d.report||{};document.querySelector('#report').innerHTML=`<div class="report-card"><h4>${esc(s.name)}</h4><div class="report-grid"><span>المعدل <b>${r.average||0}%</b></span><span>الحصص <b>${r.sessions||0}</b></span><span>الصف <b>${esc(s.stage)} ${esc(s.grade)}</b></span></div><h5>آخر ملاحظات المعلم</h5>${(r.latestNotes||[]).length?(r.latestNotes||[]).map(n=>`<p>• ${esc(n.text)}${n.subject?` — ${esc(n.subject)}`:''}</p>`).join(''):'<p>لا توجد ملاحظات بعد.</p>'}<h5>آخر الحصص</h5>${(d.sessions||[]).slice(0,10).map(x=>`<div class="session-row"><span>${esc(x.subject||'دراسة')} ${x.lesson?'— '+esc(x.lesson):''}</span><span>${x.maxScore?`${x.score}/${x.maxScore}`:'بدون درجة'}</span></div>`).join('')||'<p>لا توجد حصص مكتملة بعد.</p>'}</div>`}catch(e){show(e.message,true)}}
document.querySelector('#studentForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api('/api/school/students',{method:'POST',body:{name:f.get('name').trim(),stage:f.get('stage'),grade:f.get('grade').trim(),subjects:String(f.get('subjects')||'').split(/[,،]/).map(x=>x.trim()).filter(Boolean)}});e.currentTarget.reset();await loadStudents();show('تمت إضافة الطالب وربطه بولي الأمر')}catch(err){show(err.message,true)}};
document.querySelector('#scheduleForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api('/api/school/schedules',{method:'POST',body:{studentId:f.get('studentId'),subject:f.get('subject').trim(),scheduledAt:f.get('scheduledAt'),durationMinutes:Number(f.get('durationMinutes')||45),reminderMinutes:Number(f.get('reminderMinutes')||15)}});e.currentTarget.reset();e.currentTarget.durationMinutes.value=45;e.currentTarget.reminderMinutes.value=15;await loadSchedules();show('تم حفظ موعد الدراسة')}catch(err){show(err.message,true)}};
async function startStudy(){if(activeSession)return;const studentId=document.querySelector('#studyStudent').value,subject=document.querySelector('#studySubject').value.trim(),lesson=document.querySelector('#studyLesson').value.trim(),mode=document.querySelector('#studyMode').value;if(!studentId||!subject)return show('اختر الطالب واكتب المادة أولًا',true);try{const d=await api('/api/school/sessions/start',{method:'POST',body:{studentId,subject,lesson,mode}});activeSession=d.session;sessionStartedAt=Date.now();document.body.classList.add('study-locked');document.querySelector('#studyState').innerHTML=`🔒 <b>وقت الدراسة مفعل</b> — ${esc(subject)}${lesson?' / '+esc(lesson):''}`;document.querySelector('#finishBox').hidden=false;document.querySelector('#startStudy').textContent='الحصة جارية';document.querySelector('#startStudy').disabled=true;show('بدأت الحصة التعليمية')}catch(err){show(err.message,true)}}
document.querySelector('#startStudy').onclick=startStudy;
document.querySelector('#finishStudy').onclick=async()=>{if(!activeSession)return;const activeMinutes=Math.max(1,Math.round((Date.now()-sessionStartedAt)/60000));try{const d=await api(`/api/school/sessions/${activeSession._id}/complete`,{method:'POST',body:{score:Number(document.querySelector('#finishScore').value||0),maxScore:Number(document.querySelector('#finishMax').value||10),teacherNote:document.querySelector('#teacherNote').value.trim(),responses:Number(document.querySelector('#responses').value||0),unanswered:Number(document.querySelector('#unanswered').value||0),activeMinutes}});document.body.classList.remove('study-locked');document.querySelector('#studyState').textContent='لا توجد حصة جارية.';document.querySelector('#finishBox').hidden=true;document.querySelector('#startStudy').textContent='ابدأ وقت الدراسة';document.querySelector('#startStudy').disabled=!students.length;activeSession=null;sessionStartedAt=null;await loadStudents();show(`اكتملت الحصة${d.parentSummary?.score?' — الدرجة '+d.parentSummary.score:''}`)}catch(err){show(err.message,true)}};
document.querySelector('#reportStudent').onchange=e=>loadReport(e.target.value);
window.addEventListener('beforeunload',e=>{if(activeSession){e.preventDefault();e.returnValue=''}});
(async()=>{try{await Promise.all([loadStudents(),loadSchedules()])}catch(e){show(e.message,true)}})();
})();