(function(){
  'use strict';
  const friendsRoot=document.querySelector('[data-talk-friends]');
  const requestsRoot=document.querySelector('[data-talk-requests]');
  const contactsBtn=document.querySelector('[data-contacts]');
  const contactsResult=document.querySelector('[data-contact-result]');
  function esc(v){return String(v||'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s]));}
  function row(user){return '<div class="friend-row"><span class="avatar">'+esc((user.fullName||'?').slice(0,1))+'</span><div class="friend-copy"><strong>'+esc(user.fullName||'مستخدم')+'</strong><small>@'+esc(user.username||'—')+'</small></div><div class="friend-actions"><a href="messages.html?user='+encodeURIComponent(user.id)+'&call=audio">☎ صوت</a><a href="messages.html?user='+encodeURIComponent(user.id)+'&call=video">▣ فيديو</a><a href="messages.html?user='+encodeURIComponent(user.id)+'">✉ شات</a><a href="game-room.html?challenge='+encodeURIComponent(user.id)+'">🎯 تحدي</a></div></div>';}
  async function loadFriends(){try{const data=await SocialAPI.request('/api/friends');const items=data.friends||[];friendsRoot.innerHTML=items.length?items.map(row).join(''):'<div class="empty">لا يوجد أصدقاء بعد. ابدأ من صفحة إضافة الأصدقاء.</div>';}catch(error){friendsRoot.innerHTML='<div class="empty">'+esc(error.message)+'</div>';}}
  async function loadRequests(type){try{const data=await SocialAPI.request('/api/friends/requests?type='+(type==='sent'?'sent':'incoming'));const items=data.requests||[];requestsRoot.innerHTML=items.length?items.map(function(item){const u=item.user||item.sender||item.receiver||{};return '<div class="friend-row"><span class="avatar">'+esc((u.fullName||'?').slice(0,1))+'</span><div class="friend-copy"><strong>'+esc(u.fullName||'مستخدم')+'</strong><small>@'+esc(u.username||'—')+'</small></div><div class="friend-actions">'+(type==='sent'?'<button data-cancel="'+esc(item.id)+'">إلغاء</button>':'<button data-accept="'+esc(item.id)+'">قبول</button><button data-reject="'+esc(item.id)+'">رفض</button>')+'</div></div>';}).join(''):'<div class="empty">لا توجد طلبات في هذا القسم.</div>';}catch(error){requestsRoot.innerHTML='<div class="empty">'+esc(error.message)+'</div>';}}
  document.querySelectorAll('[data-request-tab]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-request-tab]').forEach(x=>x.classList.toggle('active',x===btn));loadRequests(btn.dataset.requestTab);}));
  requestsRoot.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.dataset.accept)await SocialAPI.request('/api/friends/requests/'+b.dataset.accept+'/accept',{method:'POST'});if(b.dataset.reject)await SocialAPI.request('/api/friends/requests/'+b.dataset.reject+'/reject',{method:'POST'});if(b.dataset.cancel)await SocialAPI.request('/api/friends/requests/'+b.dataset.cancel+'/cancel',{method:'PATCH'});await loadRequests(document.querySelector('[data-request-tab].active')?.dataset.requestTab||'incoming');await loadFriends();}catch(error){alert(error.message);}});
  contactsBtn.addEventListener('click',async()=>{if(!('contacts' in navigator)||!navigator.contacts.select){contactsResult.innerHTML='<p class="contact-note">متصفحك لا يدعم اختيار جهات الاتصال مباشرة. استخدم صفحة دعوة الأصدقاء لمشاركة رابط التسجيل.</p>';return;}try{const contacts=await navigator.contacts.select(['name','tel'],{multiple:false});if(!contacts.length)return;const c=contacts[0],name=(c.name&&c.name[0])||'جهة اتصال',tel=(c.tel&&c.tel[0])||'';contactsResult.innerHTML='<div class="friend-row"><div class="friend-copy"><strong>'+esc(name)+'</strong><small>'+esc(tel)+'</small></div><div class="friend-actions"><a href="tel:'+encodeURIComponent(tel)+'">☎ اتصال</a><a href="invite-friends.html">➕ دعوة لشنو منو</a></div></div>';}catch{contactsResult.innerHTML='<p class="contact-note">لم يتم اختيار جهة اتصال.</p>';}});
  loadFriends();loadRequests('incoming');
}());
