(function(){'use strict';
const API='https://shino-mino-tak-tak.duckdns.org';
const token=localStorage.getItem('token')||sessionStorage.getItem('token')||'';
const feed=document.querySelector('[data-feed]'),form=document.querySelector('[data-composer]'),fileInput=document.querySelector('[data-media]'),textInput=document.querySelector('[data-post-text]'),visibility=document.querySelector('[data-visibility]'),meBox=document.querySelector('[data-me-avatar]'),storyMe=document.querySelector('[data-story-me-avatar]'),peopleList=document.querySelector('[data-people-list]'),peopleSearch=document.querySelector('[data-people-search]'),storiesList=document.querySelector('[data-stories-list]'),reelsList=document.querySelector('[data-reels-list]');
function headers(extra){return Object.assign({Authorization:'Bearer '+token,Accept:'application/json'},extra||{});}async function json(path,options){const r=await fetch(API+path,Object.assign({},options||{},{headers:headers((options||{}).headers)}));const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||'تعذر تنفيذ الطلب');return d;}function esc(v){return String(v||'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s]));}function absolute(url){if(!url)return'';return /^https?:\/\//i.test(url)?url:API+url;}function shortName(v){const s=String(v||'مستخدم').trim();return s.split(/\s+/).slice(0,2).join(' ');}function avatar(u,cls='avatar'){const url=u&&(u.avatarUrl||u.profile&&u.profile.avatarUrl);return url?'<span class="'+cls+'"><img src="'+esc(absolute(url))+'" alt=""></span>':'<span class="'+cls+'">'+esc((u&&(u.fullName||u.displayName)||'?').slice(0,1))+'</span>';}function time(v){try{return new Intl.DateTimeFormat('ar-IQ',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v));}catch{return '';}}
function media(p){if(!p.media||!p.media.length)return '';const m=p.media[0],src=esc(absolute(m.url)),type=String(m.type||''),mime=String(m.mimeType||'');if(type==='video'||mime.startsWith('video/'))return '<div class="post-media post-video"><video controls playsinline preload="metadata" src="'+src+'"></video></div>';if(type==='audio'||mime.startsWith('audio/'))return '<div class="post-media"><audio controls preload="metadata" src="'+src+'"></audio></div>';return '<div class="post-media"><img loading="lazy" src="'+src+'" alt=""></div>';}
function moreMenu(p){const m=p.media&&p.media[0],kind=m&&(m.type==='video'||String(m.mimeType||'').startsWith('video/'))?'الفيديو':m&&(m.type==='audio'||String(m.mimeType||'').startsWith('audio/'))?'الصوت':'الصورة',download=m&&m.url?'<a href="'+esc(absolute(m.url))+'" download data-download>⬇ تحميل '+kind+'</a>':'';if(!download&&!p.canEdit&&!p.canDelete)return '';return '<span class="post-more"><button class="post-more-toggle" type="button" data-action="more" aria-expanded="false" title="المزيد">⋮</button><span class="post-more-menu" hidden>'+download+(p.canEdit?'<button type="button" data-action="edit">✏️ تعديل المنشور</button>':'')+(p.canDelete?'<button type="button" data-action="delete">🗑 حذف المنشور</button>':'')+'</span></span>';}
function card(p){const author=p.author||{};return '<article class="post-card" data-post-id="'+esc(p.id)+'"><div class="post-head">'+avatar(author)+'<div class="post-meta"><a href="profile.html?id='+esc(author.id)+'"><strong>'+esc(shortName(author.fullName))+'</strong></a><small>'+(author.username?'@'+esc(author.username)+' · ':'')+esc(time(p.createdAt))+'</small></div></div>'+(p.text?'<div class="post-text">'+esc(p.text)+'</div>':'')+media(p)+'<div class="post-stats"><span data-likes-count>'+Number(p.likesCount||0)+' إعجاب</span><span data-comments-count>'+Number(p.commentsCount||0)+' تعليق</span></div><div class="post-actions"><button type="button" data-action="like">♡ إعجاب</button><button type="button" data-action="comments">💬 تعليق</button><button type="button" data-action="message" data-user="'+esc(author.id)+'">✉ مراسلة</button>'+moreMenu(p)+'</div><div class="comments" hidden data-comments><div data-comments-list></div><form class="comment-form" data-comment-form><input name="text" maxlength="2000" placeholder="اكتب تعليقاً..."><button>إرسال</button></form></div></article>';}
function person(u){return '<a class="person-card" href="profile.html?id='+esc(u.id)+'" title="'+esc(u.fullName||u.username)+'">'+avatar(u)+'<span><strong>'+esc(shortName(u.fullName||u.username))+'</strong><small>@'+esc(u.username)+'</small></span></a>';}
function storyTile(s){const u=s.author||{},m=s.media&&s.media[0],thumb=m&&m.type==='image'?absolute(m.url):(u.avatarUrl?absolute(u.avatarUrl):'');const visual=thumb?'<span class="story-avatar"><img src="'+esc(thumb)+'" alt=""></span>':avatar(u,'story-avatar');return '<a class="story-tile" href="stories.html?id='+esc(s.id)+'" title="'+esc(u.fullName||u.username||'قصة')+'">'+visual+'<strong>'+esc(shortName(u.fullName||u.username||'قصة'))+'</strong></a>';}
function reelCard(r){const u=r.author||{},m=r.media&&r.media[0];if(!m||!m.url)return '';return '<a class="reel-card" href="reels.html?id='+esc(r.id)+'" title="'+esc(u.fullName||u.username||'ريل')+'"><video muted playsinline preload="metadata" src="'+esc(absolute(m.url))+'"></video><span class="reel-meta"><strong>'+esc(shortName(u.fullName||u.username||'ريل'))+'</strong><span>♥ '+Number(r.likes||r.likesCount||0)+'</span></span></a>';}
async function loadPeople(q){if(!peopleList)return;try{const data=await json(q&&q.length>=2?'/api/users/search?q='+encodeURIComponent(q):'/api/users/discover');peopleList.innerHTML=(data.users||[]).length?data.users.map(person).join(''):'<div class="empty">لا توجد نتائج.</div>';}catch(e){peopleList.innerHTML='<div class="empty">'+esc(e.message)+'</div>';}}
async function loadStories(){if(!storiesList)return;try{const d=await json('/api/stories');const list=d.stories||[];storiesList.innerHTML=list.length?list.map(storyTile).join(''):'<div class="empty inline-empty">لا توجد قصص الآن.</div>';}catch(e){storiesList.innerHTML='<div class="empty inline-empty">'+esc(e.message)+'</div>';}}
async function loadReels(){if(!reelsList)return;try{const d=await json('/api/reels');const list=d.reels||[];reelsList.innerHTML=list.length?list.map(reelCard).join(''):'<div class="empty inline-empty">لا توجد ريلز بعد.</div>';}catch(e){reelsList.innerHTML='<div class="empty inline-empty">'+esc(e.message)+'</div>';}}
async function loadFeed(){try{const d=await json('/api/posts');feed.innerHTML=d.posts&&d.posts.length?d.posts.map(card).join(''):'<div class="post-card empty">لا توجد منشورات بعد.</div>';}catch(e){feed.innerHTML='<div class="post-card empty">'+esc(e.message)+'</div>';}}
async function loadMe(){try{const d=await json('/api/users/me'),u=d.user||{},url=u.profile&&u.profile.avatarUrl;const html=url?'<img src="'+esc(absolute(url))+'" alt="">':esc((u.displayName||u.fullName||'?').slice(0,1));if(meBox)meBox.innerHTML=html;if(storyMe)storyMe.innerHTML=html;}catch{}}
form&&form.addEventListener('submit',e=>{e.preventDefault();const btn=form.querySelector('[type=submit]');btn.disabled=true;let prog=document.querySelector('.upload-progress');if(!prog){prog=document.createElement('div');prog.className='upload-progress';prog.innerHTML='<span>جارٍ الرفع...</span><div class="upload-progress-bar"><div></div></div>';document.body.appendChild(prog);}const bar=prog.querySelector('.upload-progress-bar>div');const xhr=new XMLHttpRequest();xhr.upload.addEventListener('progress',ev=>{if(ev.lengthComputable)bar.style.width=Math.round(ev.loaded/ev.total*100)+'%';});xhr.open('POST',API+'/api/posts',true);xhr.setRequestHeader('Authorization','Bearer '+token);xhr.onreadystatechange=()=>{if(xhr.readyState===4){btn.disabled=false;prog.remove();if(xhr.status>=200&&xhr.status<300){const d=JSON.parse(xhr.responseText);if(d.ok){textInput.value='';fileInput.value='';feed.insertAdjacentHTML('afterbegin',card(d.post));}else alert(d.message||'فشل النشر');}else{try{const d=JSON.parse(xhr.responseText);alert(d.message||'فشل الرفع');}catch{alert('خطأ في الاتصال');}}}};const b=new FormData();b.append('text',textInput.value.trim());b.append('visibility',visibility.value);if(fileInput.files[0])b.append('media',fileInput.files[0]);xhr.send(b);});
feed&&feed.addEventListener('click',async e=>{const post=e.target.closest('[data-post-id]'),action=e.target.closest('[data-action]');if(!post||!action)return;const id=post.dataset.postId;
if(action.dataset.action==='more'){const menu=action.parentElement.querySelector('.post-more-menu'),opening=menu.hidden;document.querySelectorAll('.post-more-menu').forEach(x=>x.hidden=true);document.querySelectorAll('.post-more-toggle').forEach(x=>x.setAttribute('aria-expanded','false'));menu.hidden=!opening;action.setAttribute('aria-expanded',opening?'true':'false');return;}
if(action.dataset.action==='like'){try{const d=await json('/api/posts/'+id+'/like',{method:'POST'});post.querySelector('[data-likes-count]').textContent=d.likesCount+' إعجاب';}catch(err){alert(err.message);}}else if(action.dataset.action==='comments'){const box=post.querySelector('[data-comments]');box.hidden=!box.hidden;if(!box.hidden&&!box.dataset.loaded){const d=await json('/api/posts/'+id+'/comments');box.querySelector('[data-comments-list]').innerHTML=(d.comments||[]).map(c=>'<div class="comment">'+avatar(c.author)+'<div class="comment-body"><strong>'+esc(c.author.fullName)+'</strong><p>'+esc(c.text)+'</p></div></div>').join('');box.dataset.loaded='1';}}else if(action.dataset.action==='message'){location.href='messages.html?user='+encodeURIComponent(action.dataset.user);}else if(action.dataset.action==='edit'){const current=post.querySelector('.post-text')?.textContent||'';const next=prompt('عدّل نص المنشور:',current);if(next===null)return;try{const d=await json('/api/posts/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:next})});post.outerHTML=card(d.post);}catch(err){alert(err.message);}}else if(action.dataset.action==='delete'){if(!confirm('هل تريد حذف هذا المنشور نهائياً؟'))return;try{await json('/api/posts/'+id,{method:'DELETE'});post.remove();}catch(err){alert(err.message);}}});
feed&&feed.addEventListener('submit',async e=>{const cf=e.target.closest('[data-comment-form]');if(!cf)return;e.preventDefault();const post=cf.closest('[data-post-id]'),input=cf.elements.text;if(!input.value.trim())return;try{const d=await json('/api/posts/'+post.dataset.postId+'/comments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:input.value.trim()})});post.querySelector('[data-comments-list]').insertAdjacentHTML('beforeend','<div class="comment">'+avatar(d.comment.author)+'<div class="comment-body"><strong>'+esc(d.comment.author.fullName)+'</strong><p>'+esc(d.comment.text)+'</p></div></div>');post.querySelector('[data-comments-count]').textContent=d.commentsCount+' تعليق';input.value='';}catch(err){alert(err.message);}});
document.addEventListener('click',e=>{if(e.target.closest('.post-more'))return;document.querySelectorAll('.post-more-menu').forEach(x=>x.hidden=true);document.querySelectorAll('.post-more-toggle').forEach(x=>x.setAttribute('aria-expanded','false'));});
document.addEventListener('play',e=>{if(e.target.tagName!=='VIDEO'&&e.target.tagName!=='AUDIO')return;document.querySelectorAll('video,audio').forEach(v=>{if(v!==e.target&&!v.paused)v.pause();});},true);
let timer;peopleSearch&&peopleSearch.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>loadPeople(peopleSearch.value.trim()),300);});
document.querySelector('[data-photo-btn]')?.addEventListener('click',()=>{fileInput.accept='image/*';fileInput.click();});document.querySelector('[data-video-btn]')?.addEventListener('click',()=>{fileInput.accept='video/*,.mp4,.m4v,.mov,.webm,.3gp,.3g2,.mkv,.avi';fileInput.click();});document.querySelector('[data-audio-btn]')?.addEventListener('click',()=>{fileInput.accept='audio/mpeg,audio/mp3,audio/mp4,audio/x-m4a,audio/wav,.mp3,.m4a,.wav';fileInput.click();});
document.getElementById('logout')?.addEventListener('click',()=>{localStorage.removeItem('token');localStorage.removeItem('user');sessionStorage.removeItem('token');sessionStorage.removeItem('user');location.replace('signin.html');});
loadMe();loadPeople('');loadStories();loadReels();loadFeed();
function enablePullRefresh(){if(!matchMedia('(max-width:760px)').matches)return;let startY=0,pulling=false,busy=false;const tip=document.createElement('div');tip.className='pull-refresh';tip.textContent='↓ اسحب للتحديث';document.body.appendChild(tip);document.addEventListener('touchstart',e=>{if(busy||scrollY>0||e.touches.length!==1||e.target.closest('input,textarea,select,button,a'))return;startY=e.touches[0].clientY;pulling=true;},{passive:true});document.addEventListener('touchmove',e=>{if(!pulling)return;const distance=Math.max(0,Math.min(110,e.touches[0].clientY-startY));tip.classList.toggle('show',distance>12);tip.classList.toggle('ready',distance>=72);tip.textContent=distance>=72?'↻ اترك للتحديث':'↓ اسحب للتحديث';tip.style.setProperty('--pull',distance+'px');},{passive:true});document.addEventListener('touchend',async e=>{if(!pulling)return;pulling=false;const ready=tip.classList.contains('ready');tip.classList.remove('ready');if(!ready){tip.classList.remove('show');tip.style.removeProperty('--pull');return;}busy=true;tip.classList.add('loading');tip.textContent='↻ جارٍ التحديث…';try{await Promise.all([loadMe(),loadPeople(peopleSearch?.value.trim()||''),loadStories(),loadReels(),loadFeed()]);tip.textContent='✓ تم التحديث';}finally{setTimeout(()=>{tip.classList.remove('show','loading');tip.style.removeProperty('--pull');busy=false;},550);}});}
enablePullRefresh();
const mobileNav=document.createElement('script');mobileNav.src='taktak-mobile-nav.js?v=20260911-1';document.body.appendChild(mobileNav);
const liveAds=document.createElement('script');liveAds.src='taktak-live-ads.js?v=20260911-1';document.body.appendChild(liveAds);
})();
(function(){const btn=document.getElementById('theme-toggle');if(!btn)return;const saved=localStorage.getItem('taktak-theme');const prefersDark=window.matchMedia('(prefers-color-scheme: dark)').matches;const dark=(saved==='dark')||(saved===null&&prefersDark);document.documentElement.setAttribute('data-theme',dark?'dark':'light');document.body.classList.toggle('light',!dark);btn.addEventListener('click',()=>{const isLight=document.documentElement.getAttribute('data-theme')==='light';const next=isLight?'dark':'light';document.documentElement.setAttribute('data-theme',next);document.body.classList.toggle('light',next==='light');localStorage.setItem('taktak-theme',next);});})();
