(function(){'use strict';
const API='https://shino-mino-tak-tak.duckdns.org';
const token=localStorage.getItem('token')||sessionStorage.getItem('token')||'';
const auth={Authorization:'Bearer '+token,Accept:'application/json'};
let stories=[],storyIndex=0,storyTimer=null,reels=[],reelIndex=0;
const esc=v=>String(v||'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[s]));
const abs=u=>!u?'':/^https?:\/\//i.test(u)?u:API+u;
async function api(path){const r=await fetch(API+path,{headers:auth});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||'تعذر تحميل المحتوى');return d;}
function ensureStoryViewer(){let root=document.getElementById('homeStoryViewer');if(root)return root;root=document.createElement('div');root.id='homeStoryViewer';root.className='home-viewer';root.hidden=true;root.innerHTML='<div class="home-viewer-backdrop" data-story-close></div><section class="story-viewer-card" role="dialog" aria-modal="true" aria-label="عرض القصة"><div class="story-progress" data-story-progress></div><header class="viewer-head"><div data-story-owner></div><button type="button" class="viewer-close" data-story-close aria-label="إغلاق">×</button></header><button type="button" class="viewer-nav prev" data-story-prev aria-label="السابق">‹</button><div class="story-stage" data-story-stage></div><button type="button" class="viewer-nav next" data-story-next aria-label="التالي">›</button></section>';document.body.appendChild(root);root.addEventListener('click',e=>{if(e.target.closest('[data-story-close]'))closeStory();else if(e.target.closest('[data-story-prev]'))showStory(storyIndex-1);else if(e.target.closest('[data-story-next]'))showStory(storyIndex+1);});return root;}
function storyOwner(s){const u=s.author||{},a=u.avatarUrl?'<img src="'+esc(abs(u.avatarUrl))+'" alt="">':'<span>'+esc((u.fullName||u.username||'?').slice(0,1))+'</span>';return '<div class="viewer-owner-avatar">'+a+'</div><div><strong>'+esc(u.fullName||u.username||'مستخدم')+'</strong><small>'+new Date(s.createdAt).toLocaleString('ar-IQ')+'</small></div>';}
function storyMedia(s){const m=s.media&&s.media[0];let visual='';if(m&&m.url){visual=m.type==='video'?'<video autoplay playsinline controls src="'+esc(abs(m.url))+'"></video>':'<img src="'+esc(abs(m.url))+'" alt="">';}else visual='<div class="story-text-only">'+esc(s.text||'✨')+'</div>';const ovs=(s.overlays||[]).map(o=>'<span class="viewer-story-overlay" style="left:'+Number(o.x||50)+'%;top:'+Number(o.y||50)+'%;font-size:'+Number(o.size||32)+'px">'+esc(o.value)+'</span>').join('');const caption=s.text&&m?'<div class="viewer-caption">'+esc(s.text)+'</div>':'';const music=s.music&&s.music.url?'<audio autoplay controls src="'+esc(abs(s.music.url))+'"></audio>':'';return visual+ovs+caption+music;}
function closeStory(){clearTimeout(storyTimer);storyTimer=null;const root=document.getElementById('homeStoryViewer');if(root){root.hidden=true;root.querySelectorAll('video,audio').forEach(v=>{v.pause();v.removeAttribute('src');});}document.body.classList.remove('viewer-open');}
function showStory(i){if(!stories.length)return;clearTimeout(storyTimer);if(i<0)i=stories.length-1;if(i>=stories.length){closeStory();return;}storyIndex=i;const s=stories[i],root=ensureStoryViewer();root.hidden=false;document.body.classList.add('viewer-open');root.querySelector('[data-story-owner]').innerHTML=storyOwner(s);root.querySelector('[data-story-stage]').innerHTML=storyMedia(s);root.querySelector('[data-story-progress]').innerHTML=stories.map((_,x)=>'<span class="'+(x<=i?'done':'')+'"></span>').join('');const v=root.querySelector('video');if(v){v.onended=()=>showStory(storyIndex+1);}else storyTimer=setTimeout(()=>showStory(storyIndex+1),6000);}
async function openStory(id){try{const d=await api('/api/stories');stories=d.stories||[];const idx=stories.findIndex(s=>String(s.id)===String(id));showStory(idx>=0?idx:0);}catch(e){alert(e.message);}}
function ensureReelViewer(){let root=document.getElementById('homeReelViewer');if(root)return root;root=document.createElement('div');root.id='homeReelViewer';root.className='home-viewer';root.hidden=true;root.innerHTML='<div class="home-viewer-backdrop" data-reel-close></div><section class="reel-viewer-card" role="dialog" aria-modal="true" aria-label="عرض الريلز"><header class="viewer-head"><div data-reel-owner></div><button type="button" class="viewer-close" data-reel-close aria-label="إغلاق">×</button></header><button type="button" class="viewer-nav prev" data-reel-prev aria-label="السابق">‹</button><div class="reel-stage" data-reel-stage></div><button type="button" class="viewer-nav next" data-reel-next aria-label="التالي">›</button></section>';document.body.appendChild(root);root.addEventListener('click',e=>{if(e.target.closest('[data-reel-close]'))closeReel();else if(e.target.closest('[data-reel-prev]'))showReel(reelIndex-1);else if(e.target.closest('[data-reel-next]'))showReel(reelIndex+1);});return root;}
function closeReel(){const root=document.getElementById('homeReelViewer');if(root){root.hidden=true;root.querySelectorAll('video').forEach(v=>{v.pause();v.removeAttribute('src');});}document.body.classList.remove('viewer-open');}
function showReel(i){if(!reels.length)return;if(i<0)i=reels.length-1;if(i>=reels.length)i=0;reelIndex=i;const r=reels[i],m=r.media&&r.media[0],u=r.author||{},root=ensureReelViewer();if(!m)return;root.hidden=false;document.body.classList.add('viewer-open');root.querySelector('[data-reel-owner]').innerHTML='<strong>'+esc(u.fullName||u.username||'مستخدم')+'</strong>';root.querySelector('[data-reel-stage]').innerHTML='<video autoplay playsinline controls src="'+esc(abs(m.url))+'"></video>'+(r.text?'<div class="viewer-caption">'+esc(r.text)+'</div>':'');}
async function openReel(id){try{const d=await api('/api/reels');reels=d.reels||[];const idx=reels.findIndex(r=>String(r.id)===String(id));showReel(idx>=0?idx:0);}catch(e){alert(e.message);}}
function wireHover(card){const v=card.querySelector('video');if(!v||card.dataset.hoverWired)return;card.dataset.hoverWired='1';v.controls=false;card.addEventListener('mouseenter',()=>{if(matchMedia('(hover:hover) and (pointer:fine)').matches){v.muted=false;v.volume=1;v.play().catch(()=>{});}});card.addEventListener('mouseleave',()=>{if(matchMedia('(hover:hover) and (pointer:fine)').matches){v.pause();v.currentTime=0;}});}
const observer=new MutationObserver(()=>document.querySelectorAll('[data-reels-list] .reel-card').forEach(wireHover));observer.observe(document.documentElement,{childList:true,subtree:true});
document.addEventListener('click',e=>{const story=e.target.closest('[data-stories-list] .story-tile');if(story){e.preventDefault();const id=(story.getAttribute('href')||'').match(/id=([^&]+)/)?.[1];if(id)openStory(decodeURIComponent(id));return;}const reel=e.target.closest('[data-reels-list] .reel-card');if(reel){e.preventDefault();reel.querySelector('video')?.pause();const id=(reel.getAttribute('href')||'').match(/id=([^&]+)/)?.[1];if(id)openReel(decodeURIComponent(id));}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeStory();closeReel();}else if(!document.getElementById('homeStoryViewer')?.hidden&&e.key==='ArrowLeft')showStory(storyIndex+1);else if(!document.getElementById('homeStoryViewer')?.hidden&&e.key==='ArrowRight')showStory(storyIndex-1);});
})();