(function(){
'use strict';
const video=document.getElementById('mainVideoPlayer');
const wrapper=document.getElementById('videoWrapper');
const placeholder=document.getElementById('videoPlaceholder');
const menuOverlay=document.querySelector('[data-menu-overlay]');
const list=document.querySelector('[data-channel-list]');
const search=document.querySelector('[data-search]');
const editBtn=document.querySelector('[data-edit]');
const inlineAdd=document.querySelector('[data-inline-add]');
const playlistSelect=document.querySelector('[data-playlist-select]');
const urlOverlay=document.querySelector('[data-url-overlay]');
const playlistNameOverlay=document.querySelector('[data-playlist-name-overlay]');
const volume=document.querySelector('[data-volume]');
const volumeValue=document.querySelector('[data-volume-value]');
const now=document.querySelector('[data-now-title]');
const playPause=document.querySelector('[data-play-pause]');
const mute=document.querySelector('[data-mute]');
const individualMode=document.querySelector('[data-individual-mode]');
const groupMode=document.querySelector('[data-group-mode]');
const collective=document.querySelector('[data-collective]');
const roomStatus=document.querySelector('[data-room-status]');
const voiceState=document.querySelector('[data-voice-state]');
const viewersBox=document.querySelector('[data-viewers]');
const viewerCount=document.querySelector('[data-viewer-count]');
const messagesBox=document.querySelector('[data-messages]');
const messageForm=document.querySelector('[data-message-form]');
const messageInput=document.querySelector('[data-message-input]');
const requestsCard=document.querySelector('[data-requests-card]');
const requestsBox=document.querySelector('[data-requests]');
const requestCount=document.querySelector('[data-request-count]');
const moderation=document.querySelector('[data-moderation]');
const params=new URLSearchParams(location.search);
const roomId=params.get('room')||params.get('groupId')||params.get('id')||localStorage.getItem('taktak_tv_room_id')||'';
const socket=window.io&&window.SocialAPI&&SocialAPI.token()?window.io(SocialAPI.baseUrl,{auth:{token:SocialAPI.token()}}):null;
let hls=null,editMode=false,pendingM3U='',activeId='',fitContain=true;
let tvRoom=null,currentUserId='',localStream=null,collectiveActive=false;
const peers={},participants=new Map(),selected=new Set(),speaking=new Set();

function esc(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function absolute(url){return url&&(/^https?:/i.test(url)?url:SocialAPI.baseUrl+url);}
function getPlaylists(){try{return JSON.parse(localStorage.getItem('taktak_tv_playlists')||'{}')}catch(e){return {}}}
function savePlaylists(v){localStorage.setItem('taktak_tv_playlists',JSON.stringify(v));}
function ensureDefault(){const p=getPlaylists();if(!Object.keys(p).length){p['قنواتي']={};savePlaylists(p);}return p;}
function updatePlaylistSelector(){const p=ensureDefault();const names=Object.keys(p);const old=playlistSelect.value;playlistSelect.innerHTML=names.map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join('');playlistSelect.value=names.includes(old)?old:names[0];}
function currentPlaylist(){const p=ensureDefault();return p[playlistSelect.value]||{};}
function flatChannels(){const rows=[];for(const [group,chs] of Object.entries(currentPlaylist()))for(const [name,url] of Object.entries(chs||{}))rows.push({id:group+'::'+name,group,name,url});return rows;}
function render(){const q=(search.value||'').trim().toLowerCase();const grouped={};for(const c of flatChannels()){if(q&&!c.name.toLowerCase().includes(q)&&!c.group.toLowerCase().includes(q))continue;(grouped[c.group]||(grouped[c.group]=[])).push(c);}let html='';for(const [group,chs] of Object.entries(grouped)){html+=`<div class="channel-group-title">${esc(group)}</div>`;for(const c of chs){html+=`<div class="channel-item ${editMode?'edit-mode ':''}${c.id===activeId?'is-active':''}" data-id="${esc(c.id)}"><div class="play-btn" data-play-channel><i class="fas fa-play-circle" style="color:#38bdf8"></i><span>${esc(c.name)}</span></div><span class="del-btn" data-delete-channel><i class="fas fa-trash-alt"></i></span></div>`;}}
list.innerHTML=html||'<div style="color:#94a3b8;text-align:center;padding:20px">لا توجد قنوات في هذا الملف</div>';inlineAdd.classList.toggle('is-open',editMode);}
function validStreamUrl(url){try{const u=new URL(url);return /^https?:$/.test(u.protocol)&&!/(porn|xxx|adult|sexcam|hentai)/i.test(u.href);}catch(e){return false;}}
function playUrl(name,url){if(!validStreamUrl(url)){alert('الرابط غير صالح أو غير مسموح.');return;}activeId='';for(const c of flatChannels())if(c.name===name&&c.url===url)activeId=c.id;now.textContent=name||'قناة';placeholder.style.display='none';if(hls){hls.destroy();hls=null;}if(video.canPlayType('application/vnd.apple.mpegurl'))video.src=url;else if(/\.m3u8(?:\?|$)/i.test(url)&&window.Hls&&Hls.isSupported()){hls=new Hls();hls.loadSource(url);hls.attachMedia(video);}else video.src=url;video.play().catch(()=>{});render();}
function addChannel(name,url,group='📌 قنوات مخصصة'){if(!name||!url)return alert('أدخل اسم القناة والرابط.');if(!validStreamUrl(url))return alert('الرابط غير صالح أو غير مسموح.');const p=ensureDefault();const key=playlistSelect.value||Object.keys(p)[0];p[key]||(p[key]={});p[key][group]||(p[key][group]={});p[key][group][name]=url;savePlaylists(p);render();}
function deleteChannel(c){if(!confirm(`حذف قناة "${c.name}"؟`))return;const p=ensureDefault();const key=playlistSelect.value;if(p[key]&&p[key][c.group]){delete p[key][c.group][c.name];if(!Object.keys(p[key][c.group]).length)delete p[key][c.group];savePlaylists(p);render();}}
function parseM3U(content){const out={};let group='قنوات عامة',name='';for(let line of String(content||'').split(/\r?\n/)){line=line.trim();if(line.startsWith('#EXTINF')){const gm=line.match(/group-title="([^"]*)"/i);if(gm&&gm[1])group=gm[1];const nm=line.match(/,(.*)$/);name=nm&&nm[1]?nm[1].trim():'';}else if(line&&!line.startsWith('#')&&name){if(validStreamUrl(line)){out[group]||(out[group]={});out[group][name]=line;}name='';}}return out;}
function setVolume(v){v=Math.max(0,Math.min(100,Number(v)||0));video.volume=v/100;volume.value=String(v);volumeValue.textContent=v+'%';mute.querySelector('i').className=v===0?'fas fa-volume-xmark':v<50?'fas fa-volume-low':'fas fa-volume-high';}
function noteMode(text){const note=placeholder.querySelector('small');if(note)note.textContent=text;}
function activateIndividualMode(){collectiveActive=false;localStorage.setItem('taktak_tv_mode','individual');collective.hidden=true;individualMode.classList.add('is-active');groupMode.classList.remove('is-active');individualMode.setAttribute('aria-pressed','true');individualMode.textContent='✓ مشاهدة فردية';groupMode.textContent='👥 مشاهدة جماعية';noteMode('الوضع الحالي: مشاهدة فردية.');leaveVoice();}

function avatarMarkup(user){const url=user.avatarUrl||user.profile?.avatarUrl||'';return url?`<span class="viewer-avatar"><img src="${esc(absolute(url))}" alt=""></span>`:`<span class="viewer-avatar">${esc((user.fullName||user.name||'?').slice(0,1))}</span>`;}
function isModerator(){return Boolean(tvRoom&&(tvRoom.isModerator||tvRoom.isAdmin));}
function renderViewers(data){const members=data?.members||[];viewerCount.textContent=String(members.length);moderation.hidden=!isModerator();viewersBox.innerHTML=members.map(user=>{const id=String(user.id||user._id);const part=participants.get(id);const isMuted=Boolean(user.muted||part?.muted);const isSpeaking=speaking.has(id)&&!isMuted;const mine=id===currentUserId;const canManage=isModerator()&&!mine&&user.role!=='owner';return `<div class="viewer-row ${isMuted?'is-muted ':''}${isSpeaking?'is-speaking':''}" data-viewer="${esc(id)}">${canManage?`<input class="viewer-check" type="checkbox" data-select-viewer="${esc(id)}" ${selected.has(id)?'checked':''}>`:''}${avatarMarkup(user)}<div class="viewer-copy"><strong>${esc(user.fullName||user.name||'مستخدم')}</strong><small>@${esc(user.username||'')}</small><span class="viewer-state">${isMuted?'🔇 مكتوم':isSpeaking?'<span class="speaking-badge"><span class="speaking-bars"><i></i><i></i><i></i></span> يتكلم الآن</span>':'🎙 الصوت مفتوح'}</span></div>${canManage?`<div class="viewer-tools"><button type="button" data-member-action="${user.muted?'unmute':'mute'}" data-user="${esc(id)}">${user.muted?'فك الكتم':'كتم'}</button><button type="button" class="danger" data-member-action="kick" data-user="${esc(id)}">إبعاد</button></div>`:''}</div>`;}).join('')||'<div class="empty-row">لا يوجد مشاهدون بعد.</div>';}
function renderRequests(data){const pending=data?.pending||[];requestsCard.hidden=!isModerator();requestCount.textContent=String(pending.length);requestsBox.innerHTML=pending.map(user=>`<div class="request-row"><div class="request-person">${avatarMarkup(user)}<div><strong>${esc(user.fullName||'مستخدم')}</strong><small>@${esc(user.username||'')}</small></div></div><div class="request-actions"><button class="accept" type="button" data-request-action="accept" data-user="${esc(user.id)}">قبول</button><button class="reject" type="button" data-request-action="reject" data-user="${esc(user.id)}">رفض</button></div></div>`).join('')||'<div class="empty-row">لا توجد طلبات انضمام.</div>';}
async function loadMembers(){if(!roomId||!collectiveActive)return;try{const data=await SocialAPI.request('/api/groups/'+encodeURIComponent(roomId)+'/members');renderViewers(data);renderRequests(data);}catch(e){roomStatus.textContent=e.message;}}
function messageMarkup(item){return `<article class="tv-message"><strong>${esc(item.sender?.fullName||'مستخدم')}</strong><time>${new Date(item.createdAt||Date.now()).toLocaleTimeString('ar-IQ',{hour:'2-digit',minute:'2-digit'})}</time>${item.text?`<p>${esc(item.text).replace(/\n/g,'<br>')}</p>`:''}</article>`;}
function appendMessage(item){messagesBox.querySelector('.empty-row')?.remove();messagesBox.insertAdjacentHTML('beforeend',messageMarkup(item));messagesBox.scrollTop=messagesBox.scrollHeight;}
function setSpeaking(userId,on){const id=String(userId);if(on)speaking.add(id);else speaking.delete(id);const row=document.querySelector(`[data-viewer="${CSS.escape(id)}"]`);if(!row)return;row.classList.toggle('is-speaking',on);const state=row.querySelector('.viewer-state');const part=participants.get(id);if(state&&!part?.muted)state.innerHTML=on?'<span class="speaking-badge"><span class="speaking-bars"><i></i><i></i><i></i></span> يتكلم الآن</span>':'🎙 الصوت مفتوح';}
function watchLevel(stream,userId){try{const context=new (window.AudioContext||window.webkitAudioContext)(),analyser=context.createAnalyser(),values=new Uint8Array(128);analyser.fftSize=256;context.createMediaStreamSource(stream).connect(analyser);let last=false;const tick=()=>{if(!collectiveActive||!stream.active){setSpeaking(userId,false);return context.close();}analyser.getByteFrequencyData(values);const talking=values.reduce((sum,v)=>sum+v,0)/values.length>18;if(talking!==last){last=talking;setSpeaking(userId,talking);}requestAnimationFrame(tick);};tick();}catch(_){} }
function peerFor(userId,start){const id=String(userId);if(peers[id])return peers[id];if(!localStream)return null;const peer=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});peers[id]=peer;localStream.getTracks().forEach(track=>peer.addTrack(track,localStream));peer.ontrack=event=>{let audio=document.querySelector(`audio[data-tv-audio="${CSS.escape(id)}"]`);if(!audio){audio=document.createElement('audio');audio.autoplay=true;audio.playsInline=true;audio.dataset.tvAudio=id;audio.hidden=true;document.body.appendChild(audio);}audio.srcObject=event.streams[0];audio.play().catch(()=>{});watchLevel(event.streams[0],id);};peer.onicecandidate=event=>{if(event.candidate)socket?.emit('webrtc:group-ice',{groupId:roomId,userId:id,data:event.candidate});};if(start)negotiate(id).catch(()=>{});return peer;}
async function negotiate(userId){const peer=peerFor(userId,false);if(!peer)return;const offer=await peer.createOffer();await peer.setLocalDescription(offer);socket?.emit('webrtc:group-offer',{groupId:roomId,userId,data:peer.localDescription});}
async function startAutomaticVoice(){if(!socket||!navigator.mediaDevices?.getUserMedia){voiceState.textContent='الصوت غير مدعوم';return;}if(localStream)return;try{voiceState.textContent='جاري تشغيل الصوت تلقائياً...';localStream=await navigator.mediaDevices.getUserMedia({audio:true,video:false});localStream.getAudioTracks().forEach(t=>t.enabled=true);watchLevel(localStream,currentUserId);socket.emit('group-voice:join',{groupId:roomId},result=>{if(!result?.ok){localStream?.getTracks().forEach(t=>t.stop());localStream=null;voiceState.textContent=result?.message||'تعذر تشغيل الصوت';return;}participants.clear();(result.participants||[]).forEach(user=>participants.set(String(user.id),user));const mine=participants.get(currentUserId);if(mine)mine.muted=false;socket.emit('group-voice:mute',{groupId:roomId,muted:false});voiceState.textContent='🎙 الصوت مفتوح تلقائياً';(result.participants||[]).forEach(user=>{if(String(user.id)!==currentUserId)peerFor(String(user.id),currentUserId<String(user.id));});loadMembers();});}catch(e){voiceState.textContent='يلزم السماح للمتصفح باستخدام الميكروفون مرة واحدة';roomStatus.textContent='تعذر تشغيل الصوت تلقائياً: '+e.message;}}
function leaveVoice(){if(roomId)socket?.emit('group-voice:leave',{groupId:roomId});if(localStream){localStream.getTracks().forEach(t=>t.stop());localStream=null;}Object.values(peers).forEach(p=>p.close());Object.keys(peers).forEach(k=>delete peers[k]);participants.clear();speaking.clear();document.querySelectorAll('audio[data-tv-audio]').forEach(a=>a.remove());}
async function activateGroupMode(){if(!roomId){alert('غرفة المشاهدة الجماعية غير محددة. افتح TV من رابط الغرفة أو البث الجماعي.');return;}if(!window.SocialAPI||!socket){alert('تعذر الاتصال بخدمة الغرفة. سجّل الدخول ثم حاول مرة أخرى.');return;}collectiveActive=true;localStorage.setItem('taktak_tv_mode','collective');localStorage.setItem('taktak_tv_room_id',roomId);collective.hidden=false;groupMode.classList.add('is-active');individualMode.classList.remove('is-active');groupMode.textContent='✓ مشاهدة جماعية';individualMode.textContent='👤 مشاهدة فردية';noteMode('الوضع الحالي: مشاهدة جماعية.');try{const [me,data]=await Promise.all([SocialAPI.request('/api/users/me'),SocialAPI.request('/api/groups/'+encodeURIComponent(roomId)+'/messages')]);currentUserId=String(me.user?.id||'');tvRoom=data.group;messagesBox.innerHTML=(data.messages||[]).map(messageMarkup).join('')||'<div class="empty-row">لا توجد رسائل بعد.</div>';roomStatus.textContent=tvRoom.name||'غرفة TV الجماعية';socket.emit('group:join',{groupId:roomId},result=>{if(!result?.ok)roomStatus.textContent=result?.message||'تعذر دخول الغرفة';});await loadMembers();await startAutomaticVoice();}catch(e){roomStatus.textContent=e.message;}}
async function memberAction(userId,action){await SocialAPI.request('/api/groups/'+encodeURIComponent(roomId)+'/members/'+encodeURIComponent(userId)+'/'+action,{method:'PATCH'});await loadMembers();}
async function requestAction(userId,action){await SocialAPI.request('/api/groups/'+encodeURIComponent(roomId)+'/requests/'+encodeURIComponent(userId)+'/'+action,{method:'PATCH'});await loadMembers();}
async function muteMany(ids){for(const id of ids){try{await memberAction(id,'mute');}catch(_){}}selected.clear();await loadMembers();}

setVolume(80);
menuOverlay.addEventListener('click',e=>{if(e.target===menuOverlay)menuOverlay.classList.remove('is-open');});
document.querySelector('[data-open-menu]').onclick=()=>{updatePlaylistSelector();render();menuOverlay.classList.add('is-open');};
document.querySelector('[data-close-menu]').onclick=()=>menuOverlay.classList.remove('is-open');
editBtn.onclick=()=>{editMode=!editMode;editBtn.textContent=editMode?'✅ إغلاق الإدارة':'🛠️ إدارة';render();};playlistSelect.onchange=render;search.oninput=render;
list.addEventListener('click',e=>{const item=e.target.closest('.channel-item');if(!item)return;const c=flatChannels().find(x=>x.id===item.dataset.id);if(!c)return;if(e.target.closest('[data-delete-channel]'))return deleteChannel(c);if(e.target.closest('[data-play-channel]')){menuOverlay.classList.remove('is-open');playUrl(c.name,c.url);}});
document.querySelector('[data-inline-save]').onclick=()=>{const n=document.querySelector('[data-inline-name]'),u=document.querySelector('[data-inline-url]');addChannel(n.value.trim(),u.value.trim());n.value='';u.value='';};
document.querySelector('[data-open-url]').onclick=()=>urlOverlay.classList.add('is-open');document.querySelector('[data-close-url]').onclick=()=>urlOverlay.classList.remove('is-open');
document.querySelector('[data-direct-save]').onclick=()=>{const n=document.querySelector('[data-direct-name]'),u=document.querySelector('[data-direct-url]');addChannel(n.value.trim(),u.value.trim());if(n.value&&u.value){n.value='';u.value='';urlOverlay.classList.remove('is-open');}};
document.querySelector('[data-m3u-file]').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=ev=>{pendingM3U=String(ev.target.result||'');document.querySelector('[data-playlist-name]').value=f.name.replace(/\.(m3u8?|txt)$/i,'');playlistNameOverlay.classList.add('is-open');};r.readAsText(f);e.target.value='';};
document.querySelector('[data-playlist-import]').onclick=()=>{const name=document.querySelector('[data-playlist-name]').value.trim();if(!name)return;const channels=parseM3U(pendingM3U),p=ensureDefault();p[name]=channels;savePlaylists(p);pendingM3U='';playlistNameOverlay.classList.remove('is-open');updatePlaylistSelector();playlistSelect.value=name;render();alert(`تم استيراد ${Object.values(channels).reduce((n,g)=>n+Object.keys(g).length,0)} قناة.`);};document.querySelector('[data-playlist-cancel]').onclick=()=>{pendingM3U='';playlistNameOverlay.classList.remove('is-open');};
document.querySelector('[data-video-file]').onchange=e=>{const f=e.target.files[0];if(!f)return;if(hls){hls.destroy();hls=null;}placeholder.style.display='none';video.src=URL.createObjectURL(f);now.textContent=f.name;video.play().catch(()=>{});};
volume.oninput=()=>setVolume(volume.value);document.querySelector('[data-volume-down]').onclick=()=>setVolume(Math.round(video.volume*100)-10);document.querySelector('[data-volume-up]').onclick=()=>setVolume(Math.round(video.volume*100)+10);mute.onclick=()=>{if(video.volume>0){video.dataset.prevVolume=video.volume;setVolume(0);}else setVolume(Math.round((Number(video.dataset.prevVolume)||.8)*100));};playPause.onclick=()=>{if(video.paused)video.play().catch(()=>{});else video.pause();};video.addEventListener('play',()=>playPause.querySelector('i').className='fas fa-pause');video.addEventListener('pause',()=>playPause.querySelector('i').className='fas fa-play');document.querySelector('[data-fit]').onclick=()=>{fitContain=!fitContain;video.style.objectFit=fitContain?'contain':'cover';};document.querySelectorAll('[data-size]').forEach(b=>b.onclick=()=>{if(b.dataset.size==='max')wrapper.classList.add('is-maximized');else wrapper.classList.remove('is-maximized');});document.addEventListener('keydown',e=>{if(e.key==='Escape')wrapper.classList.remove('is-maximized');});
individualMode.onclick=activateIndividualMode;groupMode.onclick=activateGroupMode;
messageForm.onsubmit=async e=>{e.preventDefault();const text=messageInput.value.trim();if(!text||!collectiveActive)return;try{await SocialAPI.request('/api/groups/'+encodeURIComponent(roomId)+'/messages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});messageInput.value='';}catch(err){roomStatus.textContent=err.message;}};
viewersBox.addEventListener('change',e=>{const box=e.target.closest('[data-select-viewer]');if(!box)return;box.checked?selected.add(box.dataset.selectViewer):selected.delete(box.dataset.selectViewer);});
viewersBox.addEventListener('click',async e=>{const btn=e.target.closest('[data-member-action]');if(!btn)return;try{await memberAction(btn.dataset.user,btn.dataset.memberAction);}catch(err){roomStatus.textContent=err.message;}});
requestsBox.addEventListener('click',async e=>{const btn=e.target.closest('[data-request-action]');if(!btn)return;try{await requestAction(btn.dataset.user,btn.dataset.requestAction);}catch(err){roomStatus.textContent=err.message;}});
document.querySelector('[data-mute-selected]').onclick=()=>muteMany(Array.from(selected));document.querySelector('[data-mute-all]').onclick=()=>{const ids=Array.from(document.querySelectorAll('[data-viewer]')).map(x=>x.dataset.viewer).filter(id=>id!==currentUserId);muteMany(ids);};document.querySelector('[data-clear-selection]').onclick=()=>{selected.clear();document.querySelectorAll('[data-select-viewer]').forEach(x=>x.checked=false);};
urlOverlay.addEventListener('click',e=>{if(e.target===urlOverlay)urlOverlay.classList.remove('is-open');});playlistNameOverlay.addEventListener('click',e=>{if(e.target===playlistNameOverlay)playlistNameOverlay.classList.remove('is-open');});

if(socket){
 socket.on('group:message',payload=>{if(collectiveActive&&String(payload.groupId)===String(roomId))appendMessage(payload.message);});
 socket.on('group:state',payload=>{if(collectiveActive&&String(payload.groupId)===String(roomId)){if(payload.group)tvRoom={...tvRoom,...payload.group};loadMembers();}});
 socket.on('group:moderation',payload=>{if(String(payload.groupId)!==String(roomId))return;if(payload.action==='mute'){localStream?.getAudioTracks().forEach(t=>t.enabled=false);voiceState.textContent='🔇 تم كتمك بواسطة إدارة الغرفة';}if(payload.action==='unmute'){localStream?.getAudioTracks().forEach(t=>t.enabled=true);voiceState.textContent='🎙 الصوت مفتوح تلقائياً';}if(['kick','ban'].includes(payload.action)){alert('تم إبعادك من غرفة المشاهدة.');activateIndividualMode();}});
 socket.on('group-voice:participants',payload=>{if(!collectiveActive||String(payload.groupId)!==String(roomId)||!localStream)return;participants.clear();(payload.participants||[]).forEach(user=>participants.set(String(user.id),user));Object.keys(peers).forEach(id=>{if(!participants.has(id)){peers[id].close();delete peers[id];document.querySelector(`audio[data-tv-audio="${CSS.escape(id)}"]`)?.remove();}});(payload.participants||[]).forEach(user=>{if(String(user.id)!==currentUserId)peerFor(String(user.id),currentUserId<String(user.id));});loadMembers();});
 socket.on('group-voice:mute',payload=>{if(String(payload.groupId)!==String(roomId))return;const p=participants.get(String(payload.userId));if(p)p.muted=Boolean(payload.muted);if(payload.muted)setSpeaking(payload.userId,false);loadMembers();});
 socket.on('webrtc:group-offer',async payload=>{if(!collectiveActive||String(payload.groupId)!==String(roomId)||!localStream)return;const peer=peerFor(String(payload.from),false);await peer.setRemoteDescription(payload.data);const answer=await peer.createAnswer();await peer.setLocalDescription(answer);socket.emit('webrtc:group-answer',{groupId:roomId,userId:payload.from,data:peer.localDescription});});
 socket.on('webrtc:group-answer',payload=>peers[payload.from]?.setRemoteDescription(payload.data).catch(()=>{}));
 socket.on('webrtc:group-ice',payload=>peers[payload.from]?.addIceCandidate(payload.data).catch(()=>{}));
}
addEventListener('beforeunload',leaveVoice);
if(localStorage.getItem('taktak_tv_mode')==='collective'&&roomId)activateGroupMode();else activateIndividualMode();
updatePlaylistSelector();render();
})();