const express=require('express'),jwt=require('jsonwebtoken'),crypto=require('crypto'),bcrypt=require('bcryptjs'),QRCode=require('qrcode');
const {generateRegistrationOptions,verifyRegistrationResponse,generateAuthenticationOptions,verifyAuthenticationResponse}=require('@simplewebauthn/server');
const User=require('../models/User'),DeveloperMfa=require('../models/DeveloperMfa');
const router=express.Router(),ORIGIN=process.env.WEBAUTHN_ORIGIN||'https://shino-mino-tak-tak.duckdns.org',RPID=process.env.WEBAUTHN_RP_ID||'shino-mino-tak-tak.duckdns.org';
function fullToken(user){return jwt.sign({userId:user._id,role:user.role},process.env.JWT_SECRET,{expiresIn:'7d'});}
async function preAuth(req,res,next){try{const raw=String(req.headers.authorization||'').replace(/^Bearer\s+/i,''),p=jwt.verify(raw,process.env.JWT_SECRET);if(p.scope!=='developer-mfa')throw Error();const u=await User.findOne({_id:p.userId,role:'developer',status:'active'});if(!u)throw Error();req.user=u;next();}catch(_){res.status(401).json({ok:false,message:'انتهت مهلة التحقق. أعد إدخال كلمة المرور'});}}
async function security(user){return DeveloperMfa.findOneAndUpdate({user:user._id},{$setOnInsert:{user:user._id}},{new:true,upsert:true});}
router.get('/status',preAuth,async(req,res)=>{const s=await security(req.user);res.json({ok:true,phone:Boolean(s.phoneSecretHash),fido:s.credentials.length>0,phoneNumber:s.pairedPhone||req.user.phone||''});});
router.post('/phone/enroll',preAuth,async(req,res)=>{const phone=String(req.body.phone||req.user.phone||'').replace(/\s+/g,'');if(!/^07\d{9}$/.test(phone))return res.status(400).json({ok:false,message:'رقم هاتف المطور غير صالح'});const secret=crypto.randomBytes(32).toString('base64url'),s=await security(req.user);s.pairedPhone=phone;s.phoneSecretHash=await bcrypt.hash(secret,12);s.phonePairedAt=new Date();await s.save();const url=`${ORIGIN}/developer-phone.html#pair=${secret}&user=${req.user._id}`;res.json({ok:true,qr:await QRCode.toDataURL(url,{width:280,margin:1}),url,message:'امسح الرمز بهاتف المطور لإكمال الاقتران'});});
router.post('/phone/challenge',preAuth,async(req,res)=>{const s=await security(req.user);if(!s.phoneSecretHash)return res.status(409).json({ok:false,message:'الهاتف غير مقترن'});const challengeId=crypto.randomBytes(24).toString('base64url');s.phoneChallenges=(s.phoneChallenges||[]).filter(x=>x.expiresAt>new Date());s.phoneChallenges.push({challengeId,expiresAt:new Date(Date.now()+2*60*1000)});await s.save();const url=`${ORIGIN}/developer-phone.html#approve=${challengeId}&user=${req.user._id}`;res.json({ok:true,challengeId,qr:await QRCode.toDataURL(url,{width:280,margin:1}),expiresIn:120});});
router.post('/phone/approve',async(req,res)=>{const s=await DeveloperMfa.findOne({user:req.body.user});if(!s||!await bcrypt.compare(String(req.body.secret||''),s.phoneSecretHash||''))return res.status(401).json({ok:false,message:'هذا الهاتف غير مقترن'});const c=s.phoneChallenges.find(x=>x.challengeId===req.body.challengeId&&x.expiresAt>new Date());if(!c)return res.status(410).json({ok:false,message:'انتهت صلاحية رمز الدخول'});c.approved=true;await s.save();res.json({ok:true,message:'تمت الموافقة على الدخول'});});
router.post('/phone/poll',preAuth,async(req,res)=>{const s=await security(req.user),c=s.phoneChallenges.find(x=>x.challengeId===req.body.challengeId&&x.expiresAt>new Date());if(!c)return res.status(410).json({ok:false,message:'انتهت صلاحية رمز الدخول'});if(!c.approved)return res.json({ok:true,approved:false});s.phoneChallenges=s.phoneChallenges.filter(x=>x.challengeId!==c.challengeId);await s.save();res.json({ok:true,approved:true,token:fullToken(req.user),user:{id:req.user._id,fullName:req.user.fullName,username:req.user.username,role:req.user.role}});});
router.post('/fido/register-options',preAuth,async(req,res)=>{const s=await security(req.user),options=await generateRegistrationOptions({rpName:'شنو منو تك تك',rpID:RPID,userName:req.user.username,userDisplayName:req.user.fullName,attestationType:'none',excludeCredentials:s.credentials.map(c=>({id:c.id,transports:c.transports})),authenticatorSelection:{residentKey:'preferred',userVerification:'required'}});s.registrationChallenge=options.challenge;await s.save();res.json({ok:true,options});});
router.post('/fido/register-verify',preAuth,async(req,res)=>{try{const s=await security(req.user),v=await verifyRegistrationResponse({response:req.body.response,expectedChallenge:s.registrationChallenge,expectedOrigin:ORIGIN,expectedRPID:RPID,requireUserVerification:true});if(!v.verified)return res.status(400).json({ok:false,message:'لم يتم تسجيل المفتاح'});const c=v.registrationInfo.credential;s.credentials.push({id:c.id,publicKey:Buffer.from(c.publicKey).toString('base64'),counter:c.counter,transports:c.transports||req.body.response.response?.transports||[],deviceType:v.registrationInfo.credentialDeviceType,backedUp:v.registrationInfo.credentialBackedUp});s.registrationChallenge='';await s.save();res.json({ok:true,message:'تم تسجيل مفتاح FIDO'});}catch(e){res.status(400).json({ok:false,message:'تعذر تسجيل مفتاح FIDO: '+e.message});}});
router.post('/fido/auth-options',preAuth,async(req,res)=>{const s=await security(req.user);if(!s.credentials.length)return res.status(409).json({ok:false,message:'لا يوجد مفتاح FIDO مسجل'});const options=await generateAuthenticationOptions({rpID:RPID,userVerification:'required',allowCredentials:s.credentials.map(c=>({id:c.id,transports:c.transports}))});s.authenticationChallenge=options.challenge;await s.save();res.json({ok:true,options});});
router.post('/fido/auth-verify',preAuth,async(req,res)=>{try{const s=await security(req.user),c=s.credentials.find(x=>x.id===req.body.response.id);if(!c)return res.status(404).json({ok:false,message:'المفتاح غير مسجل'});const v=await verifyAuthenticationResponse({response:req.body.response,expectedChallenge:s.authenticationChallenge,expectedOrigin:ORIGIN,expectedRPID:RPID,credential:{id:c.id,publicKey:Buffer.from(c.publicKey,'base64'),counter:c.counter,transports:c.transports},requireUserVerification:true});if(!v.verified)return res.status(401).json({ok:false,message:'فشل تحقق المفتاح'});c.counter=v.authenticationInfo.newCounter;s.authenticationChallenge='';await s.save();res.json({ok:true,token:fullToken(req.user),user:{id:req.user._id,fullName:req.user.fullName,username:req.user.username,role:req.user.role}});}catch(e){res.status(400).json({ok:false,message:'تعذر التحقق من مفتاح FIDO: '+e.message});}});
module.exports=router;
