const express=require('express');
const mongoose=require('mongoose');
const {requireAuth}=require('../middleware/auth');
const GameRoom=require('../models/GameRoom');
const User=require('../models/User');
const {blocked}=require('./friends.routes');
const router=express.Router();router.use(requireAuth);
async function room(id){return mongoose.isValidObjectId(id)?GameRoom.findById(id):GameRoom.findOne({roomCode:String(id),isActive:{$ne:false}});}
function owner(r,u){return r&&String(r.owner)===String(u._id);}
function emit(req,r){const io=req.app.get('io');if(io)io.emit('game:room-updated',{roomId:String(r._id),roomCode:r.roomCode});}
router.patch('/:id/match-settings',async(req,res)=>{const r=await room(req.params.id);if(!owner(r,req.user))return res.status(403).json({ok:false,message:'مالك الغرفة فقط'});const mode=req.body.teamMode;if(mode==='2v2'){if(!['domino','cards'].includes(r.gameType))return res.status(400).json({ok:false,message:'اللعب 2 ضد 2 متاح للدومنة والورق'});r.teamMode='2v2';r.maxPlayers=4;}else if(mode==='solo')r.teamMode='solo';if(Number(req.body.scoreTarget)>0)r.scoreTarget=Math.min(9999,Number(req.body.scoreTarget));await r.save();emit(req,r);res.json({ok:true,teamMode:r.teamMode,maxPlayers:r.maxPlayers,scoreTarget:r.scoreTarget});});
router.post('/:id/score',async(req,res)=>{const r=await room(req.params.id);if(!owner(r,req.user))return res.status(403).json({ok:false,message:'مالك الغرفة فقط يعدل النقاط'});const team=req.body.team==='B'?'B':'A',delta=Math.max(-999,Math.min(999,Number(req.body.delta)||1));const scores=r.gameState.teamScores||new Map();scores.set(team,Math.max(0,Number(scores.get(team)||0)+delta));r.gameState.teamScores=scores;r.gameState.updatedAt=new Date();await r.save();emit(req,r);res.json({ok:true,teamScores:Object.fromEntries(scores)});});
router.post('/:id/save',async(req,res)=>{const r=await room(req.params.id);if(!r||!r.players.some(x=>String(x)===String(req.user._id)))return res.status(403).json({ok:false,message:'اللاعبون فقط يستطيعون حفظ المباراة'});r.savedAt=new Date();await r.save();res.json({ok:true,savedAt:r.savedAt,message:'تم حفظ حالة المباراة'});});
router.get('/:id/players',async(req,res)=>{const r=await room(req.params.id);if(!r)return res.status(404).json({ok:false,message:'الغرفة غير موجودة'});const q=String(req.query.q||'').trim(),rx=q?new RegExp(q.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'iu'):null;const query={status:'active',_id:{$ne:req.user._id,$nin:r.players}};if(rx)query.$or=[{username:rx},{fullName:rx},{displayName:rx}];const users=await User.find(query).select('username fullName displayName profile blockedUsers').limit(30);res.json({ok:true,users:users.filter(u=>!blocked(req.user,u)).map(u=>({id:u._id,username:u.username,fullName:u.displayName||u.fullName,avatarUrl:u.profile?.avatarUrl||''}))});});
router.post('/:id/request-player',async(req,res)=>{const r=await room(req.params.id);if(!r||!r.players.some(x=>String(x)===String(req.user._id)))return res.status(403).json({ok:false,message:'يجب أن تكون لاعباً في الغرفة'});if(r.players.length>=r.maxPlayers)return res.status(409).json({ok:false,message:'الغرفة مكتملة'});const target=await User.findById(req.body.userId).select('_id username fullName displayName blockedUsers');if(!target||blocked(req.user,target))return res.status(404).json({ok:false,message:'اللاعب غير متاح'});const io=req.app.get('io');if(io)io.to(`user:${target._id}`).emit('game:player-request',{roomId:String(r._id),roomCode:r.roomCode,roomName:r.name,gameType:r.gameType,from:{id:req.user._id,name:req.user.displayName||req.user.fullName}});res.json({ok:true,message:'تم إرسال طلب اللعب'});});
module.exports=router;