const express=require('express');
const mongoose=require('mongoose');
const {requireAuth}=require('../middleware/auth');
const GameRoom=require('../models/GameRoom');
const User=require('../models/User');
const {blocked}=require('./friends.routes');
const router=express.Router();
router.use(requireAuth);
async function room(id){return mongoose.isValidObjectId(id)?GameRoom.findById(id):GameRoom.findOne({roomCode:String(id),isActive:{$ne:false}});}
function owner(r,u){return r&&String(r.owner)===String(u._id);}
function isPlayer(r,u){return r&&(r.players||[]).some(x=>String(x)===String(u._id));}
function emit(req,r,event='game:room-updated',extra={}){const io=req.app.get('io');if(io)io.emit(event,{roomId:String(r._id),roomCode:r.roomCode,...extra});}
function nextPlayer(r,current){const players=(r.players||[]).map(String);const i=players.indexOf(String(current));return players[(i+1)%players.length];}
function allTiles(){const out=[];for(let a=0;a<=6;a++)for(let b=a;b<=6;b++)out.push({id:`${a}-${b}`,a,b});return out;}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function pipTotal(hand){return (hand||[]).reduce((s,t)=>s+Number(t.a||0)+Number(t.b||0),0);}
function legalOn(chain,tile){if(!chain?.length)return true;const left=chain[0].a,right=chain[chain.length-1].b;return tile.a===left||tile.b===left||tile.a===right||tile.b===right;}
function orientForSide(chain,tile,side){if(!chain.length)return {...tile};if(side==='left'){const edge=chain[0].a;if(tile.b===edge)return {...tile};if(tile.a===edge)return {id:tile.id,a:tile.b,b:tile.a};return null;}const edge=chain[chain.length-1].b;if(tile.a===edge)return {...tile};if(tile.b===edge)return {id:tile.id,a:tile.b,b:tile.a};return null;}
function publicDomino(r,u){const e=r.gameState?.engine||{};const uid=String(u._id);const hand=e.hands?.[uid]||[];const counts={};for(const pid of (r.players||[]).map(String))counts[pid]=(e.hands?.[pid]||[]).length;return{initialized:Boolean(e.initialized),status:r.gameState?.status||'waiting',turn:r.gameState?.turn?String(r.gameState.turn):null,chain:e.chain||[],myHand:hand,handCounts:counts,boneyardCount:(e.boneyard||[]).length,passCount:e.passCount||0,winner:e.winner||null,reason:e.finishReason||null,moveCount:r.gameState?.moveCount||0};}
function finishIfNeeded(r,lastPlayer){const e=r.gameState.engine;if((e.hands?.[String(lastPlayer)]||[]).length===0){r.gameState.status='finished';e.winner=String(lastPlayer);e.finishReason='empty-hand';return true;}const playerCount=(r.players||[]).length;if((e.passCount||0)>=playerCount){let winner=null,best=Infinity;for(const pid of r.players.map(String)){const total=pipTotal(e.hands?.[pid]);if(total<best){best=total;winner=pid;}}r.gameState.status='finished';e.winner=winner;e.finishReason='blocked';return true;}return false;}
router.get('/:id/state',async(req,res)=>{const r=await room(req.params.id);if(!r)return res.status(404).json({ok:false,message:'الغرفة غير موجودة'});res.json({ok:true,teamMode:r.teamMode||'solo',scoreTarget:r.scoreTarget||100,teamScores:Object.fromEntries(r.gameState?.teamScores||[]),savedAt:r.savedAt||null});});
router.patch('/:id/match-settings',async(req,res)=>{const r=await room(req.params.id);if(!owner(r,req.user))return res.status(403).json({ok:false,message:'مالك الغرفة فقط'});const mode=req.body.teamMode;if(mode==='2v2'){if(!['domino','cards'].includes(r.gameType))return res.status(400).json({ok:false,message:'اللعب 2 ضد 2 متاح للدومنة والورق'});r.teamMode='2v2';r.maxPlayers=4;}else if(mode==='solo')r.teamMode='solo';if(Number(req.body.scoreTarget)>0)r.scoreTarget=Math.min(9999,Number(req.body.scoreTarget));await r.save();emit(req,r);res.json({ok:true,teamMode:r.teamMode,maxPlayers:r.maxPlayers,scoreTarget:r.scoreTarget});});
router.post('/:id/score',async(req,res)=>{const r=await room(req.params.id);if(!owner(r,req.user))return res.status(403).json({ok:false,message:'مالك الغرفة فقط يعدل النقاط'});const team=req.body.team==='B'?'B':'A',delta=Math.max(-999,Math.min(999,Number(req.body.delta)||1));const scores=r.gameState.teamScores||new Map();scores.set(team,Math.max(0,Number(scores.get(team)||0)+delta));r.gameState.teamScores=scores;r.gameState.updatedAt=new Date();await r.save();emit(req,r);res.json({ok:true,teamScores:Object.fromEntries(scores)});});
router.post('/:id/save',async(req,res)=>{const r=await room(req.params.id);if(!r||!isPlayer(r,req.user))return res.status(403).json({ok:false,message:'اللاعبون فقط يستطيعون حفظ المباراة'});r.savedAt=new Date();await r.save();res.json({ok:true,savedAt:r.savedAt,message:'تم حفظ حالة المباراة'});});
router.get('/:id/players',async(req,res)=>{const r=await room(req.params.id);if(!r)return res.status(404).json({ok:false,message:'الغرفة غير موجودة'});const q=String(req.query.q||'').trim(),rx=q?new RegExp(q.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'iu'):null;const query={status:'active',_id:{$ne:req.user._id,$nin:r.players}};if(rx)query.$or=[{username:rx},{fullName:rx},{displayName:rx}];const users=await User.find(query).select('username fullName displayName profile blockedUsers').limit(30);res.json({ok:true,users:users.filter(u=>!blocked(req.user,u)).map(u=>({id:u._id,username:u.username,fullName:u.displayName||u.fullName,avatarUrl:u.profile?.avatarUrl||''}))});});
router.post('/:id/request-player',async(req,res)=>{const r=await room(req.params.id);if(!r||!isPlayer(r,req.user))return res.status(403).json({ok:false,message:'يجب أن تكون لاعباً في الغرفة'});if(r.players.length>=r.maxPlayers)return res.status(409).json({ok:false,message:'الغرفة مكتملة'});const target=await User.findById(req.body.userId).select('_id username fullName displayName blockedUsers');if(!target||blocked(req.user,target))return res.status(404).json({ok:false,message:'اللاعب غير متاح'});const io=req.app.get('io');if(io)io.to(`user:${target._id}`).emit('game:player-request',{roomId:String(r._id),roomCode:r.roomCode,roomName:r.name,gameType:r.gameType,from:{id:req.user._id,name:req.user.displayName||req.user.fullName}});res.json({ok:true,message:'تم إرسال طلب اللعب',target:{id:target._id,name:target.displayName||target.fullName||target.username}});});
router.post('/:id/domino/start',async(req,res)=>{const r=await room(req.params.id);if(!r)return res.status(404).json({ok:false,message:'الغرفة غير موجودة'});if(r.gameType!=='domino')return res.status(400).json({ok:false,message:'هذه ليست غرفة دومنة'});if(!owner(r,req.user))return res.status(403).json({ok:false,message:'مالك الغرفة فقط يبدأ الدومنة'});if((r.players||[]).length!==r.maxPlayers)return res.status(409).json({ok:false,message:`يجب اكتمال ${r.maxPlayers} لاعبين قبل البدء`});const deck=shuffle(allTiles());const hands={};for(const pid of r.players.map(String))hands[pid]=deck.splice(0,7);r.gameState.engine={type:'domino',initialized:true,hands,boneyard:deck,chain:[],passCount:0,winner:null,finishReason:null};r.gameState.status='active';r.gameState.turn=r.players[0];r.gameState.board=[];r.gameState.moveCount=0;r.gameState.updatedAt=new Date();r.markModified('gameState.engine');await r.save();emit(req,r,'game:domino-updated');res.json({ok:true,domino:publicDomino(r,req.user)});});
router.get('/:id/domino/state',async(req,res)=>{const r=await room(req.params.id);if(!r)return res.status(404).json({ok:false,message:'الغرفة غير موجودة'});if(r.gameType!=='domino')return res.status(400).json({ok:false,message:'هذه ليست غرفة دومنة'});if(!isPlayer(r,req.user))return res.status(403).json({ok:false,message:'اللاعبون فقط يرون أحجارهم'});res.json({ok:true,domino:publicDomino(r,req.user)});});
router.post('/:id/domino/play',async(req,res)=>{const r=await room(req.params.id);if(!r)return res.status(404).json({ok:false,message:'الغرفة غير موجودة'});if(r.gameType!=='domino'||!r.gameState?.engine?.initialized)return res.status(409).json({ok:false,message:'الدومنة لم تبدأ بعد'});if(!isPlayer(r,req.user))return res.status(403).json({ok:false,message:'أنت لست لاعباً'});if(r.gameState.status!=='active')return res.status(409).json({ok:false,message:'المباراة ليست نشطة'});if(String(r.gameState.turn)!==String(req.user._id))return res.status(409).json({ok:false,message:'ليس دورك الآن'});const e=r.gameState.engine,uid=String(req.user._id),hand=e.hands?.[uid]||[],idx=hand.findIndex(t=>t.id===String(req.body.tileId));if(idx<0)return res.status(400).json({ok:false,message:'هذا الحجر ليس بيدك'});const tile=hand[idx],side=req.body.side==='left'?'left':'right';if(!legalOn(e.chain,tile))return res.status(409).json({ok:false,message:'هذا الحجر لا يطابق طرفي السلسلة'});let placed;if(!e.chain.length)placed={...tile};else placed=orientForSide(e.chain,tile,side);if(!placed){const other=side==='left'?'right':'left';placed=orientForSide(e.chain,tile,other);if(!placed)return res.status(409).json({ok:false,message:'اختر الطرف المناسب لهذا الحجر'});}hand.splice(idx,1);e.hands[uid]=hand;if(side==='left'&&e.chain.length)e.chain.unshift(placed);else e.chain.push(placed);e.passCount=0;r.gameState.board=e.chain;r.gameState.moveCount=Number(r.gameState.moveCount||0)+1;if(!finishIfNeeded(r,uid))r.gameState.turn=nextPlayer(r,uid);r.gameState.updatedAt=new Date();r.markModified('gameState.engine');r.markModified('gameState.board');await r.save();emit(req,r,'game:domino-updated',{playerId:uid});res.json({ok:true,domino:publicDomino(r,req.user)});});
router.post('/:id/domino/pass',async(req,res)=>{const r=await room(req.params.id);if(!r||r.gameType!=='domino'||!r.gameState?.engine?.initialized)return res.status(409).json({ok:false,message:'الدومنة لم تبدأ بعد'});if(String(r.gameState.turn)!==String(req.user._id))return res.status(409).json({ok:false,message:'ليس دورك الآن'});const e=r.gameState.engine,uid=String(req.user._id),hand=e.hands?.[uid]||[];if(hand.some(t=>legalOn(e.chain,t)))return res.status(409).json({ok:false,message:'لديك حجر صالح ولا يمكنك التمرير'});if((e.boneyard||[]).length){hand.push(e.boneyard.pop());e.hands[uid]=hand;r.markModified('gameState.engine');await r.save();emit(req,r,'game:domino-updated',{playerId:uid,drew:true});return res.json({ok:true,drew:true,message:'سحبت حجراً من المخزن',domino:publicDomino(r,req.user)});}e.passCount=Number(e.passCount||0)+1;if(!finishIfNeeded(r,uid))r.gameState.turn=nextPlayer(r,uid);r.gameState.moveCount=Number(r.gameState.moveCount||0)+1;r.gameState.updatedAt=new Date();r.markModified('gameState.engine');await r.save();emit(req,r,'game:domino-updated',{playerId:uid,passed:true});res.json({ok:true,passed:true,message:'تم تمرير الدور',domino:publicDomino(r,req.user)});});
module.exports=router;
