const express=require('express');
const path=require('path');
const {requireAuth}=require('../middleware/auth');
const mediaStorage=require('../services/media-storage');
const Reel=require('../models/Reel');
const Post=require('../models/Post');
const {normalizeVisibility,createPublishNotifications}=require('../lib/social-audience');
const router=express.Router();
const MAX=1024*1024*1024;
router.use(requireAuth);
const allowed=new Set(['.jpg','.jpeg','.png','.webp','.gif','.mp4','.m4v','.mov','.webm','.ogv','.ogg','.3gp','.mkv','.avi','.mpeg','.mpg','.ts','.flv','.wmv','.mp3','.m4a','.aac','.wav','.flac','.opus','.oga','.amr']);
function kind(mime,name){mime=String(mime||'').toLowerCase();if(mime.startsWith('image/'))return'image';if(mime.startsWith('audio/'))return'audio';if(mime.startsWith('video/'))return'video';return ['.mp3','.m4a','.aac','.wav','.flac','.opus','.oga','.amr'].includes(path.extname(String(name)).toLowerCase())?'audio':'video';}
function userView(u){return{id:u._id,fullName:u.displayName||u.fullName,username:u.username,avatarUrl:u.profile?.avatarUrl||''};}
router.post('/sign',async(req,res)=>{try{const name=String(req.body.name||''),mime=String(req.body.mime||'application/octet-stream'),size=Number(req.body.size||0),category=String(req.body.category||'');if(!mediaStorage.configured())throw Error('Cloudflare R2 غير مهيأ');if(!['posts','reels'].includes(category)||!allowed.has(path.extname(name).toLowerCase()))throw Error('نوع الملف غير مدعوم');if(!(size>0&&size<=MAX))throw Error('حجم الملف غير صالح أو أكبر من 1 غيغابايت');const key=mediaStorage.directKey(category,name);res.json({ok:true,...mediaStorage.presignPut({key,expires:1800}),mediaType:kind(mime,name),mimeType:mime,size});}catch(e){res.status(400).json({ok:false,message:e.message});}});
async function media(body,category){const key=String(body.storageKey||'');if(!key.startsWith(category+'/'))throw Error('مفتاح الميديا غير صالح');const h=await mediaStorage.headObject(key);if(!h)throw Error('لم يكتمل رفع الملف إلى Cloudflare');if(Number(body.size||0)&&h.size&&Number(body.size)!==h.size)throw Error('حجم الملف غير مطابق');return{url:String(process.env.MEDIA_CDN_BASE_URL).replace(/\/+$/,'')+'/'+key.split('/').map(encodeURIComponent).join('/'),fallbackUrl:'',storageKey:key,storage:'r2',type:kind(body.mimeType,body.name),mimeType:String(body.mimeType||h.contentType||''),size:h.size||Number(body.size||0)};}
router.post('/reels/finalize',async(req,res)=>{try{const text=String(req.body.text||'').trim(),visibility=normalizeVisibility(req.body.visibility),m=await media(req.body.media||{},'reels');const reel=await Reel.create({author:req.user._id,text,media:[m],visibility,likes:[],comments:[],savedBy:[]});await reel.populate('author','fullName displayName username profile');await createPublishNotifications({authorId:req.user._id,type:'reel',targetId:reel._id,visibility,text:`${req.user.displayName||req.user.fullName||'صديقك'} نشر ريل جديداً`}).catch(()=>{});res.status(201).json({ok:true,reel:{id:reel._id,author:userView(reel.author),text:reel.text,media:reel.media,visibility:reel.visibility,likes:0,liked:false,commentsCount:0,saved:false,canDelete:true,createdAt:reel.createdAt}});}catch(e){res.status(400).json({ok:false,message:e.message});}});
router.post('/posts/finalize',async(req,res)=>{try{const text=String(req.body.text||'').trim();if(text.length>5000)throw Error('المنشور طويل جداً');const visibility=normalizeVisibility(req.body.visibility),m=await media(req.body.media||{},'posts');const post=await Post.create({author:req.user._id,text,media:[m],type:'post',visibility,adStatus:'not_ad'});await post.populate('author','fullName displayName username profile');await createPublishNotifications({authorId:req.user._id,type:'post',targetId:post._id,visibility,text:`${req.user.displayName||req.user.fullName||'صديقك'} نشر منشوراً جديداً`}).catch(()=>{});res.status(201).json({ok:true,message:'تم النشر',post:{id:post._id,author:userView(post.author),text:post.text,media:post.media,type:'post',visibility:post.visibility,adStatus:'not_ad',likesCount:0,liked:false,commentsCount:0,createdAt:post.createdAt,updatedAt:post.updatedAt,canEdit:true,canDelete:true}});}catch(e){res.status(400).json({ok:false,message:e.message});}});
module.exports=router;
