const express=require('express');
const {requireAuth}=require('../middleware/auth');
const mediaStorage=require('../services/media-storage');
const mediaRouter=require('../services/media-router');
const Reel=require('../models/Reel');
const Post=require('../models/Post');
const {normalizeVisibility,createPublishNotifications}=require('../lib/social-audience');
const router=express.Router();
router.use(requireAuth);
function kind(mime,name){return mediaRouter.classify({mime,name}).type;}
function userView(u){return{id:u._id,fullName:u.displayName||u.fullName,username:u.username,avatarUrl:u.profile?.avatarUrl||''};}
router.post('/sign',async(req,res)=>{try{const name=String(req.body.name||''),mime=String(req.body.mime||'application/octet-stream'),size=Number(req.body.size||0),category=String(req.body.category||'');if(!mediaStorage.configured())throw Error('Cloudflare R2 غير مهيأ');const decision=mediaRouter.route({name,mime,size,category,userId:req.user._id});const key=mediaStorage.directKey(decision.route,name);res.json({ok:true,...mediaStorage.presignPut({key,expires:1800}),mediaType:decision.type,mimeType:decision.mime,size,route:decision.route,processing:decision.processing,policy:decision.policy});}catch(e){res.status(400).json({ok:false,message:e.message});}});
async function media(body,category){const key=String(body.storageKey||'');if(!key.startsWith(category+'/'))throw Error('مفتاح الميديا غير صالح');const h=await mediaStorage.headObject(key);if(!h)throw Error('لم يكتمل رفع الملف إلى Cloudflare');if(Number(body.size||0)&&h.size&&Number(body.size)!==h.size)throw Error('حجم الملف غير مطابق');return{url:String(process.env.MEDIA_CDN_BASE_URL).replace(/\/+$/,'')+'/'+key.split('/').map(encodeURIComponent).join('/'),fallbackUrl:'',storageKey:key,storage:'r2',type:kind(body.mimeType||h.contentType,body.name||key),mimeType:String(body.mimeType||h.contentType||''),size:h.size||Number(body.size||0)};}
router.post('/reels/finalize',async(req,res)=>{try{const text=String(req.body.text||'').trim(),visibility=normalizeVisibility(req.body.visibility),m=await media(req.body.media||{},'reels');const reel=await Reel.create({author:req.user._id,text,media:[m],visibility,likes:[],comments:[],savedBy:[]});await reel.populate('author','fullName displayName username profile');await createPublishNotifications({authorId:req.user._id,type:'reel',targetId:reel._id,visibility,text:`${req.user.displayName||req.user.fullName||'صديقك'} نشر ريل جديداً`}).catch(()=>{});res.status(201).json({ok:true,reel:{id:reel._id,author:userView(reel.author),text:reel.text,media:reel.media,visibility:reel.visibility,likes:0,liked:false,commentsCount:0,saved:false,canDelete:true,createdAt:reel.createdAt}});}catch(e){res.status(400).json({ok:false,message:e.message});}});
router.post('/posts/finalize',async(req,res)=>{try{const text=String(req.body.text||'').trim();if(text.length>5000)throw Error('المنشور طويل جداً');const visibility=normalizeVisibility(req.body.visibility),m=await media(req.body.media||{},'posts');const post=await Post.create({author:req.user._id,text,media:[m],type:'post',visibility,adStatus:'not_ad'});await post.populate('author','fullName displayName username profile');await createPublishNotifications({authorId:req.user._id,type:'post',targetId:post._id,visibility,text:`${req.user.displayName||req.user.fullName||'صديقك'} نشر منشوراً جديداً`}).catch(()=>{});res.status(201).json({ok:true,message:'تم النشر',post:{id:post._id,author:userView(post.author),text:post.text,media:post.media,type:'post',visibility:post.visibility,adStatus:'not_ad',likesCount:0,liked:false,commentsCount:0,createdAt:post.createdAt,updatedAt:post.updatedAt,canEdit:true,canDelete:true}});}catch(e){res.status(400).json({ok:false,message:e.message});}});
module.exports=router;
