const express=require('express');
const multer=require('multer');
const path=require('path');
const fs=require('fs');
const {execFile}=require('child_process');
const {promisify}=require('util');
const {requireAuth}=require('../middleware/auth');
const Reel=require('../models/Reel');
const {normalizeVisibility,friendIds,followingIds,createPublishNotifications}=require('../lib/social-audience');
const router=express.Router(),run=promisify(execFile);
const uploadDir=path.resolve(__dirname,'../../../uploads/reels');fs.mkdirSync(uploadDir,{recursive:true});
const MAX_REEL_BYTES=1024*1024*1024;
const types=new Map([
 ['video/mp4','.mp4'],['video/x-m4v','.m4v'],['video/webm','.webm'],['video/quicktime','.mov'],['video/ogg','.ogv'],['video/3gpp','.3gp'],['video/3gpp2','.3g2'],['video/x-matroska','.mkv'],['video/x-msvideo','.avi'],['video/mpeg','.mpeg'],['video/mp2t','.ts'],['video/x-flv','.flv'],['video/x-ms-wmv','.wmv'],['video/x-ms-asf','.asf'],['video/x-f4v','.f4v'],
 ['audio/mpeg','.mp3'],['audio/mp3','.mp3'],['audio/mp4','.m4a'],['audio/x-m4a','.m4a'],['audio/aac','.aac'],['audio/wav','.wav'],['audio/x-wav','.wav'],['audio/flac','.flac'],['audio/x-flac','.flac'],['audio/ogg','.ogg'],['audio/opus','.opus'],['audio/amr','.amr'],['audio/webm','.webm']
]);
const allowedExt=new Set(['.mp4','.m4v','.mov','.webm','.ogv','.ogg','.3gp','.3g2','.mkv','.avi','.mpeg','.mpg','.ts','.mts','.m2ts','.flv','.wmv','.asf','.vob','.f4v','.ogm','.mp3','.m4a','.aac','.wav','.flac','.opus','.oga','.amr']);
function mediaExt(file){const ext=path.extname(file.originalname||'').toLowerCase();return types.get(file.mimetype)||(allowedExt.has(ext)?ext:'');}
const upload=multer({storage:multer.diskStorage({destination:(_r,_f,cb)=>cb(null,uploadDir),filename:(_r,f,cb)=>cb(null,`${Date.now()}-${Math.random().toString(36).slice(2)}${mediaExt(f)}`)}),limits:{fileSize:MAX_REEL_BYTES,files:1},fileFilter:(_r,f,cb)=>mediaExt(f)?cb(null,true):cb(new multer.MulterError('LIMIT_UNEXPECTED_FILE',f.fieldname))});
router.use(requireAuth);
function userView(u){return u?{id:u._id,fullName:u.displayName||u.fullName,username:u.username,avatarUrl:u.profile?.avatarUrl||''}:null;}
function ownerId(author){return author&&author._id?author._id:author;}
function view(r,u){return{id:r._id,author:userView(r.author),text:r.text,media:r.media,visibility:r.visibility,likes:r.likes?.length||0,liked:r.likes?.some(id=>String(id)===String(u._id))||false,commentsCount:r.comments?.length||0,saved:r.savedBy?.some(id=>String(id)===String(u._id))||false,canDelete:String(ownerId(r.author))===String(u._id),createdAt:r.createdAt};}
function removeFile(url){if(url&&url.startsWith('/uploads/reels/'))fs.unlink(path.join(uploadDir,path.basename(url)),()=>{});}
async function normalizeMedia(file){
 if(!file)return file;
 const isAudio=String(file.mimetype||'').startsWith('audio/')||['.mp3','.m4a','.aac','.wav','.flac','.opus','.oga','.amr'].includes(path.extname(file.originalname||'').toLowerCase());
 if((isAudio&&file.mimetype==='audio/mpeg')||(!isAudio&&['video/mp4','video/webm'].includes(file.mimetype)))return{...file,mediaType:isAudio?'audio':'video'};
 const output=file.path.replace(/\.[^.]+$/, '')+(isAudio?'-converted.mp3':'-converted.mp4');
 const args=isAudio?['-y','-i',file.path,'-vn','-c:a','libmp3lame','-b:a','192k',output]:['-y','-i',file.path,'-vf','scale=min(1280\\,iw):-2','-c:v','libx264','-preset','veryfast','-crf','24','-c:a','aac','-b:a','128k','-movflags','+faststart',output];
 try{await run('ffmpeg',args,{timeout:60*60*1000,maxBuffer:4*1024*1024});const stat=await fs.promises.stat(output);await fs.promises.unlink(file.path);return{...file,path:output,filename:path.basename(output),mimetype:isAudio?'audio/mpeg':'video/mp4',mediaType:isAudio?'audio':'video',size:stat.size};}catch(e){await fs.promises.unlink(output).catch(()=>{});throw Error('تعذر تحويل الملف. تأكد من سلامة الفيديو أو الصوت ومن توفر FFmpeg على الخادم.');}
}
router.get('/',async(req,res)=>{try{const[friends,following]=await Promise.all([friendIds(req.user._id),followingIds(req.user._id)]),combined=[...new Map([...friends,...following].map(id=>[String(id),id])).values()],reels=await Reel.find({active:true,$or:[{visibility:'everyone'},{author:req.user._id},{visibility:'friends',author:{$in:friends}},{visibility:'followers',author:{$in:following}},{visibility:'friends_followers',author:{$in:combined}}]}).populate('author','fullName displayName username profile').sort({createdAt:-1}).limit(30);res.json({ok:true,reels:reels.map(r=>view(r,req.user))});}catch(e){res.status(500).json({ok:false,message:e.message});}});
router.post('/',upload.single('media'),async(req,res)=>{let file=req.file;try{const text=String(req.body.text||'').trim();if(!text&&!file)return res.status(400).json({ok:false,message:'أضف نصاً أو فيديو أو ملفاً صوتياً'});file=await normalizeMedia(file);const visibility=normalizeVisibility(req.body.visibility),media=file?[{url:`/uploads/reels/${file.filename}`,type:file.mediaType||'video',mimeType:file.mimetype,size:file.size}]:[],reel=await Reel.create({author:req.user._id,text,media,visibility,likes:[],comments:[],savedBy:[]});await reel.populate('author','fullName displayName username profile');await createPublishNotifications({authorId:req.user._id,type:'reel',targetId:reel._id,visibility,text:`${req.user.displayName||req.user.fullName||'صديقك'} نشر ريل جديداً`}).catch(()=>{});res.status(201).json({ok:true,reel:view(reel,req.user)});}catch(e){if(file?.path)fs.unlink(file.path,()=>{});res.status(400).json({ok:false,message:e.message});}});
router.delete('/:id',async(req,res)=>{try{const reel=await Reel.findOne({_id:req.params.id,author:req.user._id});if(!reel)return res.status(404).json({ok:false,message:'الريل غير موجود أو لا تملك صلاحية حذفه'});for(const item of reel.media||[])removeFile(item.url);await Reel.deleteOne({_id:reel._id});res.json({ok:true,message:'تم حذف الريل'});}catch(e){res.status(500).json({ok:false,message:e.message});}});
router.post('/:id/like',async(req,res)=>{try{const reel=await Reel.findOne({_id:req.params.id,active:true});if(!reel)return res.status(404).json({ok:false,message:'الريل غير موجود'});const i=reel.likes.findIndex(id=>String(id)===String(req.user._id));if(i>=0)reel.likes.splice(i,1);else reel.likes.push(req.user._id);await reel.save();res.json({ok:true,liked:i<0,likesCount:reel.likes.length});}catch(e){res.status(500).json({ok:false,message:e.message});}});
router.post('/:id/save',async(req,res)=>{try{const reel=await Reel.findOne({_id:req.params.id,active:true});if(!reel)return res.status(404).json({ok:false,message:'الريل غير موجود'});const i=reel.savedBy.findIndex(id=>String(id)===String(req.user._id));if(i>=0)reel.savedBy.splice(i,1);else reel.savedBy.push(req.user._id);await reel.save();res.json({ok:true,saved:i<0});}catch(e){res.status(500).json({ok:false,message:e.message});}});
router.get('/:id/comments',async(req,res)=>{try{const reel=await Reel.findOne({_id:req.params.id,active:true}).populate('comments.author','fullName displayName username profile');if(!reel)return res.status(404).json({ok:false,message:'الريل غير موجود'});res.json({ok:true,comments:reel.comments.map(c=>({id:c._id,text:c.text,createdAt:c.createdAt,author:userView(c.author)}))});}catch(e){res.status(500).json({ok:false,message:e.message});}});
router.post('/:id/comments',async(req,res)=>{try{const text=String(req.body.text||'').trim();if(!text||text.length>2000)return res.status(400).json({ok:false,message:'التعليق غير صالح'});const reel=await Reel.findOne({_id:req.params.id,active:true});if(!reel)return res.status(404).json({ok:false,message:'الريل غير موجود'});reel.comments.push({author:req.user._id,text});await reel.save();const comment=reel.comments[reel.comments.length-1];res.status(201).json({ok:true,commentsCount:reel.comments.length,comment:{id:comment._id,text:comment.text,createdAt:comment.createdAt,author:userView(req.user)}});}catch(e){res.status(500).json({ok:false,message:e.message});}});
module.exports=router;
