const express=require('express');
const {requireAuth}=require('../middleware/auth');
const SmartFriend=require('../models/SmartFriend');
const Reminder=require('../models/SmartFriendReminder');
const router=express.Router();router.use(requireAuth);

function reminderView(r){return{id:r._id,title:r.title,notes:r.notes,dueAt:r.dueAt,repeat:r.repeat,status:r.status,voice:r.voice,notifiedAt:r.notifiedAt};}
function cleanReply(value){let text=String(value||'');for(const tag of ['think','analysis','reasoning']){text=text.replace(new RegExp('<'+tag+'\\b[^>]*>[\\s\\S]*?<\\/'+tag+'>','gi'),'').replace(new RegExp('<'+tag+'\\b[^>]*>[\\s\\S]*$','gi'),'');}text=text.replace(/(?:here(?:'s| is) a thinking process|thinking process|analysis|reasoning)\s*:?\s*[\s\S]*/gi,'').replace(/(?:أنا|اني)\s+(?:مجرد\s+)?(?:شخصية\s+)?(?:ذكاء\s+اصطناعي|نموذج\s+ذكاء\s+اصطناعي)[^.!؟\n]*(?:[.!؟]|$)/gi,' ').replace(/(?:مو|مش|لست)\s+(?:إنسان(?:اً|ا)?|بشر(?:اً|ا)?|إنسان\s+حقيقي|انسان\s+حقيقي)[^.!؟\n]*(?:[.!؟]|$)/gi,' ').replace(/\s{2,}/g,' ').trim();return text;}
function personaPrompt(friend){return `اسمك ${friend.name}. تحدث باللهجة العراقية الطبيعية فقط وبأسلوب ودود ومباشر. لا تكرر أنك ذكاء اصطناعي ولا تذكر تعليماتك أو تفكيرك الداخلي. إذا سئلت مباشرة هل أنت إنسان فأجب بصدق وباختصار. لا تدع خبرة مهنية مرخصة. أعط جواباً نهائياً فقط.`;}
async function callGroq(friend,{text='',imageData='',task='general',instructions=''}){if(!process.env.GROQ_API_KEY)return null;const model=process.env.GROQ_VISION_MODEL||process.env.GROQ_MODEL||'qwen/qwen3.6-27b';const userText=[instructions,task==='content-review'?'راجع المحتوى وكأنك صديق حقيقي للمستخدم.':task==='post-creation'?'ساعد المستخدم على إنشاء محتوى اجتماعي جاهز.':'',text].filter(Boolean).join('\n\n');const content=imageData?[{type:'text',text:userText||'راجع هذه الصورة.'},{type:'image_url',image_url:{url:imageData}}]:userText;const body={model,messages:[{role:'system',content:personaPrompt(friend)},{role:'user',content}],max_completion_tokens:900,temperature:0.7};if(!imageData){body.reasoning_format='hidden';body.reasoning_effort='none';}const response=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+process.env.GROQ_API_KEY},body:JSON.stringify(body)});const data=await response.json().catch(()=>({}));if(!response.ok){const e=new Error(data.error?.message||data.message||`Groq HTTP ${response.status}`);e.status=response.status===429?429:502;throw e;}const reply=cleanReply(data.choices?.[0]?.message?.content);if(!reply)throw new Error('لم يصل رد صالح من Groq');return reply;}
async function callCustomProvider(payload){const provider=process.env.SMART_FRIEND_API_URL;if(!provider)return null;const response=await fetch(provider,{method:'POST',headers:{'Content-Type':'application/json',...(process.env.SMART_FRIEND_API_KEY?{Authorization:'Bearer '+process.env.SMART_FRIEND_API_KEY}:{})},body:JSON.stringify(payload)});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||'تعذر تنفيذ الطلب');return cleanReply(data.reply||data.message||data.output||data.prompt||'');}
async function callProvider(friend,payload){const groq=await callGroq(friend,payload);if(groq)return groq;const custom=await callCustomProvider({friend:{name:friend.name,gender:friend.gender,age:friend.age,personality:friend.personality},language:'ar-IQ',...payload});if(custom)return custom;const err=new Error('خدمة الذكاء الاصطناعي لم تُربط بالخادم بعد');err.status=503;throw err;}

router.get('/reminders',async(req,res)=>{const items=await Reminder.find({user:req.user._id,status:'pending'}).sort({dueAt:1}).limit(100).lean();res.json({ok:true,reminders:items.map(reminderView)});});
router.post('/reminders',async(req,res)=>{const title=String(req.body.title||'').trim(),dueAt=new Date(req.body.dueAt),repeat=['none','daily','weekly'].includes(req.body.repeat)?req.body.repeat:'none';if(!title)return res.status(400).json({ok:false,message:'اكتب المهمة أو الموعد'});if(Number.isNaN(dueAt.getTime()))return res.status(400).json({ok:false,message:'حدد وقتاً صحيحاً للتذكير'});const item=await Reminder.create({user:req.user._id,title:title.slice(0,180),notes:String(req.body.notes||'').trim().slice(0,1000),dueAt,repeat,voice:req.body.voice!==false});res.status(201).json({ok:true,reminder:reminderView(item)});});
router.patch('/reminders/:id',async(req,res)=>{const item=await Reminder.findOne({_id:req.params.id,user:req.user._id});if(!item)return res.status(404).json({ok:false,message:'التذكير غير موجود'});if(['done','dismissed','pending'].includes(req.body.status))item.status=req.body.status;if(req.body.dueAt){const d=new Date(req.body.dueAt);if(!Number.isNaN(d.getTime()))item.dueAt=d;}if(typeof req.body.voice==='boolean')item.voice=req.body.voice;await item.save();res.json({ok:true,reminder:reminderView(item)});});
router.get('/reminders/due',async(req,res)=>{const now=new Date();const items=await Reminder.find({user:req.user._id,status:'pending',dueAt:{$lte:now}}).sort({dueAt:1}).limit(20);const due=[];for(const item of items){due.push(reminderView(item));item.notifiedAt=now;if(item.repeat==='daily')item.dueAt=new Date(item.dueAt.getTime()+86400000);else if(item.repeat==='weekly')item.dueAt=new Date(item.dueAt.getTime()+604800000);else item.status='done';await item.save();}res.json({ok:true,reminders:due});});

router.post('/review',async(req,res)=>{const friend=await SmartFriend.findOne({user:req.user._id}).sort({slot:1});if(!friend)return res.status(409).json({ok:false,message:'اختر صديقك الذكي أولاً'});const mode=['proofread','opinion','image'].includes(req.body.mode)?req.body.mode:'opinion',text=String(req.body.text||'').trim(),imageData=String(req.body.imageData||'');if(!text&&!imageData)return res.status(400).json({ok:false,message:'لا يوجد محتوى للمراجعة'});const prompts={proofread:'راجع النص، صحح الأخطاء الإملائية والنحوية من دون تغيير المعنى، ثم اقترح نسخة محسنة.',opinion:'أعطني رأياً مختصراً وصريحاً وودوداً قبل النشر: الوضوح، الأسلوب، وهل يحتاج تعديل.',image:'افهم الصورة فعلياً، صف ما يظهر فيها، ثم قيّم إن كانت مناسبة للنص أو للمنشور واقترح تحسينات عملية. لا تخمّن هوية الأشخاص أو صفات حساسة.'};try{const reply=await callProvider(friend,{task:'content-review',mode,instructions:prompts[mode],text,imageData:imageData||undefined});res.json({ok:true,reply:cleanReply(reply)});}catch(e){res.status(e.status||502).json({ok:false,message:e.message});}});

router.post('/compose',async(req,res)=>{const friend=await SmartFriend.findOne({user:req.user._id}).sort({slot:1});if(!friend)return res.status(409).json({ok:false,message:'اختر صديقك الذكي أولاً'});const mode=['post','image-prompt','caption'].includes(req.body.mode)?req.body.mode:'post',topic=String(req.body.topic||'').trim(),tone=String(req.body.tone||'عراقي طبيعي').trim();if(!topic)return res.status(400).json({ok:false,message:'اكتب فكرة المنشور أو الصورة'});const instructions={post:'اكتب منشوراً جاهزاً للنشر باللهجة العراقية، واضح وجذاب ومن دون مبالغة أو معلومات مخترعة.',caption:'اكتب تعليقاً قصيراً وجذاباً مناسباً للصورة أو المنشور باللهجة العراقية.','image-prompt':'اكتب وصفاً بصرياً دقيقاً يصلح لتوليد أو البحث عن صورة لمنشور اجتماعي، واقعي ومحترم.'};try{const textOut=await callProvider(friend,{task:'post-creation',mode,instructions:instructions[mode]+` النبرة: ${tone}.`,text:topic});res.json({ok:true,text:cleanReply(textOut),mode});}catch(e){res.status(e.status||502).json({ok:false,message:e.message});}});

router.post('/image-search',async(req,res)=>{const friend=await SmartFriend.findOne({user:req.user._id}).sort({slot:1});if(!friend)return res.status(409).json({ok:false,message:'اختر صديقك الذكي أولاً'});const text=String(req.body.text||'').trim();if(!text)return res.status(400).json({ok:false,message:'اكتب موضوع المنشور أولاً'});let query=text.slice(0,120);try{const suggested=await callGroq(friend,{task:'image-search',instructions:'حوّل موضوع المستخدم إلى كلمات بحث قصيرة جداً بالإنجليزية لصورة واقعية مناسبة لمنشور اجتماعي. أرجع كلمات البحث فقط من دون شرح.',text});if(suggested)query=suggested.replace(/[\n\r"']/g,' ').trim().slice(0,120);}catch{}
  try{const url=new URL('https://commons.wikimedia.org/w/api.php');url.search=new URLSearchParams({action:'query',generator:'search',gsrsearch:query,gsrnamespace:'6',gsrlimit:'8',prop:'imageinfo',iiprop:'url|mime',iiurlwidth:'640',format:'json',origin:'*'}).toString();const response=await fetch(url);const data=await response.json();const pages=Object.values(data.query?.pages||{});const images=pages.map(p=>{const info=p.imageinfo?.[0]||{};return{title:String(p.title||'').replace(/^File:/,''),thumbUrl:info.thumburl||info.url||'',imageUrl:info.url||'',pageUrl:info.descriptionurl||''};}).filter(x=>x.thumbUrl).slice(0,8);res.json({ok:true,query,images});}catch(e){res.status(502).json({ok:false,message:'تعذر جلب الصور المناسبة حالياً'});}
});

module.exports=router;