const express=require('express');
const {requireAuth}=require('../middleware/auth');
const SmartFriend=require('../models/SmartFriend');
const Reminder=require('../models/SmartFriendReminder');
const router=express.Router();router.use(requireAuth);
function reminderView(r){return{id:r._id,title:r.title,notes:r.notes,dueAt:r.dueAt,repeat:r.repeat,status:r.status,voice:r.voice,notifiedAt:r.notifiedAt};}
async function callProvider(payload){const provider=process.env.SMART_FRIEND_API_URL;if(!provider){const err=new Error('خدمة الذكاء الاصطناعي لم تُربط بالخادم بعد');err.status=503;throw err;}const response=await fetch(provider,{method:'POST',headers:{'Content-Type':'application/json',...(process.env.SMART_FRIEND_API_KEY?{Authorization:'Bearer '+process.env.SMART_FRIEND_API_KEY}:{})},body:JSON.stringify(payload)});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||'تعذر تنفيذ الطلب');return data;}
router.get('/reminders',async(req,res)=>{const items=await Reminder.find({user:req.user._id,status:'pending'}).sort({dueAt:1}).limit(100).lean();res.json({ok:true,reminders:items.map(reminderView)});});
router.post('/reminders',async(req,res)=>{const title=String(req.body.title||'').trim(),dueAt=new Date(req.body.dueAt),repeat=['none','daily','weekly'].includes(req.body.repeat)?req.body.repeat:'none';if(!title)return res.status(400).json({ok:false,message:'اكتب المهمة أو الموعد'});if(Number.isNaN(dueAt.getTime()))return res.status(400).json({ok:false,message:'حدد وقتاً صحيحاً للتذكير'});const item=await Reminder.create({user:req.user._id,title:title.slice(0,180),notes:String(req.body.notes||'').trim().slice(0,1000),dueAt,repeat,voice:req.body.voice!==false});res.status(201).json({ok:true,reminder:reminderView(item)});});
router.patch('/reminders/:id',async(req,res)=>{const item=await Reminder.findOne({_id:req.params.id,user:req.user._id});if(!item)return res.status(404).json({ok:false,message:'التذكير غير موجود'});if(['done','dismissed','pending'].includes(req.body.status))item.status=req.body.status;if(req.body.dueAt){const d=new Date(req.body.dueAt);if(!Number.isNaN(d.getTime()))item.dueAt=d;}if(typeof req.body.voice==='boolean')item.voice=req.body.voice;await item.save();res.json({ok:true,reminder:reminderView(item)});});
router.get('/reminders/due',async(req,res)=>{const now=new Date();const items=await Reminder.find({user:req.user._id,status:'pending',dueAt:{$lte:now}}).sort({dueAt:1}).limit(20);const due=[];for(const item of items){due.push(reminderView(item));item.notifiedAt=now;if(item.repeat==='daily')item.dueAt=new Date(item.dueAt.getTime()+86400000);else if(item.repeat==='weekly')item.dueAt=new Date(item.dueAt.getTime()+604800000);else item.status='done';await item.save();}res.json({ok:true,reminders:due});});
router.post('/review',async(req,res)=>{const friend=await SmartFriend.findOne({user:req.user._id});if(!friend)return res.status(409).json({ok:false,message:'اختر صديقك الذكي أولاً'});const mode=['proofread','opinion','image'].includes(req.body.mode)?req.body.mode:'opinion',text=String(req.body.text||'').trim(),imageData=String(req.body.imageData||'');if(!text&&!imageData)return res.status(400).json({ok:false,message:'لا يوجد محتوى للمراجعة'});const prompts={proofread:'راجع النص، صحح الأخطاء الإملائية والنحوية من دون تغيير المعنى، ثم اقترح نسخة محسنة.',opinion:'أعطني رأياً مختصراً وصريحاً وودوداً قبل النشر: الوضوح، الأسلوب، وهل يحتاج تعديل.',image:'راجع الصورة أو الصورة مع النص قبل النشر. اذكر جودة العرض واقترح تحسينات مناسبة من دون تخمين معلومات حساسة عن الأشخاص.'};try{const data=await callProvider({friend:{name:friend.name,gender:friend.gender,age:friend.age,personality:friend.personality},language:'ar-IQ',task:'content-review',mode,instructions:prompts[mode]+' تكلم باللهجة العراقية الطبيعية ووضح أنك صديق ذكي افتراضي.',text,imageData:imageData||undefined});const reply=String(data.reply||data.message||data.output||'').trim();if(!reply)throw Error('لم يصل رد صالح');res.json({ok:true,reply});}catch(e){res.status(e.status||502).json({ok:false,message:e.message});}});
router.post('/compose',async(req,res)=>{const friend=await SmartFriend.findOne({user:req.user._id});if(!friend)return res.status(409).json({ok:false,message:'اختر صديقك الذكي أولاً'});const mode=['post','image-prompt','caption'].includes(req.body.mode)?req.body.mode:'post',topic=String(req.body.topic||'').trim(),tone=String(req.body.tone||'عراقي طبيعي').trim();if(!topic)return res.status(400).json({ok:false,message:'اكتب فكرة المنشور أو الصورة'});const instructions={post:'اكتب منشوراً جاهزاً للنشر على شنو منو باللهجة العراقية، واضح وجذاب ومن دون مبالغة. لا تخترع حقائق.',caption:'اكتب تعليقاً قصيراً وجذاباً مناسباً للصورة أو المنشور باللهجة العراقية.', 'image-prompt':'اكتب وصفاً بصرياً دقيقاً يصلح لتوليد صورة لمنشور اجتماعي. اجعله محترماً وواقعياً ولا تتضمن هوية شخص حقيقي أو معلومات حساسة.'};try{const data=await callProvider({friend:{name:friend.name,gender:friend.gender,age:friend.age,personality:friend.personality},language:'ar-IQ',task:'post-creation',mode,topic,tone,instructions:instructions[mode]});const text=String(data.reply||data.message||data.output||data.prompt||'').trim();if(!text)throw Error('لم يصل محتوى صالح');res.json({ok:true,text,mode});}catch(e){res.status(e.status||502).json({ok:false,message:e.message});}});
module.exports=router;