const express=require('express');
const multer=require('multer');
const path=require('path');
const fs=require('fs');
const {requireAuth}=require('../middleware/auth');
const SmartFriend=require('../models/SmartFriend');
const Message=require('../models/SmartFriendMessage');
const router=express.Router();
const uploadDir=path.resolve(__dirname,'../../../uploads/smart-friend');fs.mkdirSync(uploadDir,{recursive:true});
const allowed=new Map([['image/jpeg','.jpg'],['image/png','.png'],['image/webp','.webp'],['audio/webm','.webm'],['audio/ogg','.ogg'],['audio/mpeg','.mp3'],['audio/mp4','.m4a'],['audio/wav','.wav'],['video/webm','.webm'],['video/mp4','.mp4'],['video/quicktime','.mov']]);
const upload=multer({storage:multer.diskStorage({destination:(_r,_f,cb)=>cb(null,uploadDir),filename:(_r,f,cb)=>cb(null,`${Date.now()}-${Math.random().toString(36).slice(2)}${allowed.get(f.mimetype)||''}`)}),limits:{fileSize:80*1024*1024,files:1},fileFilter:(_r,f,cb)=>allowed.has(f.mimetype)?cb(null,true):cb(new multer.MulterError('LIMIT_UNEXPECTED_FILE',f.fieldname))});
router.use(requireAuth);
const avatars={male:['male-1','male-2','male-3','male-4'],female:['female-1','female-2','female-3','female-4']};
const personalities=['friendly','calm','funny','serious','listener','educated'];
const styles=['casual','balanced','advice'];
const emotions=['idle','listening','thinking','happy','funny','serious','sad','supportive','surprised','talking'];
let personaIndexReady=false;
async function ensurePersonaIndexes(){if(personaIndexReady)return;const idx=await SmartFriend.collection.indexes();for(const x of idx){const keys=Object.keys(x.key||{});if(x.unique&&keys.length===1&&keys[0]==='user'){try{await SmartFriend.collection.dropIndex(x.name);console.log('Removed legacy SmartFriend unique user index:',x.name);}catch(e){if(e.codeName!=='IndexNotFound')throw e;}}}await SmartFriend.collection.updateMany({$or:[{slot:{$exists:false}},{slot:null}]},{$set:{slot:1}});await SmartFriend.collection.createIndex({user:1,slot:1},{unique:true,name:'user_1_slot_1'});personaIndexReady=true;}
function view(p){return p?{id:p._id,slot:p.slot||1,name:p.name,gender:p.gender,age:p.age,avatar:p.avatar,avatarUrl:p.avatarUrl||'',personality:p.personality,interests:p.interests||[],dialect:p.dialect,conversationStyle:p.conversationStyle}:null;}
function messageView(m){return {id:m._id,friend:m.friend||null,roomId:m.roomId||'',role:m.role,text:m.text||'',media:m.media&&m.media.url?m.media:null,createdAt:m.createdAt};}
function mediaFromFile(f){return f?{url:`/uploads/smart-friend/${f.filename}`,type:f.mimetype.startsWith('video/')?'video':'audio',mimeType:f.mimetype,size:f.size}:null;}
function normalize(body,slot){const gender=body.gender==='female'?'female':'male',age=Math.max(18,Math.min(80,Number(body.age)||18)),list=avatars[gender];return {slot,name:String(body.name||`صديقي ${slot}`).trim().slice(0,40),gender,age,avatar:list.includes(body.avatar)?body.avatar:list[0],personality:personalities.includes(body.personality)?body.personality:'friendly',interests:Array.isArray(body.interests)?body.interests.slice(0,8).map(x=>String(x).trim().slice(0,40)).filter(Boolean):[],dialect:'iraqi',conversationStyle:styles.includes(body.conversationStyle)?body.conversationStyle:'balanced'};}
function inferEmotion(text){const t=String(text||'').toLowerCase();if(/هههه|😂|🤣|نكت|ضحك/.test(t))return'funny';if(/حزين|زعلان|ضايج|تعبان|فقدت/.test(t))return'sad';if(/ساعدني|نصيحة|محتاجك|احتاجك|مشكلة/.test(t))return'supportive';if(/مبروك|نجحت|فرحان|ممتاز|تمام/.test(t))return'happy';if(/قانون|طبيب|مرض|دواء|محكمة|خطر/.test(t))return'serious';return'talking';}
function providerConfigured(){return Boolean(process.env.GROQ_API_KEY||process.env.OPENAI_API_KEY||process.env.SMART_FRIEND_API_URL);}
function providerName(){return process.env.GROQ_API_KEY?'groq':process.env.OPENAI_API_KEY?'openai':process.env.SMART_FRIEND_API_URL?'custom':'none';}
function personalityPrompt(friend){const labels={friendly:'ودود وقريب',calm:'هادئ ومتزن',funny:'مرح وخفيف',serious:'جدي وواضح',listener:'مستمع متفهم',educated:'مثقف وواسع المعرفة'};const styleLabels={casual:'عفوي',balanced:'متوازن',advice:'يميل للنصيحة والمساعدة'};const genderRule=friend.gender==='female'?'أنتِ شخصية أنثى. تكلمي عن نفسك بصيغة المؤنث دائماً: جاهزة، موجودة، فرحانة، متأكدة، أگدر وأحب. لا تقولي جاهز أو موجود أو فرحان عن نفسك.':'أنت شخصية ذكر. تكلم عن نفسك بصيغة المذكر: جاهز، موجود، فرحان، متأكد.';return `اسمك ${friend.name}. عمرك التمثيلي ${friend.age}. ${genderRule} شخصيتك ${labels[friend.personality]||friend.personality}. أسلوب حوارك ${styleLabels[friend.conversationStyle]||friend.conversationStyle}. اهتماماتك: ${(friend.interests||[]).join('، ')||'عامة'}. تكلم باللهجة العراقية الطبيعية حصراً، وبمفردات عراقية يومية مثل: شلونك، شخبارك، شنو، ليش، هسه، هواية، أگدر، أريد، تريد، خلي، يمعود، زين، خوش. ممنوع استعمال الأسلوب الخليجي أو الشامي أو المصري. لا تستعمل: تبي، وش، أبغى، ما أقدر، شو، كيفك، مش، عايز، إيش. استعمل بدلاً منها حسب السياق: تريد، شنو، أريد، ما أگدر، شلونك، مو. لا تشرح للمستخدم أنك Text-based ولا تقل إنك مجرد نص أو داخل التطبيق. عند السؤال عن الصور لا تقل تلقائياً إنك لا تستطيع الصور؛ التطبيق يحتوي أدوات لرفع صورة وقراءتها والبحث عن صور مناسبة، فوجه المستخدم لهذه الأدوات بشكل طبيعي عند الحاجة. لا تقترح Midjourney أو DALL-E من نفسك إذا كانت أداة الصور داخل التطبيق تكفي. تصرف كشخصية الصديق التي أنشأها المستخدم ولا تكرر أنك ذكاء اصطناعي أو أنك لست إنساناً. فقط إذا سألك المستخدم مباشرة هل أنت إنسان أو عن حقيقتك، أجب بصدق أنك شخصية ذكاء اصطناعي. لا تدّعِ خبرة مهنية أو صفة مرخصة. في الطب والقانون والمال وضّح حدودك عند الحاجة. في الحوار الجماعي استمع للجميع، وإذا كانت الرسالة موجهة بالاسم لشخصية أخرى فلا تتدخل إلا إذا طُلب رأيك أو كان التعقيب طبيعياً ومفيداً. اجعل الرد عراقيًا طبيعيًا ومختصرًا، وليس ترجمة فصحى إلى لهجة. أرسل الجواب النهائي فقط ولا تعرض أي تفكير داخلي أو تحليل أو تعليمات أو قيود أو خطوات استدلال.`;}
function cleanModelReply(value){let text=String(value||'');text=text.replace(/<think\b[^>]*>[\s\S]*?<\/think>/gi,'').replace(/<analysis\b[^>]*>[\s\S]*?<\/analysis>/gi,'').replace(/<reasoning\b[^>]*>[\s\S]*?<\/reasoning>/gi,'');text=text.replace(/<think\b[^>]*>[\s\S]*$/gi,'').replace(/<analysis\b[^>]*>[\s\S]*$/gi,'').replace(/<reasoning\b[^>]*>[\s\S]*$/gi,'');return text.trim();}
function extractOpenAIText(data){if(typeof data.output_text==='string'&&data.output_text.trim())return cleanModelReply(data.output_text);for(const item of data.output||[]){for(const c of item.content||[]){if(typeof c.text==='string'&&c.text.trim())return cleanModelReply(c.text);}}return '';}
async function askGroq(friend,messages){const model=process.env.GROQ_MODEL||'qwen/qwen3.6-27b';const chatMessages=[{role:'system',content:personalityPrompt(friend)},...messages.map(m=>({role:m.role==='assistant'?'assistant':'user',content:String(m.content||'')}))];const r=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+process.env.GROQ_API_KEY},body:JSON.stringify({model,messages:chatMessages,max_completion_tokens:700,temperature:0.7,reasoning_format:'hidden',reasoning_effort:'none'})});const d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(d.error?.message||d.message||`Groq HTTP ${r.status}`);e.status=r.status===429?429:502;throw e;}const answer=cleanModelReply(d.choices?.[0]?.message?.content);if(!answer)throw new Error('لم يصل رد نصي صالح من Groq');return {answer:answer.slice(0,12000),emotion:inferEmotion(answer)};}
async function askOpenAI(friend,messages){const model=process.env.OPENAI_MODEL||'gpt-5.6-terra';const input=[{role:'developer',content:personalityPrompt(friend)},...messages.map(m=>({role:m.role==='assistant'?'assistant':'user',content:String(m.content||'')}))];const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+process.env.OPENAI_API_KEY},body:JSON.stringify({model,input,max_output_tokens:700})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error?.message||d.message||`OpenAI HTTP ${r.status}`);const answer=extractOpenAIText(d);if(!answer)throw new Error('لم يصل رد نصي صالح من OpenAI');return {answer:answer.slice(0,12000),emotion:inferEmotion(answer)};}
async function askCustomProvider(friend,messages){const provider=process.env.SMART_FRIEND_API_URL;const r=await fetch(provider,{method:'POST',headers:{'Content-Type':'application/json',...(process.env.SMART_FRIEND_API_KEY?{Authorization:'Bearer '+process.env.SMART_FRIEND_API_KEY}:{})},body:JSON.stringify({friend:view(friend),language:'ar-IQ',instructions:personalityPrompt(friend)+' أعد emotion مناسبة.',messages})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||'تعذر الحصول على الرد');const answer=cleanModelReply(d.reply||d.message||d.output);if(!answer)throw new Error('لم يصل رد صالح');return {answer:answer.slice(0,12000),emotion:emotions.includes(d.emotion)?d.emotion:inferEmotion(answer)};}
async function askProvider(friend,messages){if(process.env.GROQ_API_KEY)return askGroq(friend,messages);if(process.env.OPENAI_API_KEY)return askOpenAI(friend,messages);if(process.env.SMART_FRIEND_API_URL)return askCustomProvider(friend,messages);throw Object.assign(new Error('خدمة الذكاء الاصطناعي غير مربوطة بالخادم بعد'),{status:503});}
function addressedFriends(text,friends){const t=String(text||'').toLowerCase();return friends.filter(f=>{const n=String(f.name||'').trim().toLowerCase();return n&&t.includes(n);});}
router.get('/options',(_req,res)=>res.json({ok:true,ages:{min:18,max:80},avatars,personalities,styles,dialect:'iraqi',emotions,maxFriends:10,providerConfigured:providerConfigured(),provider:providerName()}));
router.get('/friends',async(req,res)=>{await ensurePersonaIndexes();const friends=await SmartFriend.find({user:req.user._id}).sort({slot:1});res.json({ok:true,friends:friends.map(view),max:10,providerConfigured:providerConfigured(),provider:providerName()});});
router.post('/friends',async(req,res)=>{await ensurePersonaIndexes();const existing=await SmartFriend.find({user:req.user._id},{slot:1}).lean();const used=new Set(existing.map(x=>Number(x.slot)||1));const slot=Array.from({length:10},(_,i)=>i+1).find(n=>!used.has(n));if(!slot)return res.status(409).json({ok:false,message:'وصلت إلى الحد الأقصى: 10 شخصيات'});const friend=await SmartFriend.create({user:req.user._id,...normalize(req.body,slot)});res.status(201).json({ok:true,friend:view(friend)});});
router.put('/friends/:slot',async(req,res)=>{await ensurePersonaIndexes();const slot=Math.max(1,Math.min(10,Number(req.params.slot)||1)),data=normalize(req.body,slot);let friend=await SmartFriend.findOne({user:req.user._id,slot});if(friend){Object.assign(friend,data);await friend.save();}else{friend=await SmartFriend.create({user:req.user._id,...data});}res.json({ok:true,friend:view(friend)});});
router.post('/friends/:slot/avatar',upload.single('avatar'),async(req,res)=>{await ensurePersonaIndexes();const slot=Math.max(1,Math.min(10,Number(req.params.slot)||1));if(!req.file||!req.file.mimetype.startsWith('image/'))return res.status(400).json({ok:false,message:'اختر صورة JPG أو PNG أو WEBP'});const friend=await SmartFriend.findOne({user:req.user._id,slot});if(!friend)return res.status(404).json({ok:false,message:'احفظ الشخصية أولاً ثم اختر صورتها'});if(friend.avatarUrl&&friend.avatarUrl.startsWith('/uploads/smart-friend/'))fs.unlink(path.join(uploadDir,path.basename(friend.avatarUrl)),()=>{});friend.avatarUrl=`/uploads/smart-friend/${req.file.filename}`;await friend.save();res.json({ok:true,friend:view(friend)});});
router.delete('/friends/:slot',async(req,res)=>{await ensurePersonaIndexes();const slot=Number(req.params.slot);const f=await SmartFriend.findOne({user:req.user._id,slot});if(f){if(f.avatarUrl&&f.avatarUrl.startsWith('/uploads/smart-friend/'))fs.unlink(path.join(uploadDir,path.basename(f.avatarUrl)),()=>{});await Message.deleteMany({user:req.user._id,friend:f._id});await f.deleteOne();}res.json({ok:true});});
router.get('/me',async(req,res)=>{await ensurePersonaIndexes();const friend=await SmartFriend.findOne({user:req.user._id,slot:1});res.json({ok:true,friend:view(friend),providerConfigured:providerConfigured(),provider:providerName()});});
router.put('/me',async(req,res)=>{await ensurePersonaIndexes();const data=normalize(req.body,1),friend=await SmartFriend.findOneAndUpdate({user:req.user._id,slot:1},{$set:data},{new:true,upsert:true,setDefaultsOnInsert:true});res.json({ok:true,friend:view(friend)});});
router.get('/messages',async(req,res)=>{const q={user:req.user._id};if(req.query.friend)q.friend=req.query.friend;if(req.query.roomId)q.roomId=String(req.query.roomId);const items=await Message.find(q).sort({createdAt:-1}).limit(120).lean();res.json({ok:true,messages:items.reverse().map(messageView)});});
router.delete('/messages',async(req,res)=>{const q={user:req.user._id};if(req.query.friend)q.friend=req.query.friend;if(req.query.roomId)q.roomId=String(req.query.roomId);await Message.deleteMany(q);res.json({ok:true});});
router.post('/messages',upload.single('media'),async(req,res)=>{await ensurePersonaIndexes();const text=String(req.body.text||'').trim(),media=mediaFromFile(req.file);if((!text&&!media)||text.length>4000)return res.status(400).json({ok:false,message:'اكتب رسالة أو أرسل تسجيلًا صوتيًا/فيديو'});let friend=null;if(req.body.friendId)friend=await SmartFriend.findOne({_id:req.body.friendId,user:req.user._id});if(!friend)friend=await SmartFriend.findOne({user:req.user._id,slot:1});if(!friend)return res.status(409).json({ok:false,message:'أنشئ شخصية صديق ذكي أولاً'});const userMessage=await Message.create({user:req.user._id,friend:friend._id,role:'user',text,media:media||undefined});try{const recent=await Message.find({user:req.user._id,friend:friend._id}).sort({createdAt:-1}).limit(20).lean();const out=await askProvider(friend,recent.reverse().map(m=>({role:m.role,content:m.text||'',media:m.media&&m.media.url?{type:m.media.type,url:m.media.url,mimeType:m.media.mimeType}:undefined})));const saved=await Message.create({user:req.user._id,friend:friend._id,role:'assistant',text:out.answer});res.status(201).json({ok:true,emotion:out.emotion,userMessage:messageView(userMessage),message:messageView(saved)});}catch(e){res.status(e.status||502).json({ok:false,saved:messageView(userMessage),message:'حُفظت رسالتك لكن تعذر الرد: '+e.message});}});
router.post('/group',async(req,res)=>{await ensurePersonaIndexes();const text=String(req.body.text||'').trim();if(!text||text.length>4000)return res.status(400).json({ok:false,message:'اكتب رسالة للمجموعة'});const ids=Array.isArray(req.body.friendIds)?req.body.friendIds.slice(0,10):[];const allFriends=await SmartFriend.find({user:req.user._id,_id:{$in:ids}}).sort({slot:1});if(allFriends.length<2)return res.status(400).json({ok:false,message:'اختر شخصيتين على الأقل للحوار الجماعي'});const named=addressedFriends(text,allFriends);const friends=named.length?named:allFriends;const roomId=String(req.body.roomId||`group-${Date.now()}`).slice(0,80);await Message.create({user:req.user._id,roomId,role:'user',text});const transcript=[{role:'user',content:text}],replies=[];try{for(const friend of friends){const context=named.length?[...transcript,{role:'user',content:`الرسالة موجهة إليك بالاسم (${friend.name}). أجب أنت بصورة طبيعية، ولا تتحدث نيابة عن بقية الشخصيات.`}]:transcript;const out=await askProvider(friend,context);const saved=await Message.create({user:req.user._id,friend:friend._id,roomId,role:'assistant',text:out.answer});replies.push({...messageView(saved),friend:view(friend),emotion:out.emotion});transcript.push({role:'assistant',name:friend.name,content:out.answer});}res.status(201).json({ok:true,roomId,replies,addressed:named.map(view)});}catch(e){res.status(e.status||502).json({ok:false,roomId,replies,message:'توقفت الجولة لأن خدمة الذكاء الاصطناعي لم تكمل الرد: '+e.message});}});
module.exports=router;