plugins { id 'com.android.application' }

android {
    namespace 'iq.sumer.school'
    compileSdk 35
    defaultConfig {
        applicationId 'iq.sumer.school'
        minSdk 30
        targetSdk 35
        versionCode 4
        versionName '1.0.3'
    }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
