(()=>{'use strict';const $=(s)=>document.querySelector(s),tabs=[...document.querySelectorAll('[data-tab]')],signin=$('#signinPanel'),signup=$('#signupPanel'),verify=$('#verifyPanel');let verificationToken='';
function status(id,text,bad=false){const el=$(id);el.textContent=text;el.className='status '+(bad?'bad':'ok')}
async function api(path,options={}){const response=await fetch(path,{...options,headers:{Accept:'application/json','Content-Type':'application/json',...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw Object.assign(new Error(data.message||'تعذر تنفيذ الطلب'),{data,status:response.status});return data}
function tab(name){tabs.forEach(b=>b.classList.toggle('active',b.dataset.tab===name));signin.hidden=name!=='signin';signup.hidden=name==='signin';verify.hidden=true;if(name!=='signin'){const teacher=name==='teacher';$('#schoolRole').value=teacher?'teacher':'student';$('#signupTitle').textContent=teacher?'إنشاء حساب معلم':'إنشاء حساب طالب';$('#subjectsLabel').textContent=teacher?'المواد التي تدرّسها':'المواد التي تدرسها';}}
tabs.forEach(b=>b.onclick=()=>tab(b.dataset.tab));
$('#signinForm').onsubmit=async(e)=>{e.preventDefault();const button=e.currentTarget.querySelector('button');button.disabled=true;status('#signinStatus','جارٍ التحقق من الحساب…');try{const data=await api('/api/auth/signin',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});localStorage.setItem('token',data.token);localStorage.setItem('shnoUser',JSON.stringify(data.user||{}));location.href='dashboard.html'}catch(err){status('#signinStatus',err.message,true)}finally{button.disabled=false}};
$('#signupForm').onsubmit=async(e)=>{e.preventDefault();const button=e.currentTarget.querySelector('button[type=submit]'),body=Object.fromEntries(new FormData(e.currentTarget));body.termsAccepted=true;body.privacyAccepted=true;button.disabled=true;status('#signupStatus','جارٍ إنشاء حساب شنو منو وطلب المدرسة…');try{const data=await api('/api/auth/signup',{method:'POST',body:JSON.stringify(body)});if(data.verificationRequired){verificationToken=data.verificationToken;signup.hidden=true;verify.hidden=false;$('#verifyHint').textContent='أرسلنا رمزًا إلى '+(data.destination||'بريدك الإلكتروني')+'.'}else{status('#signupStatus',data.message+' يمكنك تسجيل الدخول الآن.');setTimeout(()=>tab('signin'),900)}}catch(err){status('#signupStatus',err.message,true)}finally{button.disabled=false}};
$('#verifyForm').onsubmit=async(e)=>{e.preventDefault();const button=e.currentTarget.querySelector('button');button.disabled=true;try{const code=new FormData(e.currentTarget).get('code');const data=await api('/api/auth/verify-registration',{method:'POST',body:JSON.stringify({verificationToken,code})});status('#verifyStatus',data.message+' انتقل لتسجيل الدخول.');setTimeout(()=>tab('signin'),1000)}catch(err){status('#verifyStatus',err.message,true)}finally{button.disabled=false}};
if(localStorage.getItem('token'))location.href='dashboard.html';if('serviceWorker'in navigator)navigator.serviceWorker.register('school-sw.js').catch(()=>{});
})();
