require('dotenv').config();

const express = require('express');
const multer = require('multer');
const http = require('http');
const cors = require('cors');
const connectDB = require('./config/db');

const authRoutes = require('./routes/auth.routes');
const adminRoutes = require('./routes/admin.routes');
const developerRoutes = require('./routes/developer.routes');
const userRoutes = require('./routes/user.routes');
const friendsRoutes = require('./routes/friends.routes');
const conversationRoutes = require('./routes/conversations.routes');
const phoneContactsRoutes = require('./routes/phone-contacts.routes');
const gameRoomRoutes = require('./routes/game-rooms.routes');
const gameActionRoutes = require('./routes/game-actions.routes');
const postRoutes = require('./routes/posts.routes');
const storyRoutes = require('./routes/stories.routes');
const reelRoutes = require('./routes/reels.routes');
const supportRoutes = require('./routes/support.routes');
const groupRoutes = require('./routes/groups.routes');
const islamicRoutes = require('./routes/islamic.routes');
const storesRoutes = require('./routes/stores.routes');
const consultationRoutes = require('./routes/consultations.routes');
const astrologyRoutes = require('./routes/astrology.routes');
const serviceApprovalsRoutes = require('./routes/service-approvals.routes');
const { attachSocket } = require('./socket');

const app = express();
const httpServer = http.createServer(app);
app.use(cors());
app.use(express.json({ limit: '1mb' }));
app.get('/api/health', (req, res) => res.json({ ok: true, service: 'shno-mano-tech-api' }));
app.use('/api/auth', authRoutes);
app.use('/api/admin', adminRoutes);
app.use('/api/developer', developerRoutes);
app.use('/api/service-approvals', serviceApprovalsRoutes);
app.use('/api/users', userRoutes);
app.use('/api/friends', friendsRoutes.router);
app.use('/api/conversations', conversationRoutes);
app.use('/api/phone-contacts', phoneContactsRoutes);
app.use('/api/game-rooms', gameRoomRoutes.router);
app.use('/api/game-actions', gameActionRoutes);
app.use('/api/posts', postRoutes);
app.use('/api/stories', storyRoutes);
app.use('/api/reels', reelRoutes);
app.use('/api/support', supportRoutes);
app.use('/api/groups', groupRoutes);
app.use('/api/islamic', islamicRoutes);
app.use('/api/stores', storesRoutes);
app.use('/api/consultations', consultationRoutes);
app.use('/api/astrology', astrologyRoutes);
app.use('/uploads', express.static(require('path').resolve(__dirname, '../../uploads')));
app.use((error, req, res, next) => { if (error instanceof multer.MulterError) return res.status(400).json({ ok:false, message:error.code==='LIMIT_FILE_SIZE'?'حجم الملف أكبر من الحد المسموح':'نوع أو عدد الملفات غير مسموح' }); if(error)return res.status(500).json({ok:false,message:error.message||'حدث خطأ في الخادم'}); next(); });
app.use((req,res)=>res.status(404).json({ok:false,message:'المسار غير موجود'}));
const port=Number(process.env.PORT||3000);
connectDB().then(()=>{app.set('io',attachSocket(httpServer));httpServer.listen(port,()=>console.log(`Server running on http://localhost:${port}`));}).catch(error=>{console.error('Server startup failed:',error.message);process.exit(1);});