const { Server } = require('socket.io');
const jwt = require('jsonwebtoken');
const User = require('./models/User');
const Conversation = require('./models/Conversation');
const GameRoom = require('./models/GameRoom');
const Group = require('./models/Group');
const { publicState, canSpectate, canVoice, decorate } = require('./routes/game-rooms.routes');
const { blocked, friends } = require('./routes/friends.routes');

class PrivateCallRegistry {
  constructor(){this.calls=new Map();this.users=new Map();}
  invite(call){if(!call.callId||!call.callerId||!call.calleeId||this.calls.has(call.callId)||this.users.has(call.callerId)||this.users.has(call.calleeId))return false;this.calls.set(call.callId,{...call,state:'ringing',createdAt:new Date()});this.users.set(call.callerId,call.callId);this.users.set(call.calleeId,call.callId);return true;}
  get(id){return this.calls.get(id)} accept(id,sid){const c=this.calls.get(id);if(!c||c.state!=='ringing')return false;c.state='accepted';c.calleeSocketId=sid;return true} end(id){const c=this.calls.get(id);if(!c)return null;this.calls.delete(id);this.users.delete(c.callerId);this.users.delete(c.calleeId);return c} forUser(uid){const id=this.users.get(String(uid));return id?this.calls.get(id):null} ringingFor(uid){const c=this.forUser(uid);return c?.state==='ringing'?c:null}
}

function attachSocket(httpServer){
  const io=new Server(httpServer,{cors:{origin:true,credentials:true}}),voiceRooms=new Map(),groupVoiceRooms=new Map(),privateCalls=new PrivateCallRegistry();
  const userRoom=id=>`user:${String(id)}`,userSocketCount=id=>io.sockets.adapter.rooms.get(userRoom(id))?.size||0,onlineUserIds=()=>Array.from(io.sockets.adapter.rooms.keys()).filter(r=>r.startsWith('user:')).map(r=>r.slice(5));
  io.use(async(socket,next)=>{try{const authorization=socket.handshake.headers.authorization||'',token=socket.handshake.auth?.token||authorization.replace(/^Bearer\s+/i,'');const payload=jwt.verify(token,process.env.JWT_SECRET),user=await User.findById(payload.userId);if(!user||user.status!=='active')return next(new Error('unauthorized'));socket.user=user;next()}catch{next(new Error('unauthorized'))}});
  io.on('connection',socket=>{
    const userId=String(socket.user._id),uRoom=userRoom(userId);socket.join(uRoom);if(userSocketCount(userId)===1){User.findByIdAndUpdate(socket.user._id,{$set:{'profile.online':true}}).catch(()=>{});socket.broadcast.emit('presence:online',{userId})}socket.emit('presence:state',{userIds:onlineUserIds().filter(id=>id!==userId)});
    const getGameRoom=async id=>{const r=await GameRoom.findById(id).catch(()=>null);return r?decorate(r):null};
    const emitSpectators=async roomId=>{const r=await GameRoom.findById(roomId).populate('spectators','fullName displayName username profile');if(!r)return;io.to(`game:${roomId}`).emit('game:spectators',{count:r.spectators.length,spectators:r.spectators.map(u=>({id:u._id,name:u.displayName||u.fullName,username:u.username,avatarUrl:u.profile?.avatarUrl||''}))})};
    socket.on('game:join',async({roomId}={},ack)=>{const r=await getGameRoom(roomId);if(!r||!r.players.some(id=>String(id)===userId))return typeof ack==='function'&&ack({ok:false,message:'هذه الغرفة لا تخصك'});socket.join(`game:${roomId}`);io.to(`game:${roomId}`).emit('game:state',publicState(r));if(typeof ack==='function')ack({ok:true,room:publicState(r)})});
    socket.on('game:spectate',async({roomId}={},ack)=>{const r=await getGameRoom(roomId);if(!r||!(await canSpectate(socket.user,r)))return typeof ack==='function'&&ack({ok:false,message:'لا تملك صلاحية مشاهدة هذه المباراة'});if(!r.spectators.some(id=>String(id)===userId)){r.spectators.push(socket.user._id);await r.save()}socket.join(`game:${roomId}`);socket.emit('game:state',publicState(r));await emitSpectators(roomId);if(typeof ack==='function')ack({ok:true,room:publicState(r)})});
    socket.on('game:spectator:leave',async({roomId}={})=>{const r=await getGameRoom(roomId);if(!r)return;r.spectators=r.spectators.filter(id=>String(id)!==userId);await r.save();socket.leave(`game:${roomId}`);await emitSpectators(roomId)});
    socket.on('game:chat:send',async({roomId,text}={},ack)=>{const r=await getGameRoom(roomId),inRoom=r&&(r.players.some(id=>String(id)===userId)||r.spectators.some(id=>String(id)===userId)||String(r.owner)===userId);const safe=String(text||'').trim().slice(0,500);if(!inRoom||!safe)return typeof ack==='function'&&ack({ok:false,message:'ادخل الطاولة أولاً'});const payload={roomId,userId,name:socket.user.displayName||socket.user.fullName||socket.user.username,avatarUrl:socket.user.profile?.avatarUrl||'',text:safe,createdAt:new Date().toISOString()};io.to(`game:${roomId}`).emit('game:chat:message',payload);if(typeof ack==='function')ack({ok:true})});
    socket.on('voice:join',async({roomId}={},ack)=>{const r=await getGameRoom(roomId),allowed=r&&(await canVoice(socket.user,r))&&(r.spectators.some(id=>String(id)===userId)||r.players.some(id=>String(id)===userId)||String(r.owner)===userId);if(!allowed)return typeof ack==='function'&&ack({ok:false,message:'لا تملك صلاحية الانضمام إلى صوت الغرفة'});if(!voiceRooms.has(String(roomId)))voiceRooms.set(String(roomId),new Map());voiceRooms.get(String(roomId)).set(userId,{id:socket.user._id,name:socket.user.displayName||socket.user.fullName,muted:true});socket.join(`voice:${roomId}`);const participants=Array.from(voiceRooms.get(String(roomId)).values());io.to(`voice:${roomId}`).emit('voice:participants',{roomId,participants});if(typeof ack==='function')ack({ok:true,participants})});
    socket.on('voice:mute-state',({roomId,muted}={})=>{const p=voiceRooms.get(String(roomId))?.get(userId);if(!p)return;p.muted=Boolean(muted);io.to(`voice:${roomId}`).emit('voice:mute-state',{roomId,userId,muted:p.muted})});
    socket.on('voice:leave',({roomId}={})=>{const ps=voiceRooms.get(String(roomId));if(!ps)return;ps.delete(userId);socket.leave(`voice:${roomId}`);io.to(`voice:${roomId}`).emit('voice:participants',{roomId,participants:Array.from(ps.values())});if(!ps.size)voiceRooms.delete(String(roomId))});
    const relayVoiceSignal=event=>({roomId,userId:target,data}={})=>{const ps=voiceRooms.get(String(roomId));if(!ps?.has(userId)||!ps.has(String(target)))return;io.to(`user:${target}`).emit(event,{roomId,from:socket.user._id,data})};socket.on('webrtc:voice-offer',relayVoiceSignal('webrtc:voice-offer'));socket.on('webrtc:voice-answer',relayVoiceSignal('webrtc:voice-answer'));socket.on('webrtc:voice-ice',relayVoiceSignal('webrtc:voice-ice'));
    const joinConversation=async(id,ack)=>{const c=await Conversation.findOne({_id:id,participants:socket.user._id}).catch(()=>null);if(!c)return typeof ack==='function'&&ack({ok:false,message:'forbidden'});socket.join(`conversation:${id}`);if(typeof ack==='function')ack({ok:true})};socket.on('private:join',joinConversation);socket.on('conversation:join',joinConversation);
    socket.on('private:typing',async({conversationId,active}={})=>{const c=await Conversation.findOne({_id:conversationId,participants:socket.user._id}).populate('participants','blockedUsers');if(!c)return;const other=c.participants.find(u=>String(u._id)!==userId);if(other&&!blocked(socket.user,other))io.to(`user:${other._id}`).emit('private:typing',{conversationId,active})});
    socket.on('private:message',async({conversationId,message}={})=>{const c=await Conversation.findOne({_id:conversationId,participants:socket.user._id}).populate('participants','blockedUsers');if(!c)return;const other=c.participants.find(u=>String(u._id)!==userId);if(other&&!blocked(socket.user,other))io.to(`conversation:${conversationId}`).emit('private:message',{conversationId,message,senderId:socket.user._id})});
    socket.on('disconnect',()=>{setTimeout(()=>{if(userSocketCount(userId)===0){User.findByIdAndUpdate(socket.user._id,{$set:{'profile.online':false,'profile.lastSeenAt':new Date()}}).catch(()=>{});io.emit('presence:offline',{userId})}},250)});
  });
  return io;
}
module.exports={attachSocket,PrivateCallRegistry};